/* This file was generated by the Hex-Rays decompiler version 9.0.0.241217.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn start(); // weak
int sub_1088009();
int __stdcall sub_1088044(_DWORD *a1, unsigned int a2, int a3, int a4);


//----- (01088000) --------------------------------------------------------
void __noreturn start()
{
  sub_1088009();
  __debugbreak();
}
// 1088000: using guessed type void __noreturn start();

//----- (01088009) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int sub_1088009()
{
  _DWORD *v0; // eax
  _BYTE *v2; // [esp-Ch] [ebp-Ch]
  int v3; // [esp-4h] [ebp-4h]
  _UNKNOWN *retaddr; // [esp+0h] [ebp+0h]

  v0 = v2 - 2940936;
  if ( *v2 == 0xCC )
  {
    *v2 = 0;
    v0 = (_DWORD *)sub_1088044(v0, 0x1000u, 1400805646, 1064891698);
  }
  retaddr = v0;
  return v3;
}
// 1088043: positive sp value C has been found
// 1088009: could not find valid save-restore pair for ebx
// 1088012: variable 'v2' is possibly undefined
// 1088042: variable 'v3' is possibly undefined

//----- (01088044) --------------------------------------------------------
int __stdcall sub_1088044(_DWORD *a1, unsigned int a2, int a3, int a4)
{
  unsigned int i; // ecx
  int v7; // [esp+4h] [ebp-4h]

  for ( i = a2 >> 2; i; --i )
  {
    *a1 ^= a3;
    *a1++ += a4;
  }
  return v7;
}
// 108806B: variable 'v7' is possibly undefined

// nfuncs=3 queued=3 decompiled=3 lumina nreq=0 worse=0 better=0
// ALL OK, 3 function(s) have been successfully decompiled
