/* This file was generated by the Hex-Rays decompiler version 7.7.0.220118.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

BOOL sub_401000();
int __cdecl sub_40107F(LPMSG lpMsg); // idb
BOOL sub_4010CC();
unsigned __int8 __cdecl sub_40112C(unsigned __int8 *a1, char a2);
LRESULT __cdecl sub_401147(HWND hDlg);
int sub_401196();
LRESULT __stdcall sub_4011B6(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
BOOL sub_4011EC();
LRESULT sub_401244();
BOOL __cdecl sub_40126F(HWND hWnd, WPARAM wParam);
LPSTR __cdecl sub_401290(LPSTR lpString1, LPCSTR lpString, int iMaxLength);
BOOL __cdecl sub_4012D2(int wParam, int a2);
BOOL __cdecl sub_401322(HWND hDlg);
void __cdecl sub_4013AB(HWND hDlg);
int sub_401401();
int sub_401474();
void __cdecl sub_4014B0(HWND hWnd, _DWORD *a2);
int __cdecl sub_40155C(HGDIOBJ h, HGDIOBJ *hdc, HPALETTE *a3, _DWORD *a4, _DWORD *a5);
LRESULT __cdecl sub_401689(HWND hWnd);
int __cdecl sub_4017FC(int a1, int a2, _BYTE *a3, int a4, int a5, int a6, int a7);
void sub_401867();
BOOL __cdecl sub_4018DF(int nIDDlgItem, LPCSTR a2, int a3);
HANDLE sub_401916();
BOOL __cdecl sub_401933(HWND hDlg, int *a2, BOOL bEnable);
BOOL sub_401976();
int __cdecl sub_401A85(HWND hDlg, int *a2, int a3, int a4, BOOL bRepaint);
int sub_401B33();
LPARAM __cdecl sub_401B72(LPARAM a1);
LRESULT sub_401C07();
unsigned __int64 __cdecl sub_401C2C(__int64 a1);
void sub_401C8E();
_BYTE *__cdecl sub_401CB6(_BYTE *a1, int a2, _WORD *a3);
HFONT sub_401CE9();
_DWORD *__thiscall sub_401D4A(_DWORD *this, int a2, unsigned int a3);
int __thiscall sub_401D98(int this, int a2, int a3);
void *__thiscall sub_401E1B(_DWORD *this, unsigned int a2);
_DWORD *__thiscall sub_401E34(_DWORD *this, int a2, unsigned int a3);
int __thiscall sub_401E7F(int this, int a2);
void *__thiscall sub_401EFA(_DWORD *this, unsigned int a2);
void __thiscall sub_401F13(_DWORD *this);
int sub_401F32();
BOOL sub_401FAF();
unsigned __int8 __cdecl sub_401FF4(int a1, char a2);
void sub_40200B();
INT_PTR __stdcall DialogFunc(HWND hWnd, UINT a2, WPARAM a3, _DWORD *a4);
BOOL __cdecl sub_402129(HWND hDlg, LPCSTR lpString);
const CHAR *__cdecl sub_40218D(LPSTR a1, int *a2, int a3, int a4);
void sub_402347();
_BYTE *__cdecl sub_4024C7(int a1, _BYTE *a2, int a3, int a4, int a5, int a6);
_BYTE *__cdecl sub_4024FE(int a1, _BYTE *a2, int a3, int a4, int a5, int a6);
LRESULT __cdecl sub_402535(int a1, int a2, unsigned __int16 a3, LPCSTR lpString, int a5);
BOOL sub_4025B1();
BOOL sub_40275E();
int sub_402915();
BOOL __cdecl sub_402976(int a1, int a2, _WORD *a3, int a4, int a5, __int16 a6);
int __cdecl sub_402AF0(LPCSTR lpFileName); // idb
BOOL __cdecl sub_402B3A(int a1, int a2);
int __cdecl sub_402C42(HWND hWnd, LPCSTR lpFileName); // idb
BOOL __cdecl sub_402DCD(char *SubStr);
void sub_402EF4();
void __thiscall sub_403041(_DWORD *this);
void __thiscall sub_40304C(_DWORD *this);
_DWORD *__thiscall sub_403057(_DWORD *this, char a2);
_DWORD *__thiscall sub_403073(_DWORD *this, char a2);
void __cdecl sub_40308F(LPCSTR lpString);
BOOL sub_4030B3();
int __cdecl sub_40315B(int a1);
LRESULT __stdcall sub_403294(HWND hWnd, UINT Msg, HDROP wParam, LPARAM lParam);
int __stdcall sub_4036C8(int a1, int a2, int a3);
void __cdecl sub_40370F(_DWORD *lpBuffer);
int __cdecl sub_4037C0(CHAR *lpString);
HWND sub_403814();
void sub_4038DB();
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
int __cdecl sub_4039A4(LPCSTR lpFileName); // idb
int __stdcall sub_403B01(HWND hDlg, int a2, unsigned __int16 a3, HWND hWnd);
_DWORD *__thiscall sub_403F2F(_DWORD *this);
int __thiscall sub_403F97(_DWORD *this, int a2);
int __thiscall sub_403FA5(_DWORD *this, int a2);
int __thiscall sub_403FB3(int this, LPCSTR lpString);
int __thiscall sub_404146(_DWORD *this);
int __thiscall sub_40414A(_DWORD *this);
int __thiscall sub_40414E(_DWORD *this, unsigned int a2);
int __thiscall sub_404164(_DWORD *this);
void __thiscall sub_404168(void *this);
void *__thiscall sub_404173(void *this, char a2);
// void *__cdecl operator new(unsigned int); idb
// void __cdecl operator delete(void *); idb
// int __cdecl atexit(void (__cdecl *)());
int __cdecl UserMathErrorFunction();
int sub_4043CA();
int sub_4043E4();
int sub_4043FE();
void __cdecl sub_404414(); // idb
void __cdecl sub_40441E(); // idb
void __cdecl sub_404428(); // idb

//-------------------------------------------------------------------------
// Data declarations

// extern int (__stdcall *ImageList_AddMasked)(HIMAGELIST himl, HBITMAP hbmImage, COLORREF crMask);
// extern HIMAGELIST (__stdcall *ImageList_Create)(int cx, int cy, UINT flags, int cInitial, int cGrow);
// extern BOOL (__stdcall *InitCommonControlsEx)(const INITCOMMONCONTROLSEX *picce);
// extern BOOL (__stdcall *ImageList_Destroy)(HIMAGELIST himl);
// extern BOOL (__stdcall *DeleteDC)(HDC hdc);
// extern BOOL (__stdcall *StretchBlt)(HDC hdcDest, int xDest, int yDest, int wDest, int hDest, HDC hdcSrc, int xSrc, int ySrc, int wSrc, int hSrc, DWORD rop);
// extern UINT (__stdcall *RealizePalette)(HDC hdc);
// extern HPALETTE (__stdcall *SelectPalette)(HDC hdc, HPALETTE hPal, BOOL bForceBkgd);
// extern HGDIOBJ (__stdcall *SelectObject)(HDC hdc, HGDIOBJ h);
// extern HDC (__stdcall *CreateCompatibleDC)(HDC hdc);
// extern HPALETTE (__stdcall *CreateHalftonePalette)(HDC hdc);
// extern HPALETTE (__stdcall *CreatePalette)(const LOGPALETTE *plpal);
// extern UINT (__stdcall *GetDIBColorTable)(HDC hdc, UINT iStart, UINT cEntries, RGBQUAD *prgbq);
// extern int (__stdcall *GetObjectA)(HANDLE h, int c, LPVOID pv);
// extern HFONT (__stdcall *CreateFontIndirectA)(const LOGFONTA *lplf);
// extern HBRUSH (__stdcall *CreateSolidBrush)(COLORREF color);
// extern HGDIOBJ (__stdcall *GetStockObject)(int i);
// extern BOOL (__stdcall *DeleteObject)(HGDIOBJ ho);
// extern LPSTR (__stdcall *lstrcpynA)(LPSTR lpString1, LPCSTR lpString2, int iMaxLength);
// extern int (__stdcall *lstrlenA)(LPCSTR lpString);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern HMODULE (__stdcall *LoadLibraryA)(LPCSTR lpLibFileName);
// extern BOOL (__stdcall *GlobalUnlock)(HGLOBAL hMem);
// extern LPVOID (__stdcall *GlobalLock)(HGLOBAL hMem);
// extern HGLOBAL (__stdcall *GlobalAlloc)(UINT uFlags, SIZE_T dwBytes);
// extern BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// extern DWORD (__stdcall *SetFilePointer)(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// extern HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern DWORD (__stdcall *GetTickCount)();
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern int (__stdcall *lstrcmpA)(LPCSTR lpString1, LPCSTR lpString2);
// extern BOOL (__stdcall *SetThreadPriority)(HANDLE hThread, int nPriority);
// extern int (__stdcall *GetThreadPriority)(HANDLE hThread);
// extern HANDLE (__stdcall *GetCurrentThread)();
// extern BOOL (__stdcall *FreeLibrary)(HMODULE hLibModule);
// extern char *(__cdecl *strlwr)(char *String);
// extern char *(__cdecl *strstr)(const char *Str, const char *SubStr);
// extern int (*sprintf)(char *const Buffer, const char *const Format, ...);
// extern void *(__cdecl *memmove)(void *, const void *Src, size_t Size);
// extern void *(__cdecl *malloc)(size_t Size);
// extern void (__cdecl *free)(void *Block);
// extern char *(__cdecl *strchr)(const char *Str, int Val);
// extern void *(__cdecl *calloc)(size_t Count, size_t Size);
// extern int (__cdecl *stricmp)(const char *String1, const char *String2);
// extern void (__stdcall *DragAcceptFiles)(HWND hWnd, BOOL fAccept);
// extern UINT (__stdcall *DragQueryFileA)(HDROP hDrop, UINT iFile, LPSTR lpszFile, UINT cch);
// extern HWND (__stdcall *SetFocus)(HWND hWnd);
// extern HWND (__stdcall *CreateWindowExA)(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
// extern int (__stdcall *GetSystemMetrics)(int nIndex);
// extern ATOM (__stdcall *RegisterClassExA)(const WNDCLASSEXA *);
// extern HCURSOR (__stdcall *LoadCursorA)(HINSTANCE hInstance, LPCSTR lpCursorName);
// extern HICON (__stdcall *LoadIconA)(HINSTANCE hInstance, LPCSTR lpIconName);
// extern BOOL (__stdcall *TrackPopupMenu)(HMENU hMenu, UINT uFlags, int x, int y, int nReserved, HWND hWnd, const RECT *prcRect);
// extern HMENU (__stdcall *GetSubMenu)(HMENU hMenu, int nPos);
// extern BOOL (__stdcall *GetCursorPos)(LPPOINT lpPoint);
// extern void (__stdcall *PostQuitMessage)(int nExitCode);
// extern HWND (__stdcall *CreateDialogParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// extern int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// extern BOOL (__stdcall *OpenClipboard)(HWND hWndNewOwner);
// extern BOOL (__stdcall *EmptyClipboard)();
// extern BOOL (__stdcall *CloseClipboard)();
// extern BOOL (__stdcall *SetWindowTextA)(HWND hWnd, LPCSTR lpString);
// extern BOOL (__stdcall *SetForegroundWindow)(HWND hWnd);
// extern BOOL (__stdcall *PostMessageA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern HMENU (__stdcall *LoadMenuA)(HINSTANCE hInstance, LPCSTR lpMenuName);
// extern LRESULT (__stdcall *SendDlgItemMessageA)(HWND hDlg, int nIDDlgItem, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *GetClientRect)(HWND hWnd, LPRECT lpRect);
// extern HMENU (__stdcall *GetMenu)(HWND hWnd);
// extern BOOL (__stdcall *AdjustWindowRect)(LPRECT lpRect, DWORD dwStyle, BOOL bMenu);
// extern BOOL (__stdcall *GetWindowRect)(HWND hWnd, LPRECT lpRect);
// extern BOOL (__stdcall *DestroyMenu)(HMENU hMenu);
// extern BOOL (__stdcall *DestroyWindow)(HWND hWnd);
// extern BOOL (__stdcall *IsDialogMessageA)(HWND hDlg, LPMSG lpMsg);
// extern LRESULT (__stdcall *DefWindowProcA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern UINT (__stdcall *GetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// extern HANDLE (__stdcall *SetClipboardData)(UINT uFormat, HANDLE hMem);
// extern BOOL (__stdcall *ScreenToClient)(HWND hWnd, LPPOINT lpPoint);
// extern BOOL (__stdcall *MoveWindow)(HWND hWnd, int X, int Y, int nWidth, int nHeight, BOOL bRepaint);
// extern BOOL (__stdcall *EnableWindow)(HWND hWnd, BOOL bEnable);
// extern int (*wsprintfA)(LPSTR, LPCSTR, ...);
// extern BOOL (__stdcall *SetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPCSTR lpString);
// extern HBITMAP (__stdcall *LoadBitmapA)(HINSTANCE hInstance, LPCSTR lpBitmapName);
// extern HANDLE (__stdcall *LoadImageA)(HINSTANCE hInst, LPCSTR name, UINT type, int cx, int cy, UINT fuLoad);
// extern HDC (__stdcall *GetDC)(HWND hWnd);
// extern int (__stdcall *ReleaseDC)(HWND hWnd, HDC hDC);
// extern HDC (__stdcall *BeginPaint)(HWND hWnd, LPPAINTSTRUCT lpPaint);
// extern BOOL (__stdcall *EndPaint)(HWND hWnd, const PAINTSTRUCT *lpPaint);
// extern UINT (__stdcall *GetDlgItemInt)(HWND hDlg, int nIDDlgItem, BOOL *lpTranslated, BOOL bSigned);
// extern BOOL (__stdcall *SetDlgItemInt)(HWND hDlg, int nIDDlgItem, UINT uValue, BOOL bSigned);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern BOOL (__stdcall *InvalidateRect)(HWND hWnd, const RECT *lpRect, BOOL bErase);
// extern BOOL (__stdcall *SetWindowPos)(HWND hWnd, HWND hWndInsertAfter, int X, int Y, int cx, int cy, UINT uFlags);
// extern BOOL (__stdcall *UpdateWindow)(HWND hWnd);
// extern LONG (__stdcall *GetWindowLongA)(HWND hWnd, int nIndex);
// extern LRESULT (__stdcall *CallWindowProcA)(WNDPROC lpPrevWndFunc, HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *HideCaret)(HWND hWnd);
// extern HWND (__stdcall *GetDlgItem)(HWND hDlg, int nIDDlgItem);
// extern LRESULT (__stdcall *SendMessageA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *PeekMessageA)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg);
// extern BOOL (__stdcall *GetMessageA)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
// extern BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg);
// extern LRESULT (__stdcall *DispatchMessageA)(const MSG *lpMsg);
// extern BOOL (__stdcall *CopyRect)(LPRECT lprcDst, const RECT *lprcSrc);
// extern BOOL (__stdcall *GetOpenFileNameA)(LPOPENFILENAMEA);
// extern BOOL (__stdcall *GetSaveFileNameA)(LPOPENFILENAMEA);
_UNKNOWN unk_405376; // weak
int dword_405BE0[6] = { 1006, 0, 8, 0, 0, 0 }; // weak
int dword_405BF8[22] =
{
  1000,
  0,
  0,
  1005,
  0,
  0,
  1090,
  0,
  0,
  1012,
  0,
  0,
  1011,
  0,
  0,
  1010,
  0,
  0,
  0,
  0,
  0,
  0
}; // weak
int dword_406020[] = { 0 }; // weak
int (__thiscall *off_406040[2])(void *, char) = { &sub_403057, &sub_403073 }; // weak
int (__thiscall *off_406044)(void *, char) = &sub_403073; // weak
int (__thiscall *off_4061FC)(void *, char) = &sub_404173; // weak
void *off_407020 = &unk_405360; // weak
HWND dword_4070CC = NULL; // idb
_UNKNOWN unk_4070D0; // weak
char *off_4070D4 = "Search"; // weak
void *off_4070DC = &unk_405C50; // weak
HWND dword_4070E0 = NULL; // idb
char *off_407108[4] = { "File pos", "Mem pos", "ID", "Text" }; // weak
char *off_40710C[3] = { "Mem pos", "ID", "Text" }; // weak
char *off_407110[2] = { "ID", "Text" }; // weak
char *off_407114 = "Text"; // weak
char a0123456789abcd[17] = "0123456789ABCDEF"; // weak
HWND dword_407138 = NULL; // idb
HGDIOBJ dword_40713C = NULL; // idb
int dword_407140 = 0; // weak
HGDIOBJ hPal = NULL; // idb
HANDLE hFile = NULL; // idb
HMODULE hLibModule = NULL; // idb
int dword_407150 = 0; // weak
int dword_407154 = 0; // weak
LPCSTR lpBuffer = NULL; // idb
char String1[1028] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  
}; // idb
int dword_407564; // weak
HGDIOBJ wParam; // idb
UINT uValue; // idb
int dword_407570; // idb
int dword_407574; // weak
HWND dword_407578; // idb
char byte_4075C0; // weak
char String2[1028]; // idb
int dword_407A04; // weak
int dword_407A08; // weak
int dword_407A0C; // weak
HMENU hMenu; // idb
int hSrc; // idb
HIMAGELIST lParam; // idb
int dword_407A24; // weak
HINSTANCE hInstance; // idb
CHAR FileName; // idb
int dword_407B34; // weak
int dword_407B38; // weak
int dword_407B3C; // weak
int dword_407B40; // weak
int wSrc; // idb
UINT dword_407B48; // idb
int dword_407B4C; // weak
LPCSTR lpString; // idb
HWND hDlg; // idb
struct tagRECT Rect; // idb
int dword_407B68; // weak
char byte_407B70[256]; // weak
int dword_407C70; // idb
HGDIOBJ hdc; // idb
struct tagRECT rcDst; // idb
LPVOID Block; // idb
int dword_407C8C; // idb
HWND hWnd; // idb
int dword_407C94; // weak
HWND hWndParent; // idb
_DWORD dword_407C9C[4]; // weak
_DWORD dword_407CAC[4]; // weak
_DWORD dword_407CBC[11]; // weak
_UNKNOWN unk_407CE8; // weak
_UNKNOWN unk_407CF0; // weak


//----- (00401000) --------------------------------------------------------
BOOL sub_401000()
{
  HWND *v0; // edi

  ImageList_Destroy(lParam);
  v0 = &dword_4070CC;
  do
  {
    DestroyWindow(*v0);
    v0 += 5;
  }
  while ( (int)v0 < (int)off_407108 );
  DestroyWindow(hDlg);
  DeleteObject(wParam);
  DeleteObject(dword_40713C);
  DeleteObject(hdc);
  DeleteObject(hPal);
  DestroyMenu(hMenu);
  hdc = 0;
  hPal = 0;
  return FreeLibrary(hLibModule);
}
// 407108: using guessed type char *off_407108[4];

//----- (0040107F) --------------------------------------------------------
int __cdecl sub_40107F(LPMSG lpMsg)
{
  HWND *v2; // edi

  if ( IsDialogMessageA(hDlg, lpMsg) || IsDialogMessageA(dword_407578, lpMsg) )
    return 0;
  v2 = &dword_4070CC;
  while ( !IsDialogMessageA(*v2, lpMsg) )
  {
    v2 += 5;
    if ( (int)v2 >= (int)off_407108 )
      return 1;
  }
  return 0;
}
// 407108: using guessed type char *off_407108[4];

//----- (004010CC) --------------------------------------------------------
BOOL sub_4010CC()
{
  struct tagMSG Msg; // [esp+4h] [ebp-1Ch] BYREF

  if ( !PeekMessageA(&Msg, 0, 0, 0, 0) )
    return dword_407A04 == 0;
  if ( GetMessageA(&Msg, 0, 0, 0) )
  {
    if ( sub_40107F(&Msg) )
    {
      TranslateMessage(&Msg);
      DispatchMessageA(&Msg);
    }
    return dword_407A04 == 0;
  }
  return 0;
}
// 407A04: using guessed type int dword_407A04;

//----- (0040112C) --------------------------------------------------------
unsigned __int8 __cdecl sub_40112C(unsigned __int8 *a1, char a2)
{
  unsigned __int8 result; // al

  while ( 1 )
  {
    result = *a1;
    if ( !*a1 )
      break;
    byte_407B70[result] = a2;
    ++a1;
  }
  return result;
}

//----- (00401147) --------------------------------------------------------
LRESULT __cdecl sub_401147(HWND hDlg)
{
  unsigned int v1; // edi
  void **v2; // esi
  _BYTE *v3; // eax
  unsigned __int8 v4; // dl
  HWND DlgItem; // eax
  LRESULT result; // eax
  WPARAM v7; // [esp-8h] [ebp-10h]

  v1 = 1024;
  v2 = &off_407020;
  do
  {
    v3 = *v2;
    v4 = -1;
    while ( *v3 )
      v4 &= byte_407B70[(unsigned __int8)*v3++];
    v7 = v4;
    DlgItem = GetDlgItem(hDlg, v1);
    result = SendMessageA(DlgItem, 0xF1u, v7, 0);
    ++v1;
    ++v2;
  }
  while ( v1 <= 0x42A );
  return result;
}
// 407020: using guessed type void *off_407020;

//----- (00401196) --------------------------------------------------------
int sub_401196()
{
  sub_403F97(dword_407CBC, 0x400000);
  return sub_403FA5(dword_407CBC, 0x20000);
}
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (004011B6) --------------------------------------------------------
LRESULT __stdcall sub_4011B6(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
  LRESULT (__stdcall *WindowLongA)(HWND, UINT, WPARAM, LPARAM); // eax
  LRESULT result; // eax

  WindowLongA = (LRESULT (__stdcall *)(HWND, UINT, WPARAM, LPARAM))GetWindowLongA(hWnd, -21);
  result = CallWindowProcA(WindowLongA, hWnd, Msg, wParam, lParam);
  if ( Msg == 7 )
  {
    HideCaret(hWnd);
    return 0;
  }
  return result;
}

//----- (004011EC) --------------------------------------------------------
BOOL sub_4011EC()
{
  HWND v0; // ebx
  HWND v1; // ebp

  if ( dword_407C94 )
  {
    v0 = hWnd;
    v1 = dword_407138;
  }
  else
  {
    v0 = dword_407138;
    v1 = hWnd;
  }
  SetWindowPos(v0, HWND_MESSAGE|0x2, 0, 0, 0, 0, 0x67u);
  SetWindowPos(v1, (HWND)1, 0, 0, 0, 0, 0xA7u);
  UpdateWindow(v0);
  return UpdateWindow(v1);
}
// 407C94: using guessed type int dword_407C94;

//----- (00401244) --------------------------------------------------------
LRESULT sub_401244()
{
  SendMessageA(hWnd, 0x1009u, 0, 0);
  return SendMessageA(dword_407138, 0xCu, 0, (LPARAM)&unk_405376);
}

//----- (0040126F) --------------------------------------------------------
BOOL __cdecl sub_40126F(HWND hWnd, WPARAM wParam)
{
  SendMessageA(hWnd, 0xBu, wParam, 0);
  return InvalidateRect(hWnd, 0, 1);
}

//----- (00401290) --------------------------------------------------------
LPSTR __cdecl sub_401290(LPSTR lpString1, LPCSTR lpString, int iMaxLength)
{
  int v3; // edi
  LPSTR result; // eax

  if ( *lpString != 34 )
    return lstrcpynA(lpString1, lpString, iMaxLength);
  v3 = lstrlenA(lpString);
  result = lstrcpynA(lpString1, lpString + 1, iMaxLength);
  if ( v3 > 1 )
    lpString1[v3 - 2] = 0;
  return result;
}

//----- (004012D2) --------------------------------------------------------
BOOL __cdecl sub_4012D2(int wParam, int a2)
{
  BOOL result; // eax

  if ( a2 )
    SendMessageA(dword_407578, 0x130Cu, wParam, 0);
  ShowWindow(*(&dword_4070CC + 5 * dword_407B34), 0);
  result = ShowWindow(*(&dword_4070CC + 5 * wParam), 5);
  dword_407B34 = wParam;
  return result;
}
// 407B34: using guessed type int dword_407B34;

//----- (00401322) --------------------------------------------------------
BOOL __cdecl sub_401322(HWND hDlg)
{
  UINT DlgItemInt; // eax

  uValue = GetDlgItemInt(hDlg, 1001, 0, 0);
  if ( !uValue )
    uValue = 5;
  DlgItemInt = GetDlgItemInt(hDlg, 1003, 0, 0);
  dword_407B48 = DlgItemInt;
  if ( DlgItemInt )
  {
    if ( DlgItemInt <= 0x400 )
      goto LABEL_8;
    DlgItemInt = 1024;
  }
  else
  {
    DlgItemInt = 1024;
  }
  dword_407B48 = 1024;
LABEL_8:
  if ( uValue > DlgItemInt )
    uValue = DlgItemInt;
  SetDlgItemInt(hDlg, 1001, uValue, 0);
  return SetDlgItemInt(hDlg, 1003, dword_407B48, 0);
}

//----- (004013AB) --------------------------------------------------------
void __cdecl sub_4013AB(HWND hDlg)
{
  unsigned int DlgItemInt; // eax

  if ( dword_407154 )
  {
    DlgItemInt = GetDlgItemInt(hDlg, 1072, 0, 0);
    dword_407150 = DlgItemInt;
    if ( DlgItemInt >= 2 )
    {
      if ( DlgItemInt <= dword_407B48 )
      {
LABEL_7:
        SetDlgItemInt(hDlg, 1072, DlgItemInt, 0);
        return;
      }
      DlgItemInt = dword_407B48;
    }
    else
    {
      DlgItemInt = 3;
    }
    dword_407150 = DlgItemInt;
    goto LABEL_7;
  }
  dword_407150 = -1;
}
// 407150: using guessed type int dword_407150;
// 407154: using guessed type int dword_407154;

//----- (00401401) --------------------------------------------------------
int sub_401401()
{
  unsigned int v0; // eax
  LPCSTR i; // ecx
  unsigned __int8 v2; // al
  unsigned __int8 v3; // al
  char *v4; // esi

  v0 = lstrlenA(lpString);
  if ( v0 < uValue || v0 > dword_407B48 )
    return 0;
  for ( i = lpString; *i; ++i )
  {
    v2 = *i;
    if ( !byte_407B70[v2] )
      return 0;
  }
  if ( dword_407A08 )
  {
    v3 = byte_4075C0;
    v4 = &byte_4075C0;
    while ( v3 )
    {
      ++v4;
      if ( !strchr(lpString, v3) )
        return 0;
      v3 = *v4;
    }
  }
  return 1;
}
// 4075C0: using guessed type char byte_4075C0;
// 407A08: using guessed type int dword_407A08;

//----- (00401474) --------------------------------------------------------
int sub_401474()
{
  unsigned __int8 v0; // al
  char *v1; // esi

  if ( dword_407A08 )
  {
    v0 = byte_4075C0;
    v1 = &byte_4075C0;
    while ( v0 )
    {
      ++v1;
      if ( !strchr(lpString, v0) )
        return 0;
      v0 = *v1;
    }
  }
  return 1;
}
// 4075C0: using guessed type char byte_4075C0;
// 407A08: using guessed type int dword_407A08;

//----- (004014B0) --------------------------------------------------------
void __cdecl sub_4014B0(HWND hWnd, _DWORD *a2)
{
  HDC v2; // edi
  HDC CompatibleDC; // ebx
  struct tagPAINTSTRUCT Paint; // [esp+8h] [ebp-40h] BYREF

  v2 = (HDC)a2[6];
  if ( hdc )
  {
    if ( hPal )
    {
      BeginPaint(hWnd, &Paint);
      CompatibleDC = CreateCompatibleDC(v2);
      SelectObject(CompatibleDC, hdc);
      SelectPalette(v2, (HPALETTE)hPal, 0);
      RealizePalette(v2);
      StretchBlt(v2, a2[7], a2[8], a2[9] - a2[7], a2[10] - a2[8], CompatibleDC, 0, 0, wSrc, hSrc, 0xCC0020u);
      DeleteDC(CompatibleDC);
      EndPaint(hWnd, &Paint);
    }
  }
}

//----- (0040155C) --------------------------------------------------------
int __cdecl sub_40155C(HGDIOBJ h, HGDIOBJ *hdc, HPALETTE *a3, _DWORD *a4, _DWORD *a5)
{
  HANDLE ImageA; // eax
  int v8; // esi
  int v9; // eax
  HDC DC; // esi
  RGBQUAD prgbq[256]; // [esp+Ch] [ebp-81Ch] BYREF
  LOGPALETTE plpal; // [esp+40Ch] [ebp-41Ch] BYREF
  char pv[4]; // [esp+810h] [ebp-18h] BYREF
  int v14; // [esp+814h] [ebp-14h]
  int v15; // [esp+818h] [ebp-10h]
  unsigned __int16 v16; // [esp+820h] [ebp-8h]
  unsigned __int16 v17; // [esp+822h] [ebp-6h]
  HGDIOBJ ha; // [esp+830h] [ebp+8h]
  HDC hdca; // [esp+834h] [ebp+Ch]

  *hdc = 0;
  *a3 = 0;
  ImageA = LoadImageA(hInstance, (LPCSTR)(unsigned __int16)h, 0, 0, 0, 0x2040u);
  *hdc = ImageA;
  if ( !ImageA )
    return 0;
  GetObjectA(ImageA, 24, pv);
  if ( v17 * v16 > 8 )
  {
    DC = GetDC(0);
    *a3 = CreateHalftonePalette(DC);
    ReleaseDC(0, DC);
  }
  else
  {
    hdca = CreateCompatibleDC(0);
    ha = SelectObject(hdca, *hdc);
    v8 = 256;
    GetDIBColorTable(hdca, 0, 0x100u, prgbq);
    plpal.palVersion = 768;
    plpal.palNumEntries = 256;
    v9 = 0;
    do
    {
      plpal.palPalEntry[v9].peRed = prgbq[v9].rgbRed;
      plpal.palPalEntry[v9].peGreen = prgbq[v9].rgbGreen;
      plpal.palPalEntry[v9].peBlue = prgbq[v9].rgbBlue;
      plpal.palPalEntry[v9++].peFlags = 0;
      --v8;
    }
    while ( v8 );
    *a3 = CreatePalette(&plpal);
    SelectObject(hdca, ha);
    DeleteDC(hdca);
  }
  *a4 = v14;
  *a5 = v15;
  return 1;
}
// 40155C: using guessed type char pv[4];
// 40155C: using guessed type RGBQUAD prgbq[256];

//----- (00401689) --------------------------------------------------------
LRESULT __cdecl sub_401689(HWND hWnd)
{
  LRESULT result; // eax
  LPARAM lParam[2]; // [esp+Ch] [ebp-2Ch] BYREF
  int v3; // [esp+14h] [ebp-24h]
  char *v4; // [esp+18h] [ebp-20h]
  int v5; // [esp+20h] [ebp-18h]
  HBITMAP hbmImage; // [esp+2Ch] [ebp-Ch]
  HBITMAP BitmapA; // [esp+30h] [ebp-8h]
  HBITMAP v8; // [esp+34h] [ebp-4h]

  SendMessageA(::hWnd, 0x1036u, 0, 32);
  SendMessageA(hWnd, 0x1001u, 0, 0xFFFFFF);
  SendMessageA(hWnd, 0x1026u, 0, 0xFFFFFF);
  SendMessageA(hWnd, 0x1024u, 0, 0);
  ::lParam = ImageList_Create(12, 12, 0, 3, 1);
  hbmImage = LoadBitmapA(hInstance, (LPCSTR)0x88);
  BitmapA = LoadBitmapA(hInstance, (LPCSTR)0x89);
  v8 = LoadBitmapA(hInstance, (LPCSTR)0x8A);
  ImageList_AddMasked(::lParam, hbmImage, 0);
  ImageList_AddMasked(::lParam, BitmapA, 0);
  ImageList_AddMasked(::lParam, v8, 0);
  SendMessageA(hWnd, 0x1003u, 1u, (LPARAM)::lParam);
  DeleteObject(v8);
  DeleteObject(BitmapA);
  DeleteObject(hbmImage);
  v4 = off_407108[0];
  lParam[0] = 15;
  lParam[1] = 0;
  v3 = 96;
  v5 = 0;
  SendMessageA(hWnd, 0x101Bu, 0, (LPARAM)lParam);
  v4 = off_40710C[0];
  v3 = 96;
  SendMessageA(hWnd, 0x101Bu, 1u, (LPARAM)lParam);
  v4 = off_407110[0];
  v3 = 42;
  SendMessageA(hWnd, 0x101Bu, 2u, (LPARAM)lParam);
  v4 = off_407114;
  v3 = 800;
  result = SendMessageA(hWnd, 0x101Bu, 3u, (LPARAM)lParam);
  dword_407B38 = -1;
  dword_407564 = 1;
  return result;
}
// 407108: using guessed type char *off_407108[4];
// 40710C: using guessed type char *off_40710C[3];
// 407110: using guessed type char *off_407110[2];
// 407114: using guessed type char *off_407114;
// 407564: using guessed type int dword_407564;
// 407B38: using guessed type int dword_407B38;

//----- (004017FC) --------------------------------------------------------
int __cdecl sub_4017FC(int a1, int a2, _BYTE *a3, int a4, int a5, int a6, int a7)
{
  int result; // eax
  HINSTANCE v8; // esi

  result = a1;
  *a3 = 0;
  *(_DWORD *)(a1 + 4) = a2;
  *(_DWORD *)a1 = 76;
  v8 = hInstance;
  *(_DWORD *)(a1 + 28) = a3;
  *(_DWORD *)(a1 + 32) = a4;
  *(_DWORD *)(a1 + 8) = v8;
  *(_DWORD *)(a1 + 48) = a5;
  *(_DWORD *)(a1 + 12) = a6;
  *(_DWORD *)(a1 + 16) = 0;
  *(_DWORD *)(a1 + 20) = 0;
  *(_DWORD *)(a1 + 24) = 0;
  *(_DWORD *)(a1 + 36) = 0;
  *(_DWORD *)(a1 + 40) = 0;
  *(_DWORD *)(a1 + 44) = 0;
  *(_DWORD *)(a1 + 52) = 6;
  *(_WORD *)(a1 + 56) = 0;
  *(_WORD *)(a1 + 58) = 0;
  *(_DWORD *)(a1 + 60) = a7;
  *(_DWORD *)(a1 + 64) = 0;
  *(_DWORD *)(a1 + 68) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  return result;
}

//----- (00401867) --------------------------------------------------------
void sub_401867()
{
  int v0; // edi
  char *v1; // esi
  char *v2; // edi
  int v3; // ecx
  char v4; // al
  int v6; // [esp+8h] [ebp-Ch]
  int v7; // [esp+Ch] [ebp-8h]
  char *lParam; // [esp+10h] [ebp-4h]

  v0 = sub_404146(dword_407CBC);
  v7 = v0;
  if ( v0 )
  {
    v6 = sub_404164(dword_407CBC);
    lParam = (char *)malloc(v0 + 1);
    v1 = (char *)v6;
    v2 = lParam;
    v3 = v7;
    do
    {
      v4 = *v1++;
      if ( !v4 )
        v4 = 32;
      *v2++ = v4;
    }
    while ( v3-- > 1 );
    *v2 = v3;
    SendMessageA(dword_407138, 0xC2u, 0, (LPARAM)lParam);
    free(lParam);
  }
}
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (004018DF) --------------------------------------------------------
BOOL __cdecl sub_4018DF(int nIDDlgItem, LPCSTR a2, int a3)
{
  CHAR String[256]; // [esp+0h] [ebp-100h] BYREF

  wsprintfA(String, a2, a3);
  return SetDlgItemTextA(dword_4070CC, nIDDlgItem, String);
}

//----- (00401916) --------------------------------------------------------
HANDLE sub_401916()
{
  HANDLE result; // eax

  result = hFile;
  if ( hFile && hFile != (HANDLE)-1 )
    result = (HANDLE)CloseHandle(hFile);
  hFile = 0;
  return result;
}

//----- (00401933) --------------------------------------------------------
BOOL __cdecl sub_401933(HWND hDlg, int *a2, BOOL bEnable)
{
  HWND DlgItem; // eax

  while ( *a2 )
  {
    DlgItem = GetDlgItem(hDlg, *a2);
    EnableWindow(DlgItem, bEnable);
    a2 += 3;
  }
  InvalidateRect(hWndParent, 0, 1);
  return UpdateWindow(hWndParent);
}

//----- (00401976) --------------------------------------------------------
BOOL sub_401976()
{
  DWORD WindowLongA; // eax
  HWND *v1; // esi
  HMENU Menu; // [esp-4h] [ebp-30h]
  struct tagRECT v4; // [esp+Ch] [ebp-20h] BYREF
  struct tagRECT Rect; // [esp+1Ch] [ebp-10h] BYREF

  GetClientRect(hDlg, &Rect);
  Menu = GetMenu(hWndParent);
  WindowLongA = GetWindowLongA(hWndParent, -16);
  AdjustWindowRect(&Rect, WindowLongA, (BOOL)Menu);
  SetWindowPos(hWndParent, 0, 0, 0, Rect.right - Rect.left, Rect.bottom - Rect.top, 6u);
  GetWindowRect(dword_407578, &Rect);
  ScreenToClient(hWndParent, (LPPOINT)&Rect);
  ScreenToClient(hWndParent, (LPPOINT)&Rect.right);
  GetClientRect(dword_407578, &v4);
  SendMessageA(dword_407578, 0x1328u, 0, (LPARAM)&v4);
  v1 = &dword_4070CC;
  do
  {
    MoveWindow(*v1, Rect.left + v4.left, Rect.top + v4.top, v4.right - v4.left, v4.bottom - v4.top, 1);
    v1 += 5;
  }
  while ( (int)v1 < (int)off_407108 );
  ShowWindow(hDlg, 5);
  dword_407B34 = 0;
  return ShowWindow(dword_4070CC, 5);
}
// 407108: using guessed type char *off_407108[4];
// 407B34: using guessed type int dword_407B34;

//----- (00401A85) --------------------------------------------------------
int __cdecl sub_401A85(HWND hDlg, int *a2, int a3, int a4, BOOL bRepaint)
{
  int *v5; // ecx
  int result; // eax
  int v7; // ebx
  HWND DlgItem; // edi
  struct tagRECT Rect; // [esp+0h] [ebp-10h] BYREF

  v5 = a2;
  for ( result = *a2; *v5; a2 = v5 )
  {
    v7 = v5[2];
    if ( v7 )
    {
      DlgItem = GetDlgItem(hDlg, result);
      GetWindowRect(DlgItem, &Rect);
      if ( (v7 & 1) != 0 )
        Rect.left += a3;
      if ( (v7 & 2) != 0 )
        Rect.top += a4;
      if ( (v7 & 4) != 0 )
        Rect.right += a3;
      if ( (v7 & 8) != 0 )
        Rect.bottom += a4;
      ScreenToClient(hDlg, (LPPOINT)&Rect);
      ScreenToClient(hDlg, (LPPOINT)&Rect.right);
      MoveWindow(DlgItem, Rect.left, Rect.top, Rect.right - Rect.left, Rect.bottom - Rect.top, bRepaint);
      v5 = a2;
    }
    v5 += 3;
    result = *v5;
  }
  return result;
}

//----- (00401B33) --------------------------------------------------------
int sub_401B33()
{
  void **v0; // edi
  HWND v1; // ebx
  int *i; // esi
  int result; // eax

  v0 = &off_4070DC;
  do
  {
    v1 = (HWND)*(v0 - 4);
    for ( i = (int *)*v0; ; i += 3 )
    {
      result = *i;
      if ( !*i )
        break;
      if ( (i[1] & 1) != 0 )
        SendDlgItemMessageA(v1, result, 0x30u, (WPARAM)wParam, 1);
    }
    v0 += 5;
  }
  while ( (int)v0 < (int)a0123456789abcd );
  return result;
}
// 4070DC: using guessed type void *off_4070DC;

//----- (00401B72) --------------------------------------------------------
LPARAM __cdecl sub_401B72(LPARAM a1)
{
  LPARAM result; // eax
  LRESULT v2; // eax
  LPARAM lParam[3]; // [esp+Ch] [ebp-18h] BYREF
  LPARAM v4[2]; // [esp+18h] [ebp-Ch] BYREF
  LRESULT v5; // [esp+20h] [ebp-4h]

  SendMessageA(dword_407138, 0x434u, 0, (LPARAM)lParam);
  v5 = SendMessageA(dword_407138, 0x436u, 0, lParam[0]);
  if ( lParam[0] )
    ++lParam[0];
  lParam[1] = -1;
  lParam[2] = a1;
  result = SendMessageA(dword_407138, 0x44Fu, 0, (LPARAM)lParam);
  if ( result != -1 )
  {
    v2 = SendMessageA(dword_407138, 0x436u, 0, result);
    SendMessageA(dword_407138, 0xB6u, 0, v2 - v5);
    return SendMessageA(dword_407138, 0x437u, 0, (LPARAM)v4);
  }
  return result;
}
// 401B72: using guessed type LPARAM var_C[2];

//----- (00401C07) --------------------------------------------------------
LRESULT sub_401C07()
{
  LPARAM lParam[2]; // [esp+0h] [ebp-8h] BYREF

  lParam[1] = 0;
  lParam[0] = 0;
  return SendMessageA(dword_407138, 0x437u, 0, (LPARAM)lParam);
}

//----- (00401C2C) --------------------------------------------------------
unsigned __int64 __cdecl sub_401C2C(__int64 a1)
{
  __int16 v1; // ax
  unsigned int *i; // ecx
  unsigned __int64 v3; // rax

  v1 = dword_407574;
  for ( i = (unsigned int *)lpBuffer; ; i += 8 )
  {
    if ( !v1 )
    {
      v3 = (unsigned int)dword_407A24;
      return a1 + v3;
    }
    --v1;
    if ( a1 >= i[4] && a1 < i[5] )
      break;
  }
  v3 = i[7] - (unsigned __int64)i[4];
  return a1 + v3;
}
// 401C5F: conditional instruction was optimized away because %arg_0@4.4>=0
// 407574: using guessed type int dword_407574;
// 407A24: using guessed type int dword_407A24;

//----- (00401C8E) --------------------------------------------------------
void sub_401C8E()
{
  LOWORD(dword_407574) = 0;
  dword_407A24 = 0;
  if ( lpBuffer )
  {
    free((void *)lpBuffer);
    lpBuffer = 0;
  }
}
// 407574: using guessed type int dword_407574;
// 407A24: using guessed type int dword_407A24;

//----- (00401CB6) --------------------------------------------------------
_BYTE *__cdecl sub_401CB6(_BYTE *a1, int a2, _WORD *a3)
{
  _BYTE *result; // eax
  __int16 v5; // si
  int v6; // edx

  result = a3;
  v5 = *a3;
  while ( 1 )
  {
    result += 2;
    if ( !v5 )
      break;
    v6 = a2;
    --v5;
    --a2;
    if ( !v6 )
      break;
    *a1++ = *result;
  }
  *a1 = 0;
  return result;
}

//----- (00401CE9) --------------------------------------------------------
HFONT sub_401CE9()
{
  LOGFONTA lf; // [esp+8h] [ebp-3Ch] BYREF

  memset(&lf.lfWidth, 0, 12);
  lf.lfItalic = 0;
  lf.lfUnderline = 0;
  lf.lfStrikeOut = 0;
  lf.lfCharSet = 0;
  lf.lfHeight = -11;
  lf.lfWeight = 700;
  lf.lfOutPrecision = 3;
  lf.lfClipPrecision = 2;
  lf.lfQuality = 1;
  strcpy((char *)&lf.lfPitchAndFamily, "\"Microsoft Sans Serif");
  memset(&lf.lfFaceName[21], 0, 11);
  return CreateFontIndirectA(&lf);
}

//----- (00401D4A) --------------------------------------------------------
_DWORD *__thiscall sub_401D4A(_DWORD *this, int a2, unsigned int a3)
{
  void *v4; // edi

  *this = off_406040;
  this[1] = 0;
  this[2] = 0;
  this[3] = 0;
  if ( a2 )
  {
    this[2] = a2;
    this[1] = operator new(8 * a2);
  }
  if ( a3 && a3 <= this[2] )
  {
    v4 = (void *)this[1];
    this[3] = a3;
    memset(v4, 0, 8 * a3);
  }
  return this;
}
// 406040: using guessed type int (__thiscall *off_406040[2])(void *, char);

//----- (00401D98) --------------------------------------------------------
int __thiscall sub_401D98(int this, int a2, int a3)
{
  unsigned int v4; // eax
  int v5; // eax
  void *v6; // edi
  int v7; // eax
  int v8; // ecx
  int result; // eax

  v4 = *(_DWORD *)(this + 8);
  if ( v4 )
  {
    if ( *(_DWORD *)(this + 12) + 1 > v4 )
    {
      v5 = (v4 >> 4) + v4 + 16;
      *(_DWORD *)(this + 8) = v5;
      v6 = operator new(8 * v5);
      memmove(v6, *(const void **)(this + 4), 8 * *(_DWORD *)(this + 12));
      operator delete(*(void **)(this + 4));
      *(_DWORD *)(this + 4) = v6;
    }
  }
  else
  {
    *(_DWORD *)(this + 8) = 32;
    *(_DWORD *)(this + 4) = operator new(0x100u);
  }
  v7 = *(_DWORD *)(this + 12);
  v8 = *(_DWORD *)(this + 4);
  *(_DWORD *)(v8 + 8 * v7) = a2;
  *(_DWORD *)(v8 + 8 * v7 + 4) = a3;
  result = *(_DWORD *)(this + 12);
  *(_DWORD *)(this + 12) = result + 1;
  return result;
}

//----- (00401E1B) --------------------------------------------------------
void *__thiscall sub_401E1B(_DWORD *this, unsigned int a2)
{
  if ( a2 >= this[3] )
    return &unk_407CE8;
  else
    return (void *)(this[1] + 8 * a2);
}

//----- (00401E34) --------------------------------------------------------
_DWORD *__thiscall sub_401E34(_DWORD *this, int a2, unsigned int a3)
{
  void *v4; // edi

  *this = &off_406044;
  this[1] = 0;
  this[2] = 0;
  this[3] = 0;
  if ( a2 )
  {
    this[2] = a2;
    this[1] = operator new(4 * a2);
  }
  if ( a3 && a3 <= this[2] )
  {
    v4 = (void *)this[1];
    this[3] = a3;
    memset(v4, 0, 4 * a3);
  }
  return this;
}
// 406044: using guessed type int (__thiscall *off_406044)(void *, char);

//----- (00401E7F) --------------------------------------------------------
int __thiscall sub_401E7F(int this, int a2)
{
  unsigned int v3; // eax
  int v4; // eax
  void *v5; // edi
  int result; // eax

  v3 = *(_DWORD *)(this + 8);
  if ( v3 )
  {
    if ( *(_DWORD *)(this + 12) + 1 > v3 )
    {
      v4 = (v3 >> 4) + v3 + 16;
      *(_DWORD *)(this + 8) = v4;
      v5 = operator new(4 * v4);
      memmove(v5, *(const void **)(this + 4), 4 * *(_DWORD *)(this + 12));
      operator delete(*(void **)(this + 4));
      *(_DWORD *)(this + 4) = v5;
    }
  }
  else
  {
    *(_DWORD *)(this + 8) = 32;
    *(_DWORD *)(this + 4) = operator new(0x80u);
  }
  *(_DWORD *)(*(_DWORD *)(this + 4) + 4 * *(_DWORD *)(this + 12)) = a2;
  result = *(_DWORD *)(this + 12);
  *(_DWORD *)(this + 12) = result + 1;
  return result;
}

//----- (00401EFA) --------------------------------------------------------
void *__thiscall sub_401EFA(_DWORD *this, unsigned int a2)
{
  if ( a2 >= this[3] )
    return &unk_407CF0;
  else
    return (void *)(this[1] + 4 * a2);
}

//----- (00401F13) --------------------------------------------------------
void __thiscall sub_401F13(_DWORD *this)
{
  void *v2; // eax

  v2 = (void *)this[1];
  this[3] = 0;
  this[2] = 0;
  if ( v2 )
  {
    operator delete(v2);
    this[1] = 0;
  }
}

//----- (00401F32) --------------------------------------------------------
int sub_401F32()
{
  INITCOMMONCONTROLSEX picce; // [esp+0h] [ebp-8h] BYREF

  picce.dwSize = 8;
  picce.dwICC = 9;
  InitCommonControlsEx(&picce);
  hLibModule = LoadLibraryA("RICHED32");
  wParam = sub_401CE9();
  dword_40713C = CreateSolidBrush(0x800000u);
  hMenu = LoadMenuA(hInstance, (LPCSTR)0x87);
  return sub_40155C((HGDIOBJ)0x6F, &hdc, (HPALETTE *)&hPal, &wSrc, &hSrc);
}

//----- (00401FAF) --------------------------------------------------------
BOOL sub_401FAF()
{
  BOOL result; // eax
  MSG Msg; // [esp+8h] [ebp-1Ch] BYREF

  while ( 1 )
  {
    result = GetMessageA(&Msg, 0, 0, 0);
    if ( result <= 0 )
      break;
    if ( sub_40107F(&Msg) )
    {
      TranslateMessage(&Msg);
      DispatchMessageA(&Msg);
    }
  }
  return result;
}

//----- (00401FF4) --------------------------------------------------------
unsigned __int8 __cdecl sub_401FF4(int a1, char a2)
{
  return sub_40112C((unsigned __int8 *)dword_406020[a1], a2);
}
// 406020: using guessed type int dword_406020[];

//----- (0040200B) --------------------------------------------------------
void sub_40200B()
{
  void *v0; // eax

  sub_401F13(dword_407CAC);
  sub_401F13(dword_407C9C);
  v0 = (void *)dword_407CBC[1];
  if ( v0 )
  {
    operator delete(v0);
    dword_407CBC[1] = 0;
  }
  if ( dword_407CBC[2] )
  {
    operator delete((void *)dword_407CBC[2]);
    dword_407CBC[2] = 0;
  }
  dword_407CBC[5] = 0;
  dword_407CBC[6] = 0;
  dword_407CBC[7] = 0;
  dword_407CBC[8] = 0;
  dword_407CBC[9] = 0;
}
// 407C9C: using guessed type _DWORD dword_407C9C[4];
// 407CAC: using guessed type _DWORD dword_407CAC[4];
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (00402029) --------------------------------------------------------
INT_PTR __stdcall DialogFunc(HWND hWnd, UINT a2, WPARAM a3, _DWORD *a4)
{
  int v5; // eax

  if ( a2 == 43 )
  {
    if ( a3 == 1006 )
      sub_4014B0(hWnd, a4);
  }
  else
  {
    if ( a2 != 78 || a4[2] != -551 )
      return 0;
    v5 = SendMessageA(dword_407578, 0x130Bu, 0, 0);
    sub_4012D2(v5, 0);
  }
  return 1;
}

//----- (00402129) --------------------------------------------------------
BOOL __cdecl sub_402129(HWND hDlg, LPCSTR lpString)
{
  sub_401290(&FileName, lpString, 260);
  SetDlgItemTextA(hDlg, 1000, &FileName);
  SetWindowTextA(hWndParent, lpString);
  SetForegroundWindow(hDlg);
  sub_4012D2(0, 1);
  return PostMessageA(hDlg, 0x111u, 0x3EAu, 0);
}

//----- (0040218D) --------------------------------------------------------
const CHAR *__cdecl sub_40218D(LPSTR a1, int *a2, int a3, int a4)
{
  int *v4; // eax
  int v5; // ecx
  const CHAR *v6; // ebx
  LPSTR v7; // esi
  signed __int64 v8; // rax
  LPSTR v9; // esi
  __int64 v10; // rax
  __int64 *v11; // eax
  unsigned __int16 *v12; // eax
  int v13; // eax

  if ( a4 )
  {
    if ( a4 != 1 )
    {
      if ( a4 == 2 )
      {
        v12 = (unsigned __int16 *)sub_401EFA(dword_407C9C, a3);
        v6 = a1;
        wsprintfA(a1, "%d", *v12);
      }
      else if ( a4 == 3 && (v13 = sub_40414E(dword_407CBC, a3)) != 0 )
      {
        v6 = (const CHAR *)v13;
      }
      else
      {
        v6 = a1;
        *a1 = 0;
      }
      goto LABEL_12;
    }
    v11 = (__int64 *)sub_401E1B(dword_407CAC, a3);
    v8 = sub_401C2C(*v11);
    v6 = a1;
    a1[12] = 0;
    v7 = a1 + 11;
    a1[11] = a0123456789abcd[v8 & 0xF];
  }
  else
  {
    v4 = (int *)sub_401E1B(dword_407CAC, a3);
    v5 = *v4;
    HIDWORD(v8) = v4[1];
    v6 = a1;
    a1[12] = 0;
    v7 = a1 + 11;
    a1[11] = a0123456789abcd[v5 & 0xF];
    LODWORD(v8) = v5;
  }
  v9 = v7 - 1;
  v10 = v8 >> 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9-- = a0123456789abcd[v10 & 0xF];
  v10 >>= 4;
  *v9 = a0123456789abcd[v10 & 0xF];
  *(v9 - 1) = a0123456789abcd[(v10 >> 4) & 0xF];
LABEL_12:
  if ( a2 )
    *a2 = lstrlenA(v6);
  return v6;
}
// 407C9C: using guessed type _DWORD dword_407C9C[4];
// 407CAC: using guessed type _DWORD dword_407CAC[4];
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (00402347) --------------------------------------------------------
void sub_402347()
{
  unsigned int v0; // edi
  char *v1; // eax
  LRESULT v2; // eax
  int v3; // eax
  const char *v4; // ebx
  const char *v5; // eax
  int v6; // eax
  HGLOBAL v7; // ebx
  LPVOID v8; // eax
  char v9; // [esp+Ch] [ebp-8ACh] BYREF
  CHAR v10[1028]; // [esp+440h] [ebp-478h] BYREF
  CHAR v11[16]; // [esp+844h] [ebp-74h] BYREF
  CHAR v12[16]; // [esp+854h] [ebp-64h] BYREF
  CHAR v13[16]; // [esp+864h] [ebp-54h] BYREF
  LPARAM lParam[3]; // [esp+874h] [ebp-44h] BYREF
  char v15; // [esp+880h] [ebp-38h]
  int v16; // [esp+884h] [ebp-34h]
  int v17; // [esp+894h] [ebp-24h]
  const char *v18; // [esp+89Ch] [ebp-1Ch]
  const char *v19; // [esp+8A0h] [ebp-18h]
  void *Block; // [esp+8A4h] [ebp-14h]
  LRESULT v21; // [esp+8A8h] [ebp-10h]
  int v22; // [esp+8ACh] [ebp-Ch]
  int i; // [esp+8B0h] [ebp-8h]
  LPSTR v24; // [esp+8B4h] [ebp-4h]

  v0 = 0;
  for ( i = 0; i < 2; ++i )
  {
    if ( i )
    {
      if ( !v0 )
        return;
      v1 = (char *)calloc(v0 + 1, 1u);
      Block = v1;
    }
    else
    {
      v1 = &v9;
    }
    v24 = v1;
    v2 = SendMessageA(hWnd, 0x1004u, 0, 0);
    v0 = 0;
    v22 = 0;
    if ( v2 )
    {
      v21 = v2;
      do
      {
        v3 = v22++;
        lParam[1] = v3;
        lParam[0] = 12;
        v16 = 2;
        SendMessageA(hWnd, 0x1005u, 0, (LPARAM)lParam);
        if ( (v15 & 2) != 0 )
        {
          v4 = sub_40218D(v11, 0, v17, 0);
          v19 = sub_40218D(v12, 0, v17, 1);
          v18 = sub_40218D(v13, 0, v17, 2);
          v5 = sub_40218D(v10, 0, v17, 3);
          wsprintfA(v24, "%s   %s  %5s   %s\r\n", v4, v19, v18, v5);
          v6 = lstrlenA(v24);
          v0 += v6;
          if ( i )
            v24 += v6;
        }
        --v21;
      }
      while ( v21 );
    }
  }
  if ( v0 )
  {
    OpenClipboard(hWndParent);
    EmptyClipboard();
    v7 = GlobalAlloc(0x42u, v0 + 1);
    v8 = GlobalLock(v7);
    qmemcpy(v8, Block, v0);
    GlobalUnlock(v7);
    SetClipboardData(1u, v7);
    CloseClipboard();
    free(Block);
  }
}
// 402347: using guessed type CHAR var_74[16];
// 402347: using guessed type CHAR var_64[16];
// 402347: using guessed type CHAR var_54[16];
// 402347: using guessed type CHAR var_478[1028];

//----- (004024C7) --------------------------------------------------------
_BYTE *__cdecl sub_4024C7(int a1, _BYTE *a2, int a3, int a4, int a5, int a6)
{
  char v7[76]; // [esp+0h] [ebp-4Ch] BYREF

  sub_4017FC((int)v7, a1, a2, a3, a4, a5, a6);
  return GetOpenFileNameA((LPOPENFILENAMEA)v7) ? a2 : 0;
}

//----- (004024FE) --------------------------------------------------------
_BYTE *__cdecl sub_4024FE(int a1, _BYTE *a2, int a3, int a4, int a5, int a6)
{
  char v7[76]; // [esp+0h] [ebp-4Ch] BYREF

  sub_4017FC((int)v7, a1, a2, a3, a4, a5, a6);
  return GetSaveFileNameA((LPOPENFILENAMEA)v7) ? a2 : 0;
}

//----- (00402535) --------------------------------------------------------
LRESULT __cdecl sub_402535(int a1, int a2, unsigned __int16 a3, LPCSTR lpString, int a5)
{
  int v5; // esi
  LRESULT result; // eax
  LPARAM lParam[10]; // [esp+8h] [ebp-28h] BYREF

  v5 = sub_401D98((int)dword_407CAC, a1, a2);
  sub_401E7F((int)dword_407C9C, a3 | ((unsigned __int16)a5 << 16));
  sub_403FB3((int)dword_407CBC, lpString);
  result = 0;
  if ( dword_407C94 )
  {
    lParam[5] = -1;
    lParam[0] = 7;
    lParam[1] = v5;
    lParam[7] = a5;
    lParam[8] = v5;
    lParam[2] = 0;
    return SendMessageA(hWnd, 0x1007u, 0, (LPARAM)lParam);
  }
  return result;
}
// 407C94: using guessed type int dword_407C94;
// 407C9C: using guessed type _DWORD dword_407C9C[4];
// 407CAC: using guessed type _DWORD dword_407CAC[4];
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (004025B1) --------------------------------------------------------
BOOL sub_4025B1()
{
  CHAR *v0; // esi
  UINT v1; // edi
  unsigned __int8 v2; // al
  char v3; // cl
  bool v4; // zf
  __int64 v6; // [esp+Ch] [ebp-20h]
  __int64 v7; // [esp+14h] [ebp-18h]
  unsigned __int8 *v8; // [esp+1Ch] [ebp-10h]
  DWORD NumberOfBytesRead; // [esp+20h] [ebp-Ch] BYREF
  unsigned int v10; // [esp+24h] [ebp-8h]
  unsigned __int8 v11; // [esp+2Bh] [ebp-1h]

  v0 = (CHAR *)lpString;
  v7 = 0i64;
  v6 = 0i64;
  NumberOfBytesRead = 0;
  v10 = 1;
  v11 = 0;
  v1 = 0;
  SetFilePointer(hFile, 0, 0, 0);
  dword_407C70 = 0;
  sub_4018DF(1008, "AN: %u", 0);
  do
  {
    v8 = (unsigned __int8 *)Block;
    if ( NumberOfBytesRead )
    {
      while ( 1 )
      {
        v2 = *v8++;
        v3 = v11;
        ++v7;
        v4 = byte_407B70[v2] == 0;
        v11 = v2;
        if ( v4 )
          break;
        ++v1;
        if ( v2 == v3 )
          ++v10;
        else
          v10 = 1;
        if ( v1 >= dword_407B48 || v10 >= dword_407150 )
          goto LABEL_15;
        *v0++ = v2;
LABEL_16:
        if ( !--NumberOfBytesRead )
          goto LABEL_17;
      }
      *v0 = 0;
      if ( v1 >= uValue && v1 <= dword_407B48 && v10 < dword_407150 && sub_401474() )
      {
        dword_407B68 += v1;
        ++dword_407C70;
        sub_402535(v6, SHIDWORD(v6), 0, lpString, 0);
      }
LABEL_15:
      v0 = (CHAR *)lpString;
      v6 = v7;
      v1 = 0;
      v10 = 1;
      goto LABEL_16;
    }
LABEL_17:
    ReadFile(hFile, Block, 0x4000u, &NumberOfBytesRead, 0);
  }
  while ( NumberOfBytesRead && sub_4010CC() );
  if ( v1 >= uValue && v1 <= dword_407B48 && v10 < dword_407150 && sub_401474() )
  {
    *v0 = 0;
    dword_407B68 += v1;
    ++dword_407C70;
    sub_402535(v6, SHIDWORD(v6), 0, lpString, 0);
  }
  return sub_4018DF(1008, "AN: %u", dword_407C70);
}
// 407150: using guessed type int dword_407150;
// 407B68: using guessed type int dword_407B68;

//----- (0040275E) --------------------------------------------------------
BOOL sub_40275E()
{
  CHAR *v0; // esi
  UINT v1; // edi
  char v2; // al
  unsigned __int8 v3; // cl
  __int64 v5; // [esp+Ch] [ebp-20h]
  __int64 v6; // [esp+14h] [ebp-18h]
  char *i; // [esp+1Ch] [ebp-10h]
  DWORD NumberOfBytesRead; // [esp+20h] [ebp-Ch] BYREF
  unsigned int v9; // [esp+24h] [ebp-8h]
  unsigned __int8 v10; // [esp+2Bh] [ebp-1h]

  v0 = (CHAR *)lpString;
  v6 = 0i64;
  v5 = 0i64;
  NumberOfBytesRead = 0;
  v9 = 1;
  v10 = 0;
  v1 = 0;
  SetFilePointer(hFile, 0, 0, 0);
  dword_407570 = 0;
  sub_4018DF(1009, "UN: %u", 0);
  do
  {
    for ( i = (char *)Block; NumberOfBytesRead; --NumberOfBytesRead )
    {
      v2 = *i;
      v3 = v10;
      ++i;
      v10 = v2;
      ++v6;
      if ( v2 )
      {
        if ( v3 )
          goto LABEL_19;
      }
      else
      {
        if ( !byte_407B70[v3] )
        {
          if ( !v3 )
          {
            *v0 = 0;
            if ( v1 >= uValue && v1 <= dword_407B48 && v9 < dword_407150 && sub_401474() )
            {
              dword_407B68 += v1;
              ++dword_407570;
              sub_402535(v5, SHIDWORD(v5), 0, lpString, 1);
            }
LABEL_17:
            v9 = 1;
          }
LABEL_19:
          v0 = (CHAR *)lpString;
          v5 = v6;
          v1 = 0;
          continue;
        }
        ++v1;
        if ( v3 )
          v9 = 1;
        else
          ++v9;
        if ( v1 >= dword_407B48 || v9 >= dword_407150 )
          goto LABEL_17;
        *v0++ = v3;
      }
    }
    ReadFile(hFile, Block, 0x4000u, &NumberOfBytesRead, 0);
  }
  while ( NumberOfBytesRead && sub_4010CC() );
  if ( v1 >= uValue && v9 < dword_407150 )
  {
    *v0 = 0;
    if ( sub_401401() )
    {
      dword_407B68 += v1;
      ++dword_407570;
      sub_402535(v5, SHIDWORD(v5), 0, lpString, 1);
    }
  }
  return sub_4018DF(1009, "UN: %u", dword_407570);
}
// 407150: using guessed type int dword_407150;
// 407B68: using guessed type int dword_407B68;

//----- (00402915) --------------------------------------------------------
int sub_402915()
{
  int result; // eax
  unsigned int v1; // esi
  int v2; // edi
  unsigned int v3; // eax
  LPARAM lParam[10]; // [esp+4h] [ebp-28h] BYREF

  result = sub_40414A(dword_407CBC);
  v1 = 0;
  if ( result )
  {
    v2 = result;
    do
    {
      v3 = *(_DWORD *)sub_401EFA(dword_407C9C, v1);
      lParam[2] = 0;
      lParam[5] = -1;
      lParam[7] = HIWORD(v3);
      lParam[0] = 7;
      lParam[1] = v1;
      lParam[8] = v1;
      result = SendMessageA(hWnd, 0x1007u, 0, (LPARAM)lParam);
      ++v1;
      --v2;
    }
    while ( v2 );
  }
  return result;
}
// 407C9C: using guessed type _DWORD dword_407C9C[4];
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (00402976) --------------------------------------------------------
BOOL __cdecl sub_402976(int a1, int a2, _WORD *a3, int a4, int a5, __int16 a6)
{
  unsigned __int16 v6; // ax
  unsigned __int16 *v7; // ebx
  int v8; // eax
  int *v9; // eax
  int v10; // ecx
  int v11; // eax
  int v12; // esi
  int v13; // ecx
  _BYTE *v15; // [esp+4h] [ebp-Ch]
  int v16; // [esp+8h] [ebp-8h]
  _WORD *v17; // [esp+Ch] [ebp-4h]
  int v18; // [esp+20h] [ebp+10h]

  v6 = a3[6] + a3[7];
  v7 = a3 + 8;
  if ( v6 )
  {
    v16 = v6;
    do
    {
      v8 = *((_DWORD *)v7 + 1);
      if ( v8 >= 0 )
      {
        v9 = (int *)(a2 + v8);
        if ( (_WORD)a5 == 6 )
        {
          v10 = *(_DWORD *)(a1 + 24);
          v11 = *v9;
          v12 = v11 + *(_DWORD *)(a1 + 16) - v10;
          v18 = 0;
          v17 = (_WORD *)(a2 + v11 - v10);
          do
          {
            v15 = sub_401CB6(lpString, dword_407B48, v17);
            if ( sub_401401() )
            {
              ++dword_407C8C;
              sub_402535(v12, 0, v18 + 16 * (a6 - 1), lpString, 2);
            }
            v13 = v15 - (_BYTE *)v17;
            v17 = v15;
            v12 += v13;
            ++v18;
          }
          while ( v18 < 16 );
        }
      }
      else
      {
        if ( !a4 )
        {
          if ( (*(_DWORD *)v7 & 0x80000000) != 0 )
          {
            sub_401CB6(lpString, dword_407B48, (_WORD *)((*(_DWORD *)v7 & 0x7FFFFFFF) + a2 + 2));
            if ( sub_401401() )
            {
              ++dword_407C8C;
              sub_402535(*(_DWORD *)(a1 + 16) + (*(_DWORD *)v7 & 0x7FFFFFFF) + 2, 0, *v7, lpString, 2);
            }
          }
          LOWORD(a5) = *v7;
        }
        sub_402976(a1, a2, a2 + (*((_DWORD *)v7 + 1) & 0x7FFFFFFF), a4 + 1, a5, *v7);
      }
      v7 += 4;
      --v16;
    }
    while ( v16 );
  }
  return sub_4018DF(1013, "RS: %u", dword_407C8C);
}

//----- (00402AF0) --------------------------------------------------------
int __cdecl sub_402AF0(LPCSTR lpFileName)
{
  hFile = CreateFileA(lpFileName, 0x80000000, 1u, 0, 3u, 0x80u, 0);
  if ( hFile != (HANDLE)-1 )
    return 1;
  sub_401916();
  MessageBoxA(hWndParent, "Unable to open that file", "BinText 3.0.3", 0x10u);
  return 0;
}

//----- (00402B3A) --------------------------------------------------------
BOOL __cdecl sub_402B3A(int a1, int a2)
{
  int v2; // ebx
  int v3; // esi
  int v4; // edi
  HWND *v5; // esi
  BOOL result; // eax
  struct tagRECT v7; // [esp+0h] [ebp-34h] BYREF
  struct tagRECT v8; // [esp+10h] [ebp-24h] BYREF
  struct tagRECT Rect; // [esp+20h] [ebp-14h] BYREF
  int v10; // [esp+30h] [ebp-4h]

  if ( dword_407B40 )
  {
    GetClientRect(hWndParent, &Rect);
    GetClientRect(dword_407578, &v8);
    v2 = v8.right - v8.left;
    v10 = v8.bottom - v8.top;
    GetClientRect(hDlg, &v7);
    v3 = a1 + v7.right - v7.left;
    v4 = a2 + v7.bottom - v7.top;
    SetWindowPos(dword_407578, 0, 0, 0, a1 + v2, a2 + v10, 2u);
    SetWindowPos(hDlg, 0, 0, 0, v3, v4, 2u);
    sub_401A85(hDlg, dword_405BE0, a1, a2, 1);
    v5 = &dword_4070CC;
    do
    {
      sub_401A85(*v5, (int *)v5[4], a1, a2, 1);
      GetWindowRect(*v5, &Rect);
      Rect.bottom += a2;
      Rect.right += a1;
      result = SetWindowPos(*v5, 0, 0, 0, Rect.right - Rect.left, Rect.bottom - Rect.top, 2u);
      v5 += 5;
    }
    while ( (int)v5 < (int)off_407108 );
  }
  return result;
}
// 405BE0: using guessed type int dword_405BE0[6];
// 407108: using guessed type char *off_407108[4];
// 407B40: using guessed type int dword_407B40;

//----- (00402C42) --------------------------------------------------------
int __cdecl sub_402C42(HWND hWnd, LPCSTR lpFileName)
{
  LRESULT v3; // eax
  int v4; // eax
  const char *v5; // eax
  const char *v6; // eax
  int v7; // eax
  CHAR v8[1028]; // [esp+4h] [ebp-8B0h] BYREF
  CHAR String[1076]; // [esp+408h] [ebp-4ACh] BYREF
  CHAR v10[16]; // [esp+83Ch] [ebp-78h] BYREF
  CHAR v11[16]; // [esp+84Ch] [ebp-68h] BYREF
  CHAR v12[16]; // [esp+85Ch] [ebp-58h] BYREF
  LPARAM lParam[8]; // [esp+86Ch] [ebp-48h] BYREF
  int v14; // [esp+88Ch] [ebp-28h]
  const char *v15; // [esp+894h] [ebp-20h]
  DWORD NumberOfBytesWritten; // [esp+898h] [ebp-1Ch] BYREF
  const char *v17; // [esp+89Ch] [ebp-18h]
  const char *v18; // [esp+8A0h] [ebp-14h]
  LRESULT v19; // [esp+8A4h] [ebp-10h]
  HANDLE hFile; // [esp+8A8h] [ebp-Ch]
  int v21; // [esp+8ACh] [ebp-8h]
  int v22; // [esp+8B0h] [ebp-4h]

  hFile = CreateFileA(lpFileName, 0x40000000u, 2u, 0, 2u, 0x80u, 0);
  if ( hFile == (HANDLE)-1 )
  {
    CloseHandle((HANDLE)0xFFFFFFFF);
    MessageBoxA(hWnd, "Unable to open that file", "BinText 3.0.3", 0x10u);
    return 0;
  }
  else
  {
    v3 = SendMessageA(::hWnd, 0x1004u, 0, 0);
    v21 = 0;
    v22 = 60;
    if ( v3 )
    {
      v19 = v3;
      do
      {
        if ( dword_407C94 )
        {
          if ( ++v22 >= 60 )
          {
            WriteFile(
              hFile,
              "\r\nFile pos       Mem pos          ID   Text\r\n========       =======          ==   ====\r\n\r\n",
              0x5Au,
              &NumberOfBytesWritten,
              0);
            v22 = 0;
          }
        }
        v4 = v21++;
        lParam[1] = v4;
        lParam[0] = 4;
        SendMessageA(::hWnd, 0x1005u, 0, (LPARAM)lParam);
        v5 = sub_40218D(v8, 0, v14, 3);
        v17 = v5;
        if ( dword_407C94 )
        {
          v18 = sub_40218D(v11, 0, v14, 0);
          v15 = sub_40218D(v12, 0, v14, 1);
          v6 = sub_40218D(v10, 0, v14, 2);
          wsprintfA(String, "%s   %s  %5s   %s\r\n", v18, v15, v6, v17);
        }
        else
        {
          wsprintfA(String, "%s\n", v5);
        }
        v7 = lstrlenA(String);
        WriteFile(hFile, String, v7, &NumberOfBytesWritten, 0);
        --v19;
      }
      while ( v19 );
    }
    CloseHandle(hFile);
    return 1;
  }
}
// 407C94: using guessed type int dword_407C94;
// 402C42: using guessed type CHAR var_8B0[1028];
// 402C42: using guessed type CHAR var_68[16];
// 402C42: using guessed type CHAR var_58[16];
// 402C42: using guessed type CHAR var_78[16];

//----- (00402DCD) --------------------------------------------------------
BOOL __cdecl sub_402DCD(char *SubStr)
{
  LRESULT v1; // eax
  int v2; // edi
  const CHAR *v3; // eax
  LRESULT v4; // eax
  CHAR String1[1024]; // [esp+Ch] [ebp-434h] BYREF
  LPARAM lParam; // [esp+40Ch] [ebp-34h] BYREF
  int v8; // [esp+410h] [ebp-30h]
  int v9; // [esp+414h] [ebp-2Ch]
  int v10; // [esp+418h] [ebp-28h]
  int v11; // [esp+41Ch] [ebp-24h]
  int v12; // [esp+42Ch] [ebp-14h]
  int v13; // [esp+434h] [ebp-Ch]
  LRESULT v14; // [esp+438h] [ebp-8h]
  int v15; // [esp+43Ch] [ebp-4h] BYREF

  v1 = SendMessageA(hWnd, 0x1004u, 0, 0);
  v2 = 0;
  v13 = 1;
  if ( v1 )
  {
    v14 = v1;
    do
    {
      lParam = 4;
      v8 = v2;
      SendMessageA(hWnd, 0x1005u, 0, (LPARAM)&lParam);
      v3 = sub_40218D(0, &v15, v12, 3);
      lstrcpynA(String1, v3, 1024);
      strlwr(String1);
      if ( strstr(String1, SubStr) )
      {
        v11 = 2;
        v10 = 2;
        lParam = 8;
        v8 = v2;
        v9 = 0;
        SendMessageA(hWnd, 0x1006u, 0, (LPARAM)&lParam);
        if ( v13 )
        {
          v15 = SendMessageA(hWnd, 0x1027u, 0, 0);
          if ( v2 < v15 || (v4 = SendMessageA(hWnd, 0x1028u, 0, 0), v2 >= v15 + v4) )
          {
            if ( v2 > v15 )
            {
              v13 = 0;
              SendMessageA(hWnd, 0x1013u, v2, 0);
            }
          }
        }
      }
      ++v2;
      --v14;
    }
    while ( v14 );
  }
  return UpdateWindow(hWnd);
}

//----- (00402EF4) --------------------------------------------------------
void sub_402EF4()
{
  _DWORD *v0; // esi
  LONG v1; // edi
  _DWORD *v2; // esi
  unsigned __int16 v3; // di
  int v4; // ebx
  CHAR *v5; // esi
  bool i; // zf
  _DWORD *v7; // edi
  _BYTE *v8; // eax
  int v9; // eax
  void *v10; // [esp-4h] [ebp-1Ch]
  DWORD NumberOfBytesRead; // [esp+10h] [ebp-8h] BYREF
  LONG v12; // [esp+14h] [ebp-4h]

  sub_401C8E();
  SetFilePointer(hFile, 0, 0, 0);
  v0 = malloc(0x40u);
  ReadFile(hFile, v0, 0x40u, &NumberOfBytesRead, 0);
  v10 = v0;
  if ( *(_WORD *)v0 == 23117
    && (v12 = v0[15],
        v1 = v12,
        free(v0),
        SetFilePointer(hFile, v1, 0, 0),
        v2 = malloc(0xF8u),
        ReadFile(hFile, v2, 0xF8u, &NumberOfBytesRead, 0),
        v10 = v2,
        *v2 == 17744) )
  {
    v3 = *((_WORD *)v2 + 3);
    dword_407A24 = v2[13];
    free(v2);
    SetFilePointer(hFile, v12 + 248, 0, 0);
    v4 = v3;
    LOWORD(dword_407574) = v3;
    lpBuffer = (LPCSTR)malloc(32 * v3);
    v5 = (CHAR *)lpBuffer;
    for ( i = v3 == 0; !i; i = v4 == 0 )
    {
      v7 = malloc(0x28u);
      ReadFile(hFile, v7, 0x28u, &NumberOfBytesRead, 0);
      *(_DWORD *)v5 = *v7;
      *((_DWORD *)v5 + 1) = v7[1];
      v8 = v5 + 8;
      do
      {
        do
          *v8-- = 0;
        while ( *v8 == 32 );
      }
      while ( !*v8 );
      v9 = v7[5];
      *((_DWORD *)v5 + 4) = v9;
      *((_DWORD *)v5 + 5) = v9 + v7[4];
      *((_DWORD *)v5 + 6) = v7[3];
      *((_DWORD *)v5 + 7) = dword_407A24 + v7[3];
      v5 += 32;
      free(v7);
      --v4;
    }
  }
  else
  {
    free(v10);
  }
}
// 407574: using guessed type int dword_407574;
// 407A24: using guessed type int dword_407A24;

//----- (00403041) --------------------------------------------------------
void __thiscall sub_403041(_DWORD *this)
{
  *this = off_406040;
  sub_401F13(this);
}
// 406040: using guessed type int (__thiscall *off_406040[2])(void *, char);

//----- (0040304C) --------------------------------------------------------
void __thiscall sub_40304C(_DWORD *this)
{
  *this = &off_406044;
  sub_401F13(this);
}
// 406044: using guessed type int (__thiscall *off_406044)(void *, char);

//----- (00403057) --------------------------------------------------------
_DWORD *__thiscall sub_403057(_DWORD *this, char a2)
{
  sub_403041(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (00403073) --------------------------------------------------------
_DWORD *__thiscall sub_403073(_DWORD *this, char a2)
{
  sub_40304C(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (0040308F) --------------------------------------------------------
void __cdecl sub_40308F(LPCSTR lpString)
{
  if ( lpString )
  {
    if ( lstrlenA(lpString) )
      sub_402129(dword_4070CC, lpString);
  }
}

//----- (004030B3) --------------------------------------------------------
BOOL sub_4030B3()
{
  WPARAM v0; // ebx
  char **v1; // esi
  LPARAM v2; // eax
  unsigned __int16 *v3; // esi
  LPARAM lParam[7]; // [esp+Ch] [ebp-1Ch] BYREF

  v0 = 0;
  hDlg = CreateDialogParamA(hInstance, (LPCSTR)0x7F, hWndParent, (DLGPROC)DialogFunc, 0);
  dword_407578 = GetDlgItem(hDlg, 1016);
  v1 = &off_4070D4;
  do
  {
    v2 = (LPARAM)*v1;
    lParam[5] = -1;
    lParam[3] = v2;
    lParam[0] = 1;
    SendMessageA(dword_407578, 0x1307u, v0, (LPARAM)lParam);
    v1 += 5;
    ++v0;
  }
  while ( (int)v1 < (int)off_407110 );
  v3 = (unsigned __int16 *)&unk_4070D0;
  do
  {
    *((_DWORD *)v3 - 1) = CreateDialogParamA(hInstance, (LPCSTR)*v3, hDlg, *((DLGPROC *)v3 + 2), 0);
    v3 += 10;
  }
  while ( (int)v3 < (int)off_40710C );
  return sub_4011EC();
}
// 4070D4: using guessed type char *off_4070D4;
// 40710C: using guessed type char *off_40710C[3];
// 407110: using guessed type char *off_407110[2];

//----- (0040315B) --------------------------------------------------------
int __cdecl sub_40315B(int a1)
{
  int result; // eax
  int *v2; // esi
  int v3[36]; // [esp+4h] [ebp-1Ch] BYREF

  result = 0;
  memset(byte_407B70, 0, sizeof(byte_407B70));
  if ( !a1 )
  {
    v3[35] = 0;
    result = 1026;
    v3[0] = 1026;
    v3[1] = 1027;
    v3[2] = 1028;
    v3[3] = 1029;
    v3[4] = 1030;
    v3[5] = 1031;
    v3[6] = 1032;
    v3[7] = 1033;
    v3[8] = 1034;
    v3[9] = 1035;
    v3[10] = 1036;
    v3[11] = 1037;
    v3[12] = 1038;
    v3[13] = 1039;
    v3[14] = 1040;
    v3[15] = 1042;
    v3[16] = 1041;
    v3[17] = 1043;
    v3[18] = 1044;
    v3[19] = 1045;
    v3[20] = 1046;
    v3[21] = 1047;
    v3[22] = 1048;
    v3[23] = 1049;
    v3[24] = 1050;
    v3[25] = 1051;
    v3[26] = 1052;
    v3[27] = 1053;
    v3[28] = 1054;
    v3[29] = 1056;
    v3[30] = 1058;
    v3[31] = 1059;
    v3[32] = 1060;
    v3[33] = 1061;
    v3[34] = 1062;
    v2 = v3;
    do
    {
      sub_401FF4(result, 1);
      result = *++v2;
    }
    while ( *v2 );
  }
  return result;
}

//----- (00403294) --------------------------------------------------------
LRESULT __stdcall sub_403294(HWND hWnd, UINT Msg, HDROP wParam, LPARAM lParam)
{
  CHAR szFile[260]; // [esp+0h] [ebp-154h] BYREF
  struct tagPAINTSTRUCT Paint; // [esp+104h] [ebp-50h] BYREF
  struct tagRECT Rect; // [esp+144h] [ebp-10h] BYREF

  switch ( Msg )
  {
    case 1u:
      GetWindowRect(hWnd, &::Rect);
      GetWindowRect(hWnd, &rcDst);
      SetWindowTextA(hWnd, "BinText 3.0.3");
      DragAcceptFiles(hWnd, 1);
      break;
    case 5u:
      if ( wParam != (HDROP)1 )
      {
        GetWindowRect(hWnd, &Rect);
        sub_402B3A(Rect.right + rcDst.left - rcDst.right - Rect.left, Rect.bottom + rcDst.top - rcDst.bottom - Rect.top);
        CopyRect(&rcDst, &Rect);
      }
      break;
    case 0xFu:
      BeginPaint(hWnd, &Paint);
      sub_402B3A(0, 0);
      EndPaint(hWnd, &Paint);
      break;
    case 0x10u:
      ShowWindow(hWnd, 0);
      PostQuitMessage(0);
      break;
    case 0x24u:
      *(_DWORD *)(lParam + 24) = ::Rect.right - ::Rect.left;
      *(_DWORD *)(lParam + 28) = ::Rect.bottom - ::Rect.top;
      break;
    case 0x233u:
      if ( DragQueryFileA(wParam, 0, szFile, 0x104u) )
        sub_402129(dword_4070CC, szFile);
      break;
    default:
      return DefWindowProcA(hWnd, Msg, (WPARAM)wParam, lParam);
  }
  return 0;
}

//----- (004036C8) --------------------------------------------------------
int __stdcall sub_4036C8(int a1, int a2, int a3)
{
  int result; // eax

  sub_40218D(String1, 0, a1, a3);
  sub_40218D(String2, 0, a2, a3);
  result = stricmp(String1, String2);
  if ( dword_407564 < 0 )
    return -result;
  return result;
}
// 407564: using guessed type int dword_407564;

//----- (0040370F) --------------------------------------------------------
void __cdecl sub_40370F(_DWORD *lpBuffer)
{
  size_t v2; // esi
  int v3; // [esp+0h] [ebp-20h] BYREF
  DWORD NumberOfBytesRead; // [esp+Ch] [ebp-14h] BYREF
  int *v5; // [esp+10h] [ebp-10h]
  int v6; // [esp+1Ch] [ebp-4h]
  _WORD *lpBuffera; // [esp+28h] [ebp+8h]

  v2 = lpBuffer[5] - lpBuffer[4];
  v5 = &v3;
  lpBuffera = malloc(v2);
  v6 = 0;
  dword_407C8C = 0;
  sub_4018DF(1013, "RS: %u", 0);
  SetFilePointer(hFile, lpBuffer[4], 0, 0);
  ReadFile(hFile, lpBuffera, v2, &NumberOfBytesRead, 0);
  sub_402976((int)lpBuffer, (int)lpBuffera, lpBuffera, 0, 0, 0);
  free(lpBuffera);
}

//----- (004037C0) --------------------------------------------------------
int __cdecl sub_4037C0(CHAR *lpString)
{
  int result; // eax

  result = lstrlenA(lpString);
  if ( result )
  {
    SetDlgItemTextA(dword_4070CC, 1007, "Searching...");
    if ( dword_407C94 )
      sub_402DCD(lpString);
    else
      sub_401B72((LPARAM)lpString);
    return SetDlgItemTextA(dword_4070CC, 1007, "Ready");
  }
  return result;
}
// 407C94: using guessed type int dword_407C94;

//----- (00403814) --------------------------------------------------------
HWND sub_403814()
{
  int SystemMetrics; // eax
  HWND result; // eax
  int v2; // [esp-1Ch] [ebp-58h]
  HINSTANCE v3; // [esp-8h] [ebp-44h]
  WNDCLASSEXA v4; // [esp+Ch] [ebp-30h] BYREF

  v4.cbSize = 48;
  v4.style = 0;
  v4.lpfnWndProc = (WNDPROC)sub_403294;
  v4.cbClsExtra = 0;
  v4.cbWndExtra = 0;
  v4.hInstance = hInstance;
  v4.hIcon = LoadIconA(hInstance, (LPCSTR)0x68);
  v4.hCursor = LoadCursorA(0, (LPCSTR)0x7F00);
  v4.hbrBackground = (HBRUSH)GetStockObject(0);
  v4.lpszMenuName = 0;
  v4.lpszClassName = "BinText 3.0.3";
  v4.hIconSm = LoadIconA(hInstance, (LPCSTR)0x68);
  RegisterClassExA(&v4);
  v3 = hInstance;
  v2 = (GetSystemMetrics(1) - 402) / 2;
  SystemMetrics = GetSystemMetrics(0);
  result = CreateWindowExA(
             0,
             "BinText 3.0.3",
             "BinText 3.0.3",
             0x2CF0000u,
             (SystemMetrics - 587) / 2,
             v2,
             587,
             402,
             0,
             0,
             v3,
             0);
  FileName = 0;
  hWndParent = result;
  return result;
}

//----- (004038DB) --------------------------------------------------------
void sub_4038DB()
{
  int v0; // esi
  CHAR *v1; // edi

  dword_407C8C = 0;
  LOWORD(v0) = dword_407574;
  v1 = (CHAR *)lpBuffer;
  sub_4018DF(1013, "RS: %u", 0);
  if ( (_WORD)v0 )
  {
    v0 = (unsigned __int16)v0;
    do
    {
      if ( !lstrcmpA(v1, ".rsrc") )
        sub_40370F(v1);
      v1 += 32;
      --v0;
    }
    while ( v0 );
  }
}
// 407574: using guessed type int dword_407574;

//----- (0040392C) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  ::hInstance = hInstance;
  sub_401F32();
  sub_40315B(0);
  sub_403814();
  sub_4030B3();
  sub_401976();
  sub_401B33();
  sub_401196();
  sub_40308F(lpCmdLine);
  dword_407B40 = 1;
  ShowWindow(hWndParent, nShowCmd);
  UpdateWindow(hWndParent);
  sub_401FAF();
  sub_40200B();
  sub_401C8E();
  sub_401000();
  return 0;
}
// 401000: using guessed type int sub_401000(void);
// 401196: using guessed type int sub_401196(void);
// 401976: using guessed type int sub_401976(void);
// 401B33: using guessed type int sub_401B33(void);
// 401C8E: using guessed type int sub_401C8E(void);
// 401F32: using guessed type int sub_401F32(void);
// 401FAF: using guessed type int sub_401FAF(void);
// 40200B: using guessed type int sub_40200B(void);
// 4030B3: using guessed type int sub_4030B3(void);
// 40315B: using guessed type _DWORD __cdecl sub_40315B(_DWORD);
// 403814: using guessed type int sub_403814(void);
// 407B40: using guessed type int dword_407B40;

//----- (004039A4) --------------------------------------------------------
int __cdecl sub_4039A4(LPCSTR lpFileName)
{
  int result; // eax
  DWORD TickCount; // ebp
  HANDLE CurrentThread; // edi
  DWORD v4; // eax
  int nPriority; // [esp+18h] [ebp-104h]
  char Buffer[256]; // [esp+1Ch] [ebp-100h] BYREF

  result = sub_402AF0(lpFileName);
  if ( result )
  {
    sub_40200B();
    lpString = (LPCSTR)malloc(dword_407B48 + 2);
    Block = malloc(0x4000u);
    sub_402EF4();
    dword_407B68 = 0;
    dword_407A0C = 0;
    TickCount = GetTickCount();
    CurrentThread = GetCurrentThread();
    nPriority = GetThreadPriority(CurrentThread);
    SetThreadPriority(CurrentThread, 1);
    sub_4025B1();
    sub_40275E();
    sub_4038DB();
    SetThreadPriority(CurrentThread, nPriority);
    free(Block);
    free((void *)lpString);
    sub_401916();
    sub_402915();
    sub_401867();
    v4 = GetTickCount();
    sprintf(
      Buffer,
      "Time taken : %d.%03u secs    Text size: %u bytes (%.2fK)",
      (v4 - TickCount) / 0x3E8,
      (v4 - TickCount) % 0x3E8,
      dword_407B68,
      (double)(unsigned int)dword_407B68 * 0.0009765625);
    result = SetDlgItemTextA(dword_4070CC, 1093, Buffer);
  }
  if ( dword_407C94 )
  {
    result = SendMessageA(hWnd, 0x101Eu, 3u, 0xFFFF);
    dword_407B4C = 1;
  }
  else
  {
    dword_407140 = 1;
  }
  return result;
}
// 407140: using guessed type int dword_407140;
// 407A0C: using guessed type int dword_407A0C;
// 407B4C: using guessed type int dword_407B4C;
// 407B68: using guessed type int dword_407B68;
// 407C94: using guessed type int dword_407C94;

//----- (00403B01) --------------------------------------------------------
int __stdcall sub_403B01(HWND hDlg, int a2, unsigned __int16 a3, HWND hWnd)
{
  HWND DlgItem; // eax
  int v6; // eax
  HMENU SubMenu; // eax
  struct tagPOINT v8; // [esp-14h] [ebp-12Ch]
  int v9; // [esp-8h] [ebp-120h]
  int v10; // [esp-4h] [ebp-11Ch]
  CHAR FileName[4]; // [esp+Ch] [ebp-10Ch] BYREF
  CHAR String[256]; // [esp+10h] [ebp-108h] BYREF
  struct tagPOINT Point; // [esp+110h] [ebp-8h] BYREF

  if ( a2 == 78 )
  {
    v6 = *((_DWORD *)hWnd + 2);
    if ( v6 == -150 )
    {
      if ( ((_BYTE)hWnd[3] & 1) != 0 )
      {
        v10 = *((_DWORD *)hWnd + 5);
        v9 = *((unsigned __int16 *)hWnd + 22);
        *((_DWORD *)hWnd + 9) = 1026;
        *((_DWORD *)hWnd + 8) = sub_40218D(String1, (int *)hWnd + 9, v9, v10);
      }
      return 1;
    }
    if ( v6 == -108 )
    {
      if ( dword_407B38 == *((_DWORD *)hWnd + 4) )
      {
        dword_407564 = -dword_407564;
      }
      else
      {
        dword_407B38 = *((_DWORD *)hWnd + 4);
        dword_407564 = 1;
      }
      SetDlgItemTextA(hDlg, 1007, "Sorting...");
      SendMessageA(::hWnd, 0x1030u, *((_DWORD *)hWnd + 4), (LPARAM)sub_4036C8);
      SetDlgItemTextA(hDlg, 1007, "Ready");
      return 1;
    }
    if ( v6 != -5 )
      return 1;
    if ( *((int *)hWnd + 3) >= 0 && *((_DWORD *)hWnd + 3) < SendMessageA(::hWnd, 0x1004u, 0, 0) )
    {
      GetCursorPos(&Point);
      v8 = Point;
      SubMenu = GetSubMenu(hMenu, 0);
      TrackPopupMenu(SubMenu, 6u, v8.x, v8.y, 0, hDlg, 0);
      return 1;
    }
  }
  else if ( a2 == 272 )
  {
    ::hWnd = GetDlgItem(hDlg, 1004);
    dword_407138 = GetDlgItem(hDlg, 1092);
    sub_401689(::hWnd);
    SendMessageA(::hWnd, 0x102Fu, 0x1388u, 0);
    dword_407C94 = 1;
    SendDlgItemMessageA(hDlg, 1090, 0xF1u, 1u, 0);
    DlgItem = GetDlgItem(hDlg, 1000);
    SetFocus(DlgItem);
  }
  else if ( a2 == 273 && !dword_407B34 )
  {
    switch ( a3 )
    {
      case 0x3EAu:
        if ( dword_407B3C )
        {
          dword_407A04 = 1;
        }
        else
        {
          sub_401322(dword_4070E0);
          sub_4013AB(dword_4070E0);
          if ( lstrlenA(&::FileName) )
          {
            dword_407A04 = 0;
            dword_407B3C = 1;
            sub_40126F(::hWnd, 0);
            sub_40126F(dword_407138, 0);
            sub_401244();
            SetDlgItemTextA(hDlg, 1002, "S&top");
            SetDlgItemTextA(hDlg, 1007, "Scanning...");
            sub_401933(hDlg, dword_405BF8, 0);
            EnableWindow(dword_407578, 0);
            sub_4039A4(&::FileName);
            EnableWindow(dword_407578, 1);
            sub_401933(hDlg, dword_405BF8, 1);
            dword_407B3C = 0;
            SetDlgItemTextA(hDlg, 1002, "&Go");
            SetDlgItemTextA(hDlg, 1007, "Ready");
            sub_40126F(::hWnd, 1u);
            sub_40126F(dword_407138, 1u);
            sub_4011EC();
            sub_401C07();
          }
        }
        return 1;
      case 0x3EDu:
        if ( sub_4024C7((int)hDlg, FileName, 260, (int)"Open file for scanning", (int)"All files (*.*)", (int)"*.*") )
        {
          SetDlgItemTextA(hDlg, 1000, FileName);
          sub_401290(&::FileName, FileName, 260);
          dword_407140 = 0;
          dword_407B4C = 0;
        }
        return 1;
      case 0x3F2u:
        if ( sub_4024FE((int)hDlg, FileName, 260, (int)"Save text to file", (int)"Txt files (*.txt)", (int)"*.txt") )
        {
          SetDlgItemTextA(hDlg, 1007, "Saving...");
          sub_402C42(hDlg, FileName);
          SetDlgItemTextA(hDlg, 1007, "Ready");
        }
        return 1;
      case 0x3F3u:
        GetDlgItemTextA(hDlg, 1012, String, 256);
        sub_4037C0(String);
        return 1;
      case 0x442u:
        dword_407C94 = SendMessageA(hWnd, 0xF0u, 0, 0) == 1;
        sub_4011EC();
        return 1;
      case 0x9C41u:
        sub_402347();
        return 1;
    }
  }
  return 0;
}
// 405BF8: using guessed type int dword_405BF8[22];
// 407140: using guessed type int dword_407140;
// 407564: using guessed type int dword_407564;
// 407A04: using guessed type int dword_407A04;
// 407B34: using guessed type int dword_407B34;
// 407B38: using guessed type int dword_407B38;
// 407B3C: using guessed type int dword_407B3C;
// 407B4C: using guessed type int dword_407B4C;
// 407C94: using guessed type int dword_407C94;
// 403B01: using guessed type CHAR FileName[4];

//----- (00403F2F) --------------------------------------------------------
_DWORD *__thiscall sub_403F2F(_DWORD *this)
{
  _DWORD *result; // eax

  result = this;
  *this = &off_4061FC;
  this[1] = 0;
  this[2] = 0;
  this[3] = 256;
  this[4] = 32;
  this[5] = 0;
  this[6] = 0;
  this[7] = 0;
  this[8] = 0;
  this[9] = 0;
  return result;
}
// 4061FC: using guessed type int (__thiscall *off_4061FC)(void *, char);

//----- (00403F97) --------------------------------------------------------
int __thiscall sub_403F97(_DWORD *this, int a2)
{
  int result; // eax

  result = a2;
  if ( a2 )
    this[3] = a2;
  return result;
}

//----- (00403FA5) --------------------------------------------------------
int __thiscall sub_403FA5(_DWORD *this, int a2)
{
  int result; // eax

  result = a2;
  if ( a2 )
    this[4] = a2;
  return result;
}

//----- (00403FB3) --------------------------------------------------------
int __thiscall sub_403FB3(int this, LPCSTR lpString)
{
  int v3; // ebp
  void *v4; // eax
  unsigned int v5; // edx
  int v6; // eax
  void *v7; // eax
  unsigned int v8; // edx
  int v9; // eax
  char *v10; // eax
  char *v11; // esi
  char *v12; // ebp
  unsigned int v13; // eax
  bool v14; // zf
  unsigned int v15; // eax
  unsigned int v16; // esi
  void *v17; // eax
  int result; // eax
  unsigned int v19; // [esp-4h] [ebp-1Ch]
  int v20; // [esp+10h] [ebp-8h]
  void *v21; // [esp+14h] [ebp-4h]
  void *v22; // [esp+14h] [ebp-4h]

  v3 = lstrlenA(lpString);
  v20 = v3;
  if ( !*(_DWORD *)(this + 24) )
  {
    v19 = v3 + *(_DWORD *)(this + 12);
    *(_DWORD *)(this + 24) = v19;
    v4 = operator new(v19);
    v5 = *(_DWORD *)(this + 24);
    *(_DWORD *)(this + 4) = v4;
    memset(v4, 0, v5);
    v6 = *(_DWORD *)(this + 16);
    *(_DWORD *)(this + 32) = v6;
    v7 = operator new(4 * v6);
    v8 = 4 * *(_DWORD *)(this + 32);
    *(_DWORD *)(this + 8) = v7;
    memset(v7, 0, v8);
  }
  v9 = *(_DWORD *)(this + 20);
  if ( (unsigned int)(v9 + v3 + 1) >= *(_DWORD *)(this + 24) )
  {
    v21 = (void *)(v9 + *(_DWORD *)(this + 12) + v3 + 1);
    v10 = (char *)operator new((unsigned int)v21);
    v11 = v10;
    if ( !v10 )
      return -1;
    v12 = &v10[-*(_DWORD *)(this + 4)];
    memset(v10, 0, (unsigned int)v21);
    memmove(v10, *(const void **)(this + 4), *(_DWORD *)(this + 20));
    operator delete(*(void **)(this + 4));
    *(_DWORD *)(this + 24) = v21;
    v13 = 0;
    v14 = *(_DWORD *)(this + 36) == 0;
    *(_DWORD *)(this + 4) = v11;
    if ( !v14 )
    {
      do
        *(_DWORD *)(*(_DWORD *)(this + 8) + 4 * v13++) += v12;
      while ( v13 < *(_DWORD *)(this + 36) );
    }
    v3 = v20;
  }
  v15 = *(_DWORD *)(this + 28);
  if ( v15 < *(_DWORD *)(this + 32) )
  {
LABEL_11:
    qmemcpy((void *)(*(_DWORD *)(this + 4) + *(_DWORD *)(this + 20)), lpString, v3 + 1);
    *(_DWORD *)(*(_DWORD *)(this + 8) + 4 * *(_DWORD *)(this + 36)) = *(_DWORD *)(this + 4) + *(_DWORD *)(this + 20);
    result = *(_DWORD *)(this + 36);
    *(_DWORD *)(this + 20) += v3 + 1;
    ++*(_DWORD *)(this + 28);
    *(_DWORD *)(this + 36) = result + 1;
    return result;
  }
  v16 = v15 + *(_DWORD *)(this + 16);
  v17 = operator new(4 * v16);
  v22 = v17;
  if ( v17 )
  {
    memset(v17, 0, 4 * v16);
    memmove(v17, *(const void **)(this + 8), 4 * *(_DWORD *)(this + 28));
    operator delete(*(void **)(this + 8));
    *(_DWORD *)(this + 8) = v22;
    *(_DWORD *)(this + 32) = v16;
    goto LABEL_11;
  }
  return -1;
}

//----- (00404146) --------------------------------------------------------
int __thiscall sub_404146(_DWORD *this)
{
  return this[5];
}

//----- (0040414A) --------------------------------------------------------
int __thiscall sub_40414A(_DWORD *this)
{
  return this[9];
}

//----- (0040414E) --------------------------------------------------------
int __thiscall sub_40414E(_DWORD *this, unsigned int a2)
{
  if ( a2 >= this[9] )
    return 0;
  else
    return *(_DWORD *)(this[2] + 4 * a2);
}

//----- (00404164) --------------------------------------------------------
int __thiscall sub_404164(_DWORD *this)
{
  return this[1];
}

//----- (00404168) --------------------------------------------------------
void __thiscall sub_404168(void *this)
{
  void *v2; // eax

  *(_DWORD *)this = &off_4061FC;
  v2 = (void *)*((_DWORD *)this + 1);
  if ( v2 )
  {
    operator delete(v2);
    *((_DWORD *)this + 1) = 0;
  }
  if ( *((_DWORD *)this + 2) )
  {
    operator delete(*((void **)this + 2));
    *((_DWORD *)this + 2) = 0;
  }
  *((_DWORD *)this + 5) = 0;
  *((_DWORD *)this + 6) = 0;
  *((_DWORD *)this + 7) = 0;
  *((_DWORD *)this + 8) = 0;
  *((_DWORD *)this + 9) = 0;
}
// 4061FC: using guessed type int (__thiscall *off_4061FC)(void *, char);

//----- (00404173) --------------------------------------------------------
void *__thiscall sub_404173(void *this, char a2)
{
  sub_404168(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (004043B0) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (004043CA) --------------------------------------------------------
int sub_4043CA()
{
  sub_401D4A(dword_407CAC, 0, 0);
  return atexit(sub_40441E);
}
// 407CAC: using guessed type _DWORD dword_407CAC[4];

//----- (004043E4) --------------------------------------------------------
int sub_4043E4()
{
  sub_401E34(dword_407C9C, 0, 0);
  return atexit(sub_404428);
}
// 407C9C: using guessed type _DWORD dword_407C9C[4];

//----- (004043FE) --------------------------------------------------------
int sub_4043FE()
{
  sub_403F2F(dword_407CBC);
  return atexit(sub_404414);
}
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (00404414) --------------------------------------------------------
void __cdecl sub_404414()
{
  sub_404168(dword_407CBC);
}
// 407CBC: using guessed type _DWORD dword_407CBC[11];

//----- (0040441E) --------------------------------------------------------
void __cdecl sub_40441E()
{
  sub_403041(dword_407CAC);
}
// 407CAC: using guessed type _DWORD dword_407CAC[4];

//----- (00404428) --------------------------------------------------------
void __cdecl sub_404428()
{
  sub_40304C(dword_407C9C);
}
// 407C9C: using guessed type _DWORD dword_407C9C[4];

// nfuncs=108 queued=93 decompiled=93 lumina nreq=0 worse=0 better=0
// ALL OK, 93 function(s) have been successfully decompiled
