/* This file was generated by the Hex-Rays decompiler version 9.0.0.241217.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

void __cdecl sub_10001000(int a1, int a2, int a3, char a4);
struct _LIST_ENTRY *__fastcall sub_10001190(int a1, struct _LIST_ENTRY *a2);
struct _LIST_ENTRY *__cdecl sub_100012E0(const unsigned __int16 *a1, struct _LIST_ENTRY *a2);
int __fastcall sub_100013F0(int a1, _DWORD *a2, int a3, const char *a4);
int __fastcall sub_10001670(int a1, int a2);
int __thiscall sub_100016B0(const char *this);
void sub_100017F0();
int (__stdcall *sub_100019F0())(_DWORD);
__int16 sub_10001A10();
int (__stdcall *sub_10001BA0())(_DWORD, _DWORD);
int __fastcall sub_10001BC0(_DWORD *a1, int *a2);
BOOL __thiscall sub_10001D50(_DWORD *this);
int __thiscall sub_10001EE0(_DWORD *this);
unsigned int *__cdecl sub_10002020(char *a1, unsigned int a2);
int __cdecl sub_10002550(_DWORD *a1, const char *a2);
int sub_100025A0();
int __cdecl sub_10002610(unsigned __int64 a1);
BOOL __cdecl sub_10002710(int a1, int a2, __int64 a3);
unsigned __int8 __cdecl sub_100027D0(int a1, int a2, int a3, unsigned int a4, int a5);
void __cdecl sub_100028F0(_BYTE *a1, int a2);
struct _EXCEPTION_REGISTRATION_RECORD *sub_10002930();
int __cdecl sub_10002940(int a1, int a2, int a3, _DWORD *a4);
int __stdcall sub_10002970(struct _EXCEPTION_RECORD **a1);
int sub_10002A80();
int __cdecl sub_10002D90(int a1);
int sub_10002DA0();
unsigned __int8 __cdecl sub_10002ED0(int a1, int a2, int a3);
BOOL __stdcall DllEntryPoint(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved);
unsigned int Burepononavurluyoz();
unsigned int Pipalogatucuqugifm();
unsigned int Rujnemezecidocun();
unsigned int Jurafat();
unsigned int Levecasasudigedutevibl();
unsigned int Gexejnweti();
unsigned int Lefinimijic();
unsigned int Pulivedahamw();
unsigned int Casugupuyuzu();
int __cdecl sub_100037E0(unsigned __int8 *a1, unsigned __int8 *a2, int a3);
int __cdecl sub_10003830(int a1, unsigned __int16 *a2);
int __cdecl sub_10003890(int a1, char *a2, int a3);
char *__cdecl sub_100038C0(char *a1, unsigned __int8 a2, unsigned int a3);
_WORD *__cdecl sub_100038F0(_WORD *a1, int a2, unsigned int a3);
BOOL __cdecl sub_10003940(int *a1);
unsigned int sub_10003FC0();
int sub_100040A0(void); // weak
_DWORD *__cdecl sub_100041C0(_DWORD *a1);
int sub_10004470();
void __cdecl sub_1001A740(int a1, int a2);
void sub_1001A762();
int __stdcall sub_1001A770(int (__stdcall *a1)(int, int, int), int a2, int a3, int a4);
int __stdcall DllEntry_0(int a1, int a2);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_1001B000; // weak
_UNKNOWN unk_1001B008; // weak
_UNKNOWN unk_1001B020; // weak
_UNKNOWN unk_1001B04C; // weak
_UNKNOWN unk_1001B078; // weak
_UNKNOWN unk_1001B0A4; // weak
_UNKNOWN unk_1001B0D0; // weak
_UNKNOWN unk_1001B0FC; // weak
_UNKNOWN unk_1001B128; // weak
_UNKNOWN unk_1001B154; // weak
_UNKNOWN unk_1001B180; // weak
_UNKNOWN unk_1001B1AC; // weak
_UNKNOWN unk_1001B1D8; // weak
_UNKNOWN unk_100B4B08; // weak
_UNKNOWN unk_100B4B14; // weak
_UNKNOWN unk_100B4B20; // weak
_UNKNOWN unk_100B4B40; // weak
_UNKNOWN unk_100B4B54; // weak
_UNKNOWN unk_100B4B6C; // weak
_UNKNOWN unk_100B4B8C; // weak
_UNKNOWN unk_100B4BA8; // weak
_UNKNOWN unk_100B4BBC; // weak
_UNKNOWN unk_100B4BCC; // weak
_UNKNOWN unk_100B4BDC; // weak
_UNKNOWN unk_100B4BFC; // weak
_UNKNOWN unk_100B4C10; // weak
_UNKNOWN unk_100B4C28; // weak
_UNKNOWN unk_100B4C40; // weak
_UNKNOWN unk_100B4C58; // weak
_UNKNOWN unk_100B4C68; // weak
_UNKNOWN unk_100B5048; // weak
char byte_10442050 = '\0'; // weak
__int16 word_10442051 = 0; // weak
char byte_10442053 = '\0'; // weak
char byte_10442054 = '\0'; // weak
__int16 word_10442055 = 0; // weak
char byte_10442057 = '\0'; // weak
int dword_10442058 = 0; // weak
int dword_1044205C = 0; // weak
char byte_10442090[256] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // weak
char byte_10442190[] = { '\0' }; // weak
char byte_10442191 = '\0'; // weak
char byte_10442192 = '\0'; // weak
char byte_10442193 = '\0'; // weak
char byte_10442194 = '\0'; // weak
char byte_10442195 = '\0'; // weak
char byte_10442196 = '\0'; // weak
char byte_10442197 = '\0'; // weak
char byte_10442198 = '\0'; // weak
char byte_10442199 = '\0'; // weak
char byte_1044219A = '\0'; // weak
char byte_1044219B = '\0'; // weak
char byte_1044219C = '\0'; // weak
char byte_1044219D = '\0'; // weak
char byte_1044219E = '\0'; // weak
char byte_10442290; // weak
char byte_10442291; // weak
char byte_10442292; // weak
char byte_10442293; // weak
char byte_10442294; // weak
char byte_10442295; // weak
char byte_10442296; // weak
char byte_10442297; // weak
char byte_10442298; // weak
char byte_10442299; // weak
char byte_1044229A; // weak
char byte_1044229B; // weak
char byte_1044229C; // weak
char byte_1044229D; // weak
char byte_1044229E; // weak
int (__stdcall *dword_10443190)(_DWORD, _DWORD); // weak
int dword_10443194; // weak
int (__stdcall *dword_10443198)(_DWORD, _DWORD, _DWORD); // weak
int (__stdcall *dword_1044319C)(_DWORD); // weak
int (__stdcall *dword_104431A0)(_DWORD, _DWORD); // weak
int (__stdcall *dword_104431A4)(_DWORD, _DWORD); // weak
int dword_104431A8; // weak
int (__stdcall *dword_104431AC)(_DWORD, _DWORD, _DWORD); // weak
int (__stdcall *dword_104431B0)(_DWORD); // weak
int dword_104431B4; // weak
int dword_104431BC; // weak
int dword_104431C0; // weak
int dword_104431C4; // weak
int dword_104431C8; // weak
__int16 word_104431CC[128]; // weak
__int16 word_104432CC; // weak
__int16 word_104432CE; // weak
__int16 word_104432D0; // weak
char byte_104432D2; // weak
int dword_104432D4; // weak
signed __int32 dword_104432D8; // weak
int dword_104432DC; // weak
int dword_104432E0; // weak
int dword_104432E4; // weak
char byte_104432F0[256]; // weak
char byte_104433F0[256]; // weak
char byte_104434F0[256]; // weak
char byte_104435F0[256]; // weak
char byte_104436F0[256]; // weak
char byte_104437F0[256]; // weak
char byte_104438F0[256]; // weak
char byte_104439F0[256]; // weak
char byte_10443AF0[256]; // weak
char byte_10443BF0[256]; // weak
char byte_10443CF0[256]; // weak
char byte_10443DF0[256]; // weak
char byte_10443EF0[256]; // weak
char byte_10443FF0[256]; // weak
char byte_104440F0[256]; // weak
char byte_104441F0[256]; // weak
char byte_104442F0[256]; // weak
char byte_104443F0[]; // weak


//----- (10001000) --------------------------------------------------------
void __cdecl sub_10001000(int a1, int a2, int a3, char a4)
{
  char *v4; // edx
  int v5; // esi
  char *v6; // ecx
  int v7; // eax
  int v8; // ecx
  char *v9; // ecx
  int v10; // eax
  int v11; // ecx
  char *v12; // ecx
  int v13; // eax
  int v14; // ecx
  _BYTE v15[20]; // [esp+8h] [ebp-4Ch] BYREF
  __int64 v16; // [esp+1Ch] [ebp-38h]
  int v17; // [esp+24h] [ebp-30h]
  int v18; // [esp+28h] [ebp-2Ch]
  int v19; // [esp+2Ch] [ebp-28h]
  int v20; // [esp+30h] [ebp-24h]
  int v21; // [esp+34h] [ebp-20h]
  int v22; // [esp+38h] [ebp-1Ch]
  int v23; // [esp+3Ch] [ebp-18h]
  int v24; // [esp+40h] [ebp-14h]
  int v25; // [esp+44h] [ebp-10h]
  int v26; // [esp+48h] [ebp-Ch]
  int v27; // [esp+4Ch] [ebp-8h]
  _BYTE *v28; // [esp+50h] [ebp-4h]

  v4 = (char *)&a2;
  v5 = a1;
  if ( a1 <= 0 )
  {
    v25 = 0;
    v26 = 0;
  }
  else
  {
    v4 = &a4;
    v5 = a1 - 1;
    v25 = a2;
    v26 = a3;
  }
  v6 = v4;
  if ( v5 <= 0 )
  {
    v23 = 0;
    v24 = 0;
  }
  else
  {
    --v5;
    v4 += 8;
    v7 = *(_DWORD *)v6;
    v8 = *((_DWORD *)v6 + 1);
    v23 = v7;
    v24 = v8;
  }
  v9 = v4;
  if ( v5 <= 0 )
  {
    v21 = 0;
    v22 = 0;
  }
  else
  {
    --v5;
    v4 += 8;
    v10 = *(_DWORD *)v9;
    v11 = *((_DWORD *)v9 + 1);
    v21 = v10;
    v22 = v11;
  }
  v12 = v4;
  if ( v5 <= 0 )
  {
    v19 = 0;
    v20 = 0;
  }
  else
  {
    --v5;
    v4 += 8;
    v13 = *(_DWORD *)v12;
    v14 = *((_DWORD *)v12 + 1);
    v19 = v13;
    v20 = v14;
  }
  v17 = 0;
  *(_QWORD *)&v15[12] = (int)v4;
  v18 = 0;
  v16 = v5;
  v27 = (unsigned __int16)__FS__;
  v28 = v15;
  JUMPOUT(0x1001209A);
}
// 100010F9: control flows out of bounds to 1001209A

//----- (10001190) --------------------------------------------------------
struct _LIST_ENTRY *__fastcall sub_10001190(int a1, struct _LIST_ENTRY *a2)
{
  unsigned int v2; // esi
  unsigned __int16 *v3; // edi
  char v4; // al
  unsigned int v5; // edi
  int v6; // ebp
  struct _LIST_ENTRY *p_InLoadOrderModuleList; // ebx
  struct _LIST_ENTRY *Flink; // esi
  unsigned int Blink_low; // eax
  unsigned __int16 *v11; // [esp+10h] [ebp-C08h]
  unsigned __int16 v13[512]; // [esp+18h] [ebp-C00h] BYREF
  _WORD v14[512]; // [esp+418h] [ebp-800h] BYREF
  unsigned __int16 v15[512]; // [esp+818h] [ebp-400h] BYREF

  if ( a1 )
  {
    v2 = 0;
    v3 = v15;
    while ( 1 )
    {
      v4 = *(_BYTE *)(v2 + a1);
      if ( !v4 )
        break;
      ++v2;
      *v3++ = v4;
      if ( v2 >= 0x1FF )
        goto LABEL_7;
    }
    *v3 = 0;
LABEL_7:
    v11 = v15;
    v5 = wcslen(v15);
    if ( v5 >= 0x200 )
      v5 = 511;
    v6 = 2 * v5;
    sub_100038F0(v14, (int)v15, v5);
    v14[v5] = 0;
  }
  else
  {
    v5 = 0;
    v6 = 0;
    v11 = 0;
  }
  p_InLoadOrderModuleList = &NtCurrentTeb()->ProcessEnvironmentBlock->Ldr->InLoadOrderModuleList;
  if ( p_InLoadOrderModuleList
    || (p_InLoadOrderModuleList = &NtCurrentTeb()->ProcessEnvironmentBlock->Ldr->InMemoryOrderModuleList) != 0 )
  {
    Flink = p_InLoadOrderModuleList->Flink;
    if ( p_InLoadOrderModuleList->Flink != p_InLoadOrderModuleList )
    {
      while ( Flink )
      {
        if ( LOWORD(Flink[4].Blink) > 2u )
        {
          Blink_low = LOWORD(Flink[5].Blink);
          if ( Blink_low > 2 && Flink[3].Flink && (!v6 || v6 == Blink_low) )
          {
            sub_100038F0(v13, (int)Flink[6].Flink, v5);
            v13[v5] = 0;
            if ( (!a2 || a2 == Flink[3].Flink) && (!v11 || !sub_10003830((int)v14, v13)) )
              return Flink;
          }
        }
        Flink = Flink->Flink;
        if ( Flink == p_InLoadOrderModuleList )
          return 0;
      }
    }
  }
  return 0;
}

//----- (100012E0) --------------------------------------------------------
struct _LIST_ENTRY *__cdecl sub_100012E0(const unsigned __int16 *a1, struct _LIST_ENTRY *a2)
{
  unsigned int v2; // edi
  int v3; // ebp
  struct _LIST_ENTRY *p_InLoadOrderModuleList; // ebx
  struct _LIST_ENTRY *Flink; // esi
  unsigned int Blink_low; // eax
  unsigned __int16 v8[512]; // [esp+10h] [ebp-800h] BYREF
  _WORD v9[512]; // [esp+410h] [ebp-400h] BYREF

  v2 = 0;
  v3 = 0;
  if ( a1 )
  {
    v2 = wcslen(a1);
    if ( v2 >= 0x200 )
      v2 = 511;
    v3 = 2 * v2;
    sub_100038F0(v9, (int)a1, v2);
    v9[v2] = 0;
  }
  p_InLoadOrderModuleList = &NtCurrentTeb()->ProcessEnvironmentBlock->Ldr->InLoadOrderModuleList;
  if ( p_InLoadOrderModuleList
    || (p_InLoadOrderModuleList = &NtCurrentTeb()->ProcessEnvironmentBlock->Ldr->InMemoryOrderModuleList) != 0 )
  {
    Flink = p_InLoadOrderModuleList->Flink;
    if ( p_InLoadOrderModuleList->Flink != p_InLoadOrderModuleList )
    {
      while ( Flink )
      {
        if ( LOWORD(Flink[4].Blink) > 2u )
        {
          Blink_low = LOWORD(Flink[5].Blink);
          if ( Blink_low > 2 && Flink[3].Flink && (!v3 || v3 == Blink_low) )
          {
            sub_100038F0(v8, (int)Flink[6].Flink, v2);
            v8[v2] = 0;
            if ( (!a2 || a2 == Flink[3].Flink) && (!a1 || !sub_10003830((int)v9, v8)) )
              return Flink;
          }
        }
        Flink = Flink->Flink;
        if ( Flink == p_InLoadOrderModuleList )
          return 0;
      }
    }
  }
  return 0;
}

//----- (100013F0) --------------------------------------------------------
int __fastcall sub_100013F0(int a1, _DWORD *a2, int a3, const char *a4)
{
  _BYTE *v4; // edi
  const char *v7; // ecx
  int v8; // eax
  unsigned int v9; // edx
  unsigned int v10; // eax
  unsigned int v11; // esi
  int v12; // edx
  const char *v13; // eax
  int v14; // eax
  unsigned __int16 v16; // ax
  struct _LIST_ENTRY *v17; // eax
  int v18; // ecx
  char *v19; // eax
  int v20; // ecx
  unsigned int v21; // esi
  _BYTE *v22; // ebx
  char *v23; // ecx
  char v24; // al
  unsigned int v25; // edx
  _BYTE *v26; // ecx
  char *v27; // esi
  struct _LIST_ENTRY *v28; // eax
  int Flink; // eax
  int v30; // [esp+Ch] [ebp-418h] BYREF
  char v31; // [esp+10h] [ebp-414h]
  int v32; // [esp+14h] [ebp-410h] BYREF
  char v33; // [esp+18h] [ebp-40Ch]
  int v34; // [esp+1Ch] [ebp-408h]
  unsigned int v35; // [esp+20h] [ebp-404h]
  struct _LIST_ENTRY v36[64]; // [esp+24h] [ebp-400h] BYREF
  char v37[512]; // [esp+224h] [ebp-200h] BYREF

  v31 = 0;
  v4 = 0;
  v30 = 0;
  sub_10002ED0((int)&unk_100B4B08, 9, (int)&v30);
  v32 = 0;
  v33 = 0;
  sub_10002ED0((int)&unk_100B4B14, 9, (int)&v32);
  if ( !a1 )
    return (int)v4;
  if ( !a2 )
    return (int)v4;
  if ( !a3 )
    return (int)v4;
  v7 = a4;
  if ( !a4 )
    return (int)v4;
  v8 = a2[6];
  if ( !v8 && !a2[5] )
    return (int)v4;
  v9 = (unsigned int)a4 >> 16;
  v35 = (unsigned int)a4 >> 16;
  if ( !HIWORD(a4) )
  {
    v10 = a2[4];
    if ( (unsigned __int16)a4 >= v10 )
    {
      v11 = (unsigned __int16)a4 - v10;
      goto LABEL_19;
    }
    return (int)v4;
  }
  v11 = 0;
  v12 = a1 + a2[8];
  v34 = v12;
  if ( !v8 )
    return (int)v4;
  while ( 1 )
  {
    v13 = (const char *)(a1 + *(_DWORD *)(v12 + 4 * v11));
    if ( v13 )
      break;
LABEL_16:
    if ( ++v11 >= a2[6] )
      return 0;
  }
  v14 = strcmp(v13, v7);
  if ( v14 )
    v14 = v14 < 0 ? -1 : 1;
  if ( v14 )
  {
    v7 = a4;
    v12 = v34;
    goto LABEL_16;
  }
  LOWORD(v9) = v35;
LABEL_19:
  if ( v11 <= a2[5] )
  {
    v16 = (_WORD)v9 ? *(_WORD *)(a2[9] + 2 * v11 + a1) : v11;
    v4 = (_BYTE *)(a1 + *(_DWORD *)(a2[7] + 4 * v16 + a1));
    if ( v4 >= (_BYTE *)a2 && v4 < (_BYTE *)a2 + a3 )
    {
      sub_100038C0((char *)v36, 0, 0x200u);
      v17 = v36;
      v18 = 512;
      do
      {
        LOBYTE(v17->Flink) = 0;
        v17 = (struct _LIST_ENTRY *)((char *)v17 + 1);
        --v18;
      }
      while ( v18 );
      sub_100038C0(v37, 0, 0x200u);
      v19 = v37;
      v20 = 512;
      do
      {
        *v19++ = 0;
        --v20;
      }
      while ( v20 );
      v21 = 0;
      v22 = v4;
      if ( *v4 )
      {
        v23 = (char *)((char *)v36 - v4);
        do
        {
          if ( v21 >= 0x1FC )
            break;
          v24 = *v4;
          v4[(_DWORD)v23] = *v4;
          if ( v24 == 46 )
            break;
          ++v4;
          ++v21;
        }
        while ( *v4 );
      }
      *(struct _LIST_ENTRY **)((char *)&v36[0].Flink + v21 + 1) = (struct _LIST_ENTRY *)7105636;
      v4 = 0;
      if ( sub_100037E0((unsigned __int8 *)v36, (unsigned __int8 *)&v30, 4)
        && sub_100037E0((unsigned __int8 *)v36, (unsigned __int8 *)&v32, 4) )
      {
        v25 = 0;
        v26 = &v22[v21 + 1];
        if ( *v26 )
        {
          v27 = (char *)(v37 - v26);
          do
          {
            if ( v25 >= 0x1FF )
              break;
            ++v25;
            v26[(_DWORD)v27] = *v26;
            ++v26;
          }
          while ( *v26 );
        }
        v37[v25] = 0;
        v28 = sub_10001190(0, v36);
        if ( v28 )
          Flink = (int)v28[3].Flink;
        else
          Flink = sub_100016B0((const char *)v36);
        if ( Flink )
          return sub_10001670(Flink, (int)v37);
      }
    }
  }
  return (int)v4;
}

//----- (10001670) --------------------------------------------------------
int __fastcall sub_10001670(int a1, int a2)
{
  int v2; // eax
  int v3; // esi

  if ( !a1 )
    return 0;
  if ( !a2 )
    return 0;
  v2 = *(_DWORD *)(a1 + 60);
  if ( !v2 )
    return 0;
  v3 = *(_DWORD *)(v2 + a1 + 124);
  if ( v3 && *(_DWORD *)(v2 + a1 + 120) )
    return sub_100013F0(v3, a2);
  else
    return 0;
}
// 100013F0: using guessed type _DWORD __cdecl sub_100013F0(_DWORD, _DWORD);

//----- (100016B0) --------------------------------------------------------
int __thiscall sub_100016B0(const char *this)
{
  int (__stdcall *v2)(char *, _DWORD, int); // ebp
  int v3; // ecx
  unsigned int v4; // kr00_4
  unsigned int v5; // edx
  unsigned int i; // eax
  __int16 v7; // bx
  unsigned int j; // eax
  char v9; // bl
  unsigned int v10; // eax
  char *v11; // ecx
  char v12; // bl
  _DWORD v14[2]; // [esp+10h] [ebp-20Ch] BYREF
  __int16 v15; // [esp+18h] [ebp-204h]
  char v16; // [esp+1Ah] [ebp-202h]
  char v17[512]; // [esp+1Ch] [ebp-200h] BYREF

  if ( !this )
    return 0;
  v2 = (int (__stdcall *)(char *, _DWORD, int))dword_10443198;
  if ( !dword_10443198 )
    return 0;
  if ( dword_1044319C )
    return dword_10443198(this, 0, 2048);
  v14[0] = 0;
  v14[1] = 0;
  v15 = 0;
  v16 = 0;
  sub_10002ED0((int)&unk_100B4BBC, 15, (int)v14);
  sub_100038C0(v17, 0, 0x200u);
  v3 = 0;
  v4 = wcslen((const unsigned __int16 *)0x7FFE0030);
  if ( !v4 )
    return 0;
  v5 = strlen(this) + v4 + 12;
  if ( v5 > 0x200 )
    return 0;
  for ( i = 0; i < v5; ++i )
  {
    v7 = *(_WORD *)(2 * i + 0x7FFE0030);
    if ( !v7 )
      break;
    v17[i] = v7;
    ++v3;
  }
  for ( j = 0; j < v5; ++v3 )
  {
    v9 = *((_BYTE *)v14 + j);
    if ( !v9 )
      break;
    v17[v3] = v9;
    ++j;
  }
  v10 = 0;
  if ( v5 )
  {
    v11 = &v17[v3];
    do
    {
      v12 = this[v10];
      if ( !v12 )
        break;
      *v11 = v12;
      ++v10;
      ++v11;
    }
    while ( v10 < v5 );
  }
  return v2(v17, 0, 8);
}
// 10443198: using guessed type int (__stdcall *dword_10443198)(_DWORD, _DWORD, _DWORD);
// 1044319C: using guessed type int dword_1044319C;

//----- (100017F0) --------------------------------------------------------
void sub_100017F0()
{
  struct _LIST_ENTRY *v0; // eax
  struct _LIST_ENTRY *v1; // ebx
  int Flink; // ecx
  int v3; // eax
  int (__stdcall *v4)(_DWORD, _DWORD); // esi
  int v5; // edx
  int v6; // edi
  int v7; // ebp
  int v8; // edi
  int (__stdcall *v9)(_DWORD, _DWORD, _DWORD); // esi
  int v10; // ecx
  int v11; // edi
  int v12; // ebp
  int v13; // ebp
  int v14; // eax
  int v15; // eax
  int v16; // eax
  int v17; // edx
  int v18; // esi
  int v19; // edx
  int v20; // [esp+0h] [ebp-5Ch]
  _DWORD v21[3]; // [esp+4h] [ebp-58h] BYREF
  __int16 v22; // [esp+10h] [ebp-4Ch]
  char v23; // [esp+12h] [ebp-4Ah]
  _DWORD v24[3]; // [esp+14h] [ebp-48h] BYREF
  __int16 v25; // [esp+20h] [ebp-3Ch]
  char v26; // [esp+22h] [ebp-3Ah]
  _DWORD v27[6]; // [esp+24h] [ebp-38h] BYREF
  char v28; // [esp+3Ch] [ebp-20h]
  _DWORD v29[6]; // [esp+40h] [ebp-1Ch] BYREF
  __int16 v30; // [esp+58h] [ebp-4h]

  if ( !dword_10443194 )
  {
    memset(v29, 0, sizeof(v29));
    v30 = 0;
    sub_10002ED0((int)&unk_100B4B20, 30, (int)v29);
    memset(v21, 0, sizeof(v21));
    v22 = 0;
    v23 = 0;
    sub_10002ED0((int)&unk_100B4BA8, 19, (int)v21);
    memset(v24, 0, sizeof(v24));
    v25 = 0;
    v26 = 0;
    sub_10002ED0((int)&unk_100B4B40, 19, (int)v24);
    memset(v27, 0, sizeof(v27));
    v28 = 0;
    sub_10002ED0((int)&unk_100B4B6C, 29, (int)v27);
    v0 = sub_100012E0((const unsigned __int16 *)v29, 0);
    v1 = v0;
    if ( v0 )
    {
      Flink = (int)v0[3].Flink;
      v3 = Flink;
      v4 = 0;
      v5 = Flink;
      if ( Flink )
      {
        v6 = *(_DWORD *)(Flink + 60);
        if ( v6 )
        {
          v7 = *(_DWORD *)(v6 + Flink + 124);
          if ( v7 )
          {
            v8 = *(_DWORD *)(v6 + Flink + 120);
            if ( v8 )
            {
              v4 = (int (__stdcall *)(_DWORD, _DWORD))sub_100013F0(Flink, (_DWORD *)(v8 + Flink), v7, (const char *)v24);
              v3 = (int)v1[3].Flink;
              v5 = v3;
            }
          }
        }
      }
      if ( v4 )
        dword_10443190 = v4;
      v9 = 0;
      v10 = v3;
      v11 = v5;
      if ( v3 )
      {
        v12 = *(_DWORD *)(v3 + 60);
        if ( v12 )
        {
          v20 = *(_DWORD *)(v3 + v12 + 124);
          v10 = v3;
          if ( v20 )
          {
            v13 = *(_DWORD *)(v3 + v12 + 120);
            if ( v13 )
            {
              v14 = sub_100013F0(v3, (_DWORD *)(v3 + v13), v20, (const char *)v21);
              v10 = (int)v1[3].Flink;
              v9 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))v14;
              v11 = v10;
            }
          }
        }
      }
      if ( v9
        || dword_10443190
        && (v15 = dword_10443190(v11, v21),
            v10 = (int)v1[3].Flink,
            (v9 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))v15) != 0) )
      {
        dword_10443198 = v9;
      }
      v16 = 0;
      if ( v10 )
      {
        v17 = *(_DWORD *)(v10 + 60);
        if ( v17 )
        {
          v18 = *(_DWORD *)(v17 + v10 + 124);
          if ( v18 )
          {
            v19 = *(_DWORD *)(v17 + v10 + 120);
            if ( v19 )
              v16 = sub_100013F0(v10, (_DWORD *)(v10 + v19), v18, (const char *)v27);
          }
        }
      }
      if ( v16 || dword_10443190 && (v16 = dword_10443190(v1[3].Flink, v27)) != 0 )
        dword_1044319C = v16;
      if ( dword_10443198 )
      {
        if ( dword_10443190 )
          dword_10443194 = 1;
      }
    }
  }
}
// 10443190: using guessed type int (__stdcall *dword_10443190)(_DWORD, _DWORD);
// 10443194: using guessed type int dword_10443194;
// 10443198: using guessed type int (__stdcall *dword_10443198)(_DWORD, _DWORD, _DWORD);
// 1044319C: using guessed type int dword_1044319C;

//----- (100019F0) --------------------------------------------------------
int (__stdcall *sub_100019F0())(_DWORD)
{
  int (__stdcall *result)(_DWORD); // eax

  sub_100017F0();
  result = dword_1044319C;
  if ( dword_1044319C )
    return (int (__stdcall *)(_DWORD))dword_1044319C(2048);
  return result;
}
// 1044319C: invalid function type '?' has been ignored
// 1044319C: using guessed type int (__stdcall *dword_1044319C)(_DWORD);

//----- (10001A10) --------------------------------------------------------
__int16 sub_10001A10()
{
  struct _LIST_ENTRY *v0; // eax
  int Flink; // esi
  int v2; // eax
  int v3; // ecx
  int v4; // eax
  struct _LIST_ENTRY *v5; // edi
  int v6; // ecx
  int v7; // edx
  int v8; // ecx
  unsigned int v9; // ecx
  unsigned int i; // eax
  __int16 v11; // si
  unsigned int v12; // eax
  _WORD *v13; // edx
  __int16 v14; // si
  _DWORD v16[5]; // [esp+0h] [ebp-448h] BYREF
  int v17; // [esp+14h] [ebp-434h]
  _DWORD v18[5]; // [esp+18h] [ebp-430h] BYREF
  _DWORD v19[6]; // [esp+2Ch] [ebp-41Ch] BYREF
  __int16 v20; // [esp+44h] [ebp-404h]
  _WORD v21[512]; // [esp+48h] [ebp-400h] BYREF

  sub_100017F0();
  memset(v19, 0, sizeof(v19));
  v20 = 0;
  sub_10002ED0((int)&unk_100B4B20, 30, (int)v19);
  memset(v16, 0, sizeof(v16));
  LOBYTE(v17) = 0;
  sub_10002ED0((int)&unk_100B4B8C, 25, (int)v16);
  v0 = sub_100012E0((const unsigned __int16 *)v19, 0);
  if ( v0 )
  {
    Flink = (int)v0[3].Flink;
    sub_100017F0();
    if ( Flink )
    {
      v2 = *(_DWORD *)(Flink + 60);
      if ( v2 )
      {
        v3 = *(_DWORD *)(v2 + Flink + 124);
        if ( v3 )
        {
          v4 = *(_DWORD *)(v2 + Flink + 120);
          if ( v4 )
          {
            v5 = (struct _LIST_ENTRY *)sub_100013F0(Flink, (_DWORD *)(v4 + Flink), v3, (const char *)v16);
            if ( v5 )
              goto LABEL_9;
          }
        }
      }
    }
    LOWORD(v0) = (_WORD)dword_10443190;
    if ( dword_10443190 )
    {
      v0 = (struct _LIST_ENTRY *)dword_10443190(Flink, v16);
      v5 = v0;
      if ( v0 )
      {
LABEL_9:
        memset(v18, 0, sizeof(v18));
        sub_10002ED0((int)&unk_100B4B54, 24, (int)v18);
        sub_100038C0((char *)v21, 0, 0x400u);
        v6 = 2147352624;
        v7 = 0;
        do
        {
          LOWORD(v0) = *(_WORD *)v6;
          v6 += 2;
        }
        while ( (_WORD)v0 );
        v8 = (v6 - 2147352626) >> 1;
        if ( v8 )
        {
          v9 = v8 + 11;
          if ( v9 <= 0x200 )
          {
            for ( i = 0; i < v9; ++v7 )
            {
              v11 = *(_WORD *)(2 * v7 + 0x7FFE0030);
              if ( !v11 )
                break;
              v21[v7] = v11;
              ++i;
            }
            v12 = 0;
            if ( v9 )
            {
              v13 = &v21[v7];
              do
              {
                v14 = *((_WORD *)v18 + v12);
                if ( !v14 )
                  break;
                *v13 = v14;
                ++v12;
                ++v13;
              }
              while ( v12 < v9 );
            }
            LOWORD(v0) = ((int (__stdcall *)(_WORD *))v5)(v21);
          }
        }
      }
    }
  }
  return (__int16)v0;
}
// 10443190: using guessed type int (__stdcall *dword_10443190)(_DWORD, _DWORD);

//----- (10001BA0) --------------------------------------------------------
int (__stdcall *sub_10001BA0())(_DWORD, _DWORD)
{
  int (__stdcall *result)(_DWORD, _DWORD); // eax

  sub_100017F0();
  result = dword_10443190;
  if ( dword_10443190 )
    dword_104431A0 = (int)dword_10443190;
  return result;
}
// 10443190: using guessed type int (__stdcall *dword_10443190)(_DWORD, _DWORD);
// 104431A0: using guessed type int dword_104431A0;

//----- (10001BC0) --------------------------------------------------------
int __fastcall sub_10001BC0(_DWORD *a1, int *a2)
{
  unsigned int v2; // edi
  unsigned int v3; // esi
  int v5; // esi
  _DWORD *i; // eax
  int v7; // eax

  v2 = a2[2];
  if ( !v2 )
    return 1;
  if ( (a2[3] & 0x2000000) != 0 )
  {
    if ( *a2 == a2[1] )
    {
      if ( a2[4] || (v3 = a1[5], *(_DWORD *)(*a1 + 56) == v3) || !(v2 % v3) )
        sub_10002710(*a2, *a2 >> 31, v2);
    }
    return 1;
  }
  if ( dword_104431B4 )
  {
    v5 = 0;
    if ( *(_DWORD *)dword_104431B4 )
    {
      for ( i = (_DWORD *)(dword_104431B4 + 4); *i != 1725942529; ++i )
      {
        if ( (unsigned int)++v5 >= *(_DWORD *)dword_104431B4 )
          return 0;
      }
      if ( v5 != -1 )
      {
        sub_10002DA0();
        if ( dword_104432D4 )
          sub_10001000(v5, 5, -1, -1);
        else
          sub_1001A740(v5, 5);
        if ( v7 >= 0 )
          return 1;
      }
    }
  }
  return 0;
}
// 10001D40: variable 'v7' is possibly undefined
// 104431B4: using guessed type int dword_104431B4;
// 104432D4: using guessed type int dword_104432D4;

//----- (10001D50) --------------------------------------------------------
BOOL __thiscall sub_10001D50(_DWORD *this)
{
  int v1; // ebx
  int v2; // esi
  _DWORD *v3; // ebp
  int v4; // eax
  int v5; // ecx
  int v6; // eax
  int v7; // edx
  char *v8; // ebp
  unsigned int v9; // edi
  int v10; // eax
  int v11; // ebx
  int v12; // eax
  int v15; // [esp+18h] [ebp-24h]
  int v16; // [esp+1Ch] [ebp-20h]
  int v17; // [esp+20h] [ebp-1Ch]
  int v18; // [esp+24h] [ebp-18h]
  int v19; // [esp+28h] [ebp-14h] BYREF
  unsigned int v20; // [esp+2Ch] [ebp-10h]
  int v21; // [esp+30h] [ebp-Ch]
  int v22; // [esp+34h] [ebp-8h]
  int v23; // [esp+38h] [ebp-4h]

  v1 = *this;
  v2 = this[5];
  v3 = (_DWORD *)(v1 + *(unsigned __int16 *)(v1 + 20));
  v20 = 0;
  v19 = 0;
  v4 = v3[8];
  v16 = v4 & -v2;
  v20 = v16;
  v5 = v3[10];
  v21 = 0;
  v22 = 0;
  v15 = v4;
  v19 = v4;
  if ( !v5 )
  {
    v6 = v3[15];
    if ( (v6 & 0x40) != 0 )
    {
      v5 = *(_DWORD *)(v1 + 32);
    }
    else if ( (v6 & 0x80u) != 0 )
    {
      v5 = *(_DWORD *)(v1 + 36);
    }
  }
  v7 = v3[15];
  v21 = v5;
  v22 = v7;
  v23 = 0;
  v18 = 1;
  if ( *(_WORD *)(v1 + 6) <= 1u )
  {
LABEL_22:
    v23 = 1;
    return sub_10001BC0(this, &v19) != 0;
  }
  v8 = (char *)(v3 + 25);
  while ( 1 )
  {
    v17 = *((_DWORD *)v8 - 7);
    v9 = v17 & -v2;
    v10 = v2;
    if ( *((_DWORD *)v8 - 5) )
    {
LABEL_13:
      v11 = *((_DWORD *)v8 - 5);
      goto LABEL_14;
    }
    if ( (*v8 & 0x40) != 0 )
    {
      v11 = *(_DWORD *)(v1 + 32);
    }
    else
    {
      if ( *v8 >= 0 )
        goto LABEL_13;
      v11 = *(_DWORD *)(v1 + 36);
      v10 = this[5];
    }
LABEL_14:
    if ( v16 == v9 || (v2 = v10, v5 + v15 > v9) )
    {
      v12 = v7 & *(_DWORD *)v8;
      v7 |= *(_DWORD *)v8;
      if ( (v12 & 0x2000000) == 0 )
        v7 &= ~0x2000000u;
      v5 = v17 + v11 - v15;
      goto LABEL_21;
    }
    if ( !sub_10001BC0(this, &v19) )
      return 0;
    v5 = v11;
    v7 = *(_DWORD *)v8;
    v2 = this[5];
    v15 = v17;
    v19 = v17;
    v16 = v9;
    v20 = v9;
LABEL_21:
    v8 += 40;
    v22 = v7;
    v21 = v5;
    v1 = *this;
    if ( ++v18 >= *(unsigned __int16 *)(*this + 6) )
      goto LABEL_22;
  }
}

//----- (10001EE0) --------------------------------------------------------
int __thiscall sub_10001EE0(_DWORD *this)
{
  int v1; // eax
  int v2; // ebp
  int v3; // ecx
  int *v4; // ebx
  int v5; // eax
  int v6; // edi
  int Flink; // esi
  struct _LIST_ENTRY *v8; // eax
  int v9; // eax
  int v10; // edi
  int *v11; // ebx
  int v12; // eax
  int *v13; // edi
  bool i; // sf
  const char *v15; // edx
  int v16; // eax
  int v17; // ecx
  int v18; // ebp
  int v19; // ecx
  int v20; // eax
  bool v21; // zf
  int v23; // [esp+4h] [ebp-8h]
  int v24; // [esp+8h] [ebp-4h]

  v1 = *this;
  v2 = this[2];
  v23 = v2;
  v3 = *(_DWORD *)(*this + 128);
  if ( !v3 || !*(_DWORD *)(v1 + 132) )
    return 1;
  v4 = (int *)(v3 + v2);
  v24 = v3 + v2;
  if ( v3 + v2 )
  {
    do
    {
      v5 = v4[3];
      if ( !v5 )
        break;
      v6 = v5 + v2;
      Flink = sub_100016B0((const char *)(v5 + v2));
      if ( !Flink )
      {
        v8 = sub_10001190(v6, 0);
        if ( !v8 )
          return 0;
        Flink = (int)v8[3].Flink;
        if ( !Flink )
          return 0;
      }
      v9 = *v4;
      if ( !*v4 )
        v9 = v4[4];
      v10 = v4[4];
      v11 = (int *)(v9 + v2);
      v12 = *(_DWORD *)(v9 + v2);
      v13 = (int *)(v2 + v10);
      for ( i = v12 < 0; v12; i = v12 < 0 )
      {
        if ( i )
          v15 = (const char *)(unsigned __int16)v12;
        else
          v15 = (const char *)(v2 + v12 + 2);
        v16 = 0;
        if ( Flink )
        {
          if ( v15 )
          {
            v17 = *(_DWORD *)(Flink + 60);
            if ( v17 )
            {
              v18 = *(_DWORD *)(v17 + Flink + 124);
              if ( v18 )
              {
                v19 = *(_DWORD *)(v17 + Flink + 120);
                if ( v19 )
                  v16 = sub_100013F0(Flink, (_DWORD *)(v19 + Flink), v18, v15);
              }
              v2 = v23;
            }
          }
        }
        *v13 = v16;
        if ( !v16 )
        {
          v20 = *v11;
          if ( *v11 >= 0 )
            v20 += v2 + 2;
          else
            v20 = (unsigned __int16)v20;
          *v13 = dword_104431A0(Flink, v20);
        }
        if ( !*v13 )
          return 0;
        v12 = v11[1];
        ++v11;
        ++v13;
      }
      v21 = v24 == -20;
      v4 = (int *)(v24 + 20);
      v24 += 20;
    }
    while ( !v21 );
  }
  return 1;
}
// 104431A0: invalid function type '?' has been ignored
// 104431A0: using guessed type int (__stdcall *dword_104431A0)(_DWORD, _DWORD);

//----- (10002020) --------------------------------------------------------
unsigned int *__cdecl sub_10002020(char *a1, unsigned int a2)
{
  unsigned int v2; // esi
  unsigned int v3; // ebx
  int v4; // edi
  int *v5; // eax
  int v6; // ecx
  int v7; // edx
  unsigned int v8; // ecx
  int (*v9)(void); // eax
  int v10; // esi
  int v11; // eax
  int v12; // ecx
  int v13; // eax
  int v14; // edi
  int (__cdecl *v15)(int, int, int); // eax
  int v16; // esi
  int v17; // eax
  int v18; // ecx
  int v19; // eax
  unsigned int *v20; // esi
  int v22; // eax
  int v23; // ecx
  unsigned int *v24; // edi
  __int64 v25; // rax
  int v26; // esi
  unsigned int v27; // ecx
  int v28; // esi
  _BYTE *v29; // eax
  int v30; // esi
  int v31; // eax
  unsigned int v32; // edx
  _DWORD *v33; // ecx
  int i; // eax
  int v35; // ebx
  unsigned int v36; // esi
  _DWORD *v37; // edi
  _WORD *v38; // edx
  unsigned int v39; // esi
  _DWORD *v40; // eax
  unsigned int v41; // eax
  int v42; // esi
  int v43; // edi
  int (__stdcall **v44)(int, int, int); // esi
  int (__stdcall *j)(int, int, int); // eax
  int v46; // eax
  unsigned int *v47; // [esp+8h] [ebp-48h]
  int v48; // [esp+Ch] [ebp-44h]
  _DWORD *v49; // [esp+Ch] [ebp-44h]
  int v50; // [esp+10h] [ebp-40h]
  int v51; // [esp+14h] [ebp-3Ch]
  int v52; // [esp+18h] [ebp-38h]
  int v53; // [esp+1Ch] [ebp-34h]
  int v54; // [esp+20h] [ebp-30h]
  unsigned int v55; // [esp+24h] [ebp-2Ch]
  int v56; // [esp+2Ch] [ebp-24h]
  _DWORD v57[2]; // [esp+34h] [ebp-1Ch] BYREF
  __int16 v58; // [esp+3Ch] [ebp-14h]
  _DWORD v59[3]; // [esp+40h] [ebp-10h] BYREF
  __int16 v60; // [esp+4Ch] [ebp-4h]
  char v61; // [esp+4Eh] [ebp-2h]

  v2 = 0;
  if ( a2 < 0xF8 )
    return 0;
  v3 = (unsigned int)&a1[*(_DWORD *)a1];
  if ( v3 >= (unsigned int)&a1[a2] )
    return 0;
  if ( *(_WORD *)(v3 + 4) != 332 )
    return 0;
  v56 = *(_DWORD *)(v3 + 56);
  if ( (v56 & 1) != 0 )
    return 0;
  v4 = *(unsigned __int16 *)(v3 + 6);
  if ( *(_WORD *)(v3 + 6) )
  {
    v5 = (int *)(v3 + *(unsigned __int16 *)(v3 + 20) + 36);
    do
    {
      v6 = v5[1];
      v7 = *v5;
      if ( v6 )
        v8 = v7 + v6;
      else
        v8 = v7 + v56;
      if ( v8 > v2 )
        v2 = v8;
      v5 += 10;
      --v4;
    }
    while ( v4 );
  }
  if ( ((*(_DWORD *)(v3 + 80) + 4095) & 0xFFFFF000) != ((v2 + 4095) & 0xFFFFF000) || !sub_10002610(0LL) )
    return 0;
  v9 = (int (*)(void))dword_104432E4;
  if ( dword_104432E4 )
    goto LABEL_22;
  memset(v59, 0, sizeof(v59));
  v60 = 0;
  v61 = 0;
  sub_10002ED0((int)&unk_100B4BFC, 19, (int)v59);
  v10 = sub_100025A0();
  sub_100017F0();
  if ( v10 )
  {
    v11 = *(_DWORD *)(v10 + 60);
    if ( v11 )
    {
      v12 = *(_DWORD *)(v11 + v10 + 124);
      if ( v12 )
      {
        v13 = *(_DWORD *)(v11 + v10 + 120);
        if ( v13 )
        {
          v9 = (int (*)(void))sub_100013F0(v10, (_DWORD *)(v13 + v10), v12, (const char *)v59);
          if ( v9 )
          {
            dword_104432E4 = (int)v9;
LABEL_22:
            v14 = v9();
            goto LABEL_23;
          }
        }
      }
    }
  }
  if ( dword_10443190 )
  {
    v9 = (int (*)(void))dword_10443190(v10, v59);
    dword_104432E4 = (int)v9;
    if ( v9 )
      goto LABEL_22;
    v14 = 0;
  }
  else
  {
    dword_104432E4 = 0;
    v14 = 0;
  }
LABEL_23:
  v15 = (int (__cdecl *)(int, int, int))dword_104432E0;
  if ( !dword_104432E0 )
  {
    v57[0] = 0;
    v57[1] = 0;
    v58 = 0;
    sub_10002ED0((int)&unk_100B4BCC, 14, (int)v57);
    v16 = sub_100025A0();
    sub_100017F0();
    if ( !v16
      || (v17 = *(_DWORD *)(v16 + 60)) == 0
      || (v18 = *(_DWORD *)(v17 + v16 + 124)) == 0
      || (v19 = *(_DWORD *)(v17 + v16 + 120)) == 0
      || (v15 = (int (__cdecl *)(int, int, int))sub_100013F0(v16, (_DWORD *)(v19 + v16), v18, (const char *)v57)) == 0 )
    {
      if ( dword_10443190 )
      {
        v15 = (int (__cdecl *)(int, int, int))dword_10443190(v16, v57);
        dword_104432E0 = (int)v15;
        if ( v15 )
          goto LABEL_37;
      }
      else
      {
        dword_104432E0 = 0;
      }
LABEL_38:
      sub_10002710(v50, v50 >> 31, 0LL);
      return 0;
    }
    dword_104432E0 = (int)v15;
  }
LABEL_37:
  v20 = (unsigned int *)v15(v14, 8, 24);
  v47 = v20;
  if ( !v20 )
    goto LABEL_38;
  v20[2] = v50;
  v20[5] = 4096;
  if ( a2 < *(_DWORD *)(v3 + 84) )
    return 0;
  *v20 = v3;
  v22 = v50 - *(_DWORD *)(v3 + 52);
  *(_DWORD *)(v3 + 52) = v50;
  v23 = v20[2];
  v54 = v22;
  v51 = v23;
  v52 = 0;
  if ( !*(_WORD *)(*v20 + 6) )
    goto LABEL_55;
  v24 = (unsigned int *)(*v20 + *(unsigned __int16 *)(*v20 + 20) + 36);
  v25 = v23;
  v48 = v23 >> 31;
  v26 = v23;
  v53 = v23;
  do
  {
    v27 = v24[1];
    if ( v27 )
    {
      if ( a2 < v27 + v24[2] || !sub_10002610(__PAIR64__(HIDWORD(v25), v26) + *v24) )
        return 0;
      v30 = v51 + *v24;
      sub_10003890(v30, &a1[v24[2]], v24[1]);
      *(v24 - 1) = v30;
    }
    else
    {
      v28 = *(_DWORD *)(v3 + 56);
      if ( v28 <= 0 )
        goto LABEL_53;
      if ( !sub_10002610(__PAIR64__(v48, v53) + *v24) )
        return 0;
      v29 = (_BYTE *)(v51 + *v24);
      *(v24 - 1) = (unsigned int)v29;
      do
      {
        *v29++ = 0;
        --v28;
      }
      while ( v28 );
    }
    HIDWORD(v25) = v48;
LABEL_53:
    v24 += 10;
    ++v52;
    v26 = v53;
  }
  while ( v52 < *(unsigned __int16 *)(*v47 + 6) );
  v20 = v47;
LABEL_55:
  if ( !v54 )
    goto LABEL_76;
  if ( *(_DWORD *)(*v20 + 164) )
  {
    v32 = v20[2];
    v33 = (_DWORD *)(v32 + *(_DWORD *)(*v20 + 160));
    v55 = v32;
    v49 = v33;
    for ( i = *v33; *v33; i = *v33 )
    {
      v35 = i + v32;
      v36 = 0;
      v37 = v33 + 1;
      v38 = v33 + 2;
      if ( ((v33[1] - 8) & 0xFFFFFFFE) != 0 )
      {
        do
        {
          if ( (*v38 & 0xF000) == 0x3000 )
            *(_DWORD *)((*v38 & 0xFFF) + v35) += v54;
          ++v36;
          ++v38;
        }
        while ( v36 < (unsigned int)(*v37 - 8) >> 1 );
        v33 = v49;
      }
      v20 = v47;
      if ( dword_104431B4 )
      {
        v39 = 0;
        if ( *(_DWORD *)dword_104431B4 )
        {
          v40 = (_DWORD *)(dword_104431B4 + 4);
          while ( *v40 != -784939372 )
          {
            ++v39;
            ++v40;
            if ( v39 >= *(_DWORD *)dword_104431B4 )
              goto LABEL_74;
          }
          if ( v39 != -1 )
          {
            sub_10002DA0();
            if ( dword_104432D4 )
              sub_10001000(v39, 3, -1, -1);
            else
              sub_1001A740(v39, 3);
          }
        }
LABEL_74:
        v33 = v49;
        v20 = v47;
      }
      v33 = (_DWORD *)((char *)v33 + *v37);
      v32 = v55;
      v49 = v33;
    }
LABEL_76:
    v31 = 1;
    goto LABEL_77;
  }
  v31 = 0;
LABEL_77:
  v20[4] = v31;
  if ( !sub_10001EE0(v20) || !sub_10001D50(v20) )
    return 0;
  v41 = *v20;
  v42 = *(_DWORD *)(*v20 + 192);
  if ( v42 )
  {
    if ( *(_DWORD *)(v41 + 196) )
    {
      v43 = v47[2];
      v44 = *(int (__stdcall ***)(int, int, int))(v43 + v42 + 12);
      if ( v44 )
      {
        for ( j = *v44; j; ++v44 )
        {
          sub_1001A770(j, v43, 1, 0);
          j = v44[1];
        }
      }
    }
  }
  v46 = *(_DWORD *)(*v47 + 40);
  if ( !v46 )
    return v47;
  if ( ((int (__cdecl *)())(v50 + v46))() )
  {
    v47[3] = 1;
    return v47;
  }
  return 0;
}
// 10002257: variable 'v50' is possibly undefined
// 10443190: using guessed type int (__stdcall *dword_10443190)(_DWORD, _DWORD);
// 104431B4: using guessed type int dword_104431B4;
// 104432D4: using guessed type int dword_104432D4;
// 104432E0: using guessed type int dword_104432E0;
// 104432E4: using guessed type int dword_104432E4;

//----- (10002550) --------------------------------------------------------
int __cdecl sub_10002550(_DWORD *a1, const char *a2)
{
  int v2; // ecx
  int v3; // esi
  int *v4; // eax
  int v5; // ecx
  int v6; // eax

  v2 = 0;
  if ( !a1 )
    return v2;
  if ( !a2 )
    return v2;
  v3 = a1[2];
  if ( !v3 )
    return v2;
  v4 = (int *)(*a1 + 120);
  if ( *a1 == -120 )
    return v2;
  v5 = *v4;
  if ( *v4 )
  {
    v6 = *(_DWORD *)(*a1 + 124);
    if ( v6 )
      return sub_100013F0(v3, (_DWORD *)(v5 + v3), v6, a2);
  }
  return 0;
}

//----- (100025A0) --------------------------------------------------------
int sub_100025A0()
{
  int result; // eax
  struct _LIST_ENTRY *v1; // eax
  _DWORD v2[6]; // [esp+0h] [ebp-1Ch] BYREF
  __int16 v3; // [esp+18h] [ebp-4h]

  result = dword_104432DC;
  if ( !dword_104432DC )
  {
    memset(v2, 0, sizeof(v2));
    v3 = 0;
    sub_10002ED0((int)&unk_100B4BDC, 30, (int)v2);
    v1 = sub_100012E0((const unsigned __int16 *)v2, 0);
    if ( v1 && (result = (int)v1[3].Flink) != 0 )
      dword_104432DC = result;
    else
      return dword_104432DC;
  }
  return result;
}
// 104432DC: using guessed type int dword_104432DC;

//----- (10002610) --------------------------------------------------------
int __cdecl sub_10002610(unsigned __int64 a1)
{
  int v1; // esi
  _DWORD *i; // eax
  int v4; // eax

  if ( a1 && a1 < 0x1000 )
    return 0;
  sub_10002DA0();
  if ( !dword_104431B4 )
    return 0;
  v1 = 0;
  if ( !*(_DWORD *)dword_104431B4 )
    return 0;
  for ( i = (_DWORD *)(dword_104431B4 + 4); *i != -770038677; ++i )
  {
    if ( (unsigned int)++v1 >= *(_DWORD *)dword_104431B4 )
      return 0;
  }
  if ( v1 == -1 )
    return 0;
  sub_10002DA0();
  if ( dword_104432D4 )
    sub_10001000(v1, 6, -1, -1);
  else
    sub_1001A740(v1, 6);
  if ( v4 < 0 )
    return 0;
  else
    return HIDWORD(a1);
}
// 100026F5: variable 'v4' is possibly undefined
// 104431B4: using guessed type int dword_104431B4;
// 104432D4: using guessed type int dword_104432D4;

//----- (10002710) --------------------------------------------------------
BOOL __cdecl sub_10002710(int a1, int a2, __int64 a3)
{
  __int16 v3; // cx
  int v4; // esi
  _DWORD *i; // eax
  int v7; // eax

  if ( v3 < 0 && a3 )
    return 0;
  if ( !dword_104431B4 )
    return 0;
  v4 = 0;
  if ( !*(_DWORD *)dword_104431B4 )
    return 0;
  for ( i = (_DWORD *)(dword_104431B4 + 4); *i != -984224036; ++i )
  {
    if ( (unsigned int)++v4 >= *(_DWORD *)dword_104431B4 )
      return 0;
  }
  if ( v4 == -1 )
    return 0;
  sub_10002DA0();
  if ( dword_104432D4 )
    sub_10001000(v4, 4, -1, -1);
  else
    sub_1001A740(v4, 4);
  return v7 >= 0;
}
// 10002739: variable 'v3' is possibly undefined
// 100027C3: variable 'v7' is possibly undefined
// 104431B4: using guessed type int dword_104431B4;
// 104432D4: using guessed type int dword_104432D4;

//----- (100027D0) --------------------------------------------------------
unsigned __int8 __cdecl sub_100027D0(int a1, int a2, int a3, unsigned int a4, int a5)
{
  unsigned __int8 result; // al
  int v6; // ebp
  unsigned int v7; // ecx
  unsigned int i; // eax
  unsigned int j; // esi
  char v10; // bl
  int v11; // esi
  int v12; // ebp
  int v13; // edi
  char v14; // cl
  int v15; // [esp+4h] [ebp-104h]
  char v16[256]; // [esp+8h] [ebp-100h] BYREF

  result = (unsigned __int8)sub_100038C0(v16, 0, 0x100u);
  LOBYTE(v6) = 0;
  if ( a1 )
  {
    if ( a3 )
    {
      v7 = a4;
      if ( a4 )
      {
        if ( a5 )
        {
          for ( i = 0; i < 0x100; ++i )
            v16[i] = i;
          for ( j = 0; j < 0x100; ++j )
          {
            v10 = v16[j];
            v6 = (unsigned __int8)(v6 + *(_BYTE *)(j % v7 + a3) + v10);
            v7 = a4;
            result = v16[v6];
            v16[j] = result;
            v16[v6] = v10;
          }
          v11 = a2;
          LOBYTE(v12) = 0;
          v13 = a5;
          for ( LOBYTE(v15) = 0; v11; --v11 )
          {
            v12 = (unsigned __int8)(v12 + 1);
            ++v13;
            v14 = v16[v12];
            v15 = (unsigned __int8)(v14 + v15);
            v16[v12] = v16[v15];
            v16[v15] = v14;
            result = *(_BYTE *)(a1 - a5 + v13 - 1) ^ v16[(unsigned __int8)(v14 + v16[v12])];
            *(_BYTE *)(v13 - 1) = result;
          }
        }
      }
    }
  }
  return result;
}

//----- (100028F0) --------------------------------------------------------
void __cdecl sub_100028F0(_BYTE *a1, int a2)
{
  int v2; // eax

  if ( a1 && a2 )
  {
    v2 = a2 - 1;
    if ( a2 != 1 )
    {
      do
      {
        a1[v2] ^= a1[v2 - 1];
        --v2;
      }
      while ( v2 );
    }
    *a1 ^= a1[a2 - 1];
  }
}

//----- (10002930) --------------------------------------------------------
struct _EXCEPTION_REGISTRATION_RECORD *sub_10002930()
{
  return NtCurrentTeb()->NtTib.ExceptionList;
}

//----- (10002940) --------------------------------------------------------
int __cdecl sub_10002940(int a1, int a2, int a3, _DWORD *a4)
{
  if ( (*(_BYTE *)(a1 + 4) & 6) != 0 )
    return 1;
  *a4 = *(_DWORD *)(a2 + 8);
  return 2;
}

//----- (10002970) --------------------------------------------------------
int __stdcall sub_10002970(struct _EXCEPTION_RECORD **a1)
{
  struct _EXCEPTION_RECORD *v1; // esi
  struct _CONTEXT *v2; // ecx
  struct _EXCEPTION_REGISTRATION_RECORD *v3; // edi
  struct _EXCEPTION_REGISTRATION_RECORD *v4; // ebx
  int v5; // eax
  int v6; // eax
  _DWORD v8[20]; // [esp+Ch] [ebp-58h] BYREF
  struct _EXCEPTION_REGISTRATION_RECORD *v9; // [esp+5Ch] [ebp-8h]
  struct _EXCEPTION_REGISTRATION_RECORD *v10; // [esp+60h] [ebp-4h] BYREF
  struct _CONTEXT *v11; // [esp+6Ch] [ebp+8h]

  v1 = *a1;
  v11 = (struct _CONTEXT *)a1[1];
  v3 = sub_10002930();
  v4 = 0;
  v9 = v3;
  v10 = 0;
  if ( (int)v3 > 4096 )
  {
    while ( 1 )
    {
      v5 = v3->Handler(v1, v3, v2, &v10);
      if ( v4 == v3 )
      {
        v1->ExceptionFlags &= ~0x10u;
        v4 = 0;
      }
      if ( v5 )
        break;
      if ( (v1->ExceptionFlags & 1) != 0 )
      {
        v8[0] = -1073741787;
        v8[3] = 0;
LABEL_15:
        v8[1] = 1;
        v8[2] = v1;
        v8[4] = 0;
        dword_104431B0(v8);
        goto LABEL_16;
      }
      dword_104431A4(v11, 0);
LABEL_16:
      v3 = v3->Next;
      v2 = v11;
      v9 = v3;
      if ( (int)v3 <= 4096 )
        return dword_104431AC(v1, v2, 0);
    }
    v6 = v5 - 1;
    if ( !v6 )
    {
      if ( (v1->ExceptionFlags & 8) != 0 )
        dword_104431AC(v1, v11, 0);
      goto LABEL_16;
    }
    if ( v6 == 1 )
    {
      v1->ExceptionFlags |= 0x10u;
      if ( v10 > v4 )
        v4 = v10;
      goto LABEL_16;
    }
    v8[0] = -1073741786;
    goto LABEL_15;
  }
  return dword_104431AC(v1, v2, 0);
}
// 100029C0: variable 'v2' is possibly undefined
// 104431A4: using guessed type int (__stdcall *dword_104431A4)(_DWORD, _DWORD);
// 104431AC: using guessed type int (__stdcall *dword_104431AC)(_DWORD, _DWORD, _DWORD);
// 104431B0: using guessed type int (__stdcall *dword_104431B0)(_DWORD);

//----- (10002A80) --------------------------------------------------------
int sub_10002A80()
{
  int v0; // ebx
  struct _LIST_ENTRY *v1; // eax
  struct _LIST_ENTRY *v2; // edi
  int Flink; // esi
  int v4; // eax
  int v5; // ecx
  int v6; // eax
  int (__stdcall *v7)(_DWORD); // eax
  int v8; // esi
  int v9; // eax
  int v10; // ecx
  int v11; // eax
  int (__stdcall *v12)(_DWORD, _DWORD); // eax
  int v13; // esi
  int v14; // eax
  int v15; // ecx
  int v16; // eax
  int (__stdcall *v17)(_DWORD, _DWORD); // eax
  struct _LIST_ENTRY *v18; // eax
  int v19; // esi
  int v20; // eax
  int v21; // ecx
  int v22; // eax
  int (__stdcall *v23)(_DWORD, int (__stdcall *)(struct _EXCEPTION_RECORD **)); // eax
  _DWORD v25[2]; // [esp+8h] [ebp-80h] BYREF
  __int16 v26; // [esp+10h] [ebp-78h]
  char v27; // [esp+12h] [ebp-76h]
  _DWORD v28[4]; // [esp+14h] [ebp-74h] BYREF
  char v29; // [esp+24h] [ebp-64h]
  _DWORD v30[4]; // [esp+28h] [ebp-60h] BYREF
  __int16 v31; // [esp+38h] [ebp-50h]
  _DWORD v32[5]; // [esp+3Ch] [ebp-4Ch] BYREF
  _DWORD v33[6]; // [esp+50h] [ebp-38h] BYREF
  __int16 v34; // [esp+68h] [ebp-20h]
  _DWORD v35[7]; // [esp+6Ch] [ebp-1Ch] BYREF

  memset(v32, 0, sizeof(v32));
  v0 = 0;
  sub_10002ED0((int)&unk_100B4C28, 24, (int)v32);
  memset(v30, 0, sizeof(v30));
  v31 = 0;
  sub_10002ED0((int)&unk_100B4C40, 22, (int)v30);
  v25[0] = 0;
  v25[1] = 0;
  v26 = 0;
  v27 = 0;
  sub_10002ED0((int)&unk_100B4C58, 15, (int)v25);
  memset(v28, 0, sizeof(v28));
  v29 = 0;
  sub_10002ED0((int)&unk_100B4C10, 21, (int)v28);
  memset(v33, 0, sizeof(v33));
  v34 = 0;
  sub_10002ED0((int)&unk_100B4BDC, 30, (int)v33);
  memset(v35, 0, sizeof(v35));
  sub_10002ED0((int)&unk_100B4C68, 32, (int)v35);
  v1 = sub_100012E0((const unsigned __int16 *)v32, 0);
  v2 = v1;
  if ( !v1 )
    return v0;
  Flink = (int)v1[3].Flink;
  if ( !Flink )
    return v0;
  sub_100017F0();
  v4 = *(_DWORD *)(Flink + 60);
  if ( !v4
    || (v5 = *(_DWORD *)(v4 + Flink + 124)) == 0
    || (v6 = *(_DWORD *)(v4 + Flink + 120)) == 0
    || (v7 = (int (__stdcall *)(_DWORD))sub_100013F0(Flink, (_DWORD *)(v6 + Flink), v5, (const char *)v30)) == 0 )
  {
    v7 = (int (__stdcall *)(_DWORD))dword_10443190;
    if ( dword_10443190 )
      v7 = (int (__stdcall *)(_DWORD))dword_10443190(Flink, v30);
  }
  v8 = (int)v2[3].Flink;
  dword_104431B0 = v7;
  sub_100017F0();
  if ( !v8
    || (v9 = *(_DWORD *)(v8 + 60)) == 0
    || (v10 = *(_DWORD *)(v9 + v8 + 124)) == 0
    || (v11 = *(_DWORD *)(v9 + v8 + 120)) == 0
    || (v12 = (int (__stdcall *)(_DWORD, _DWORD))sub_100013F0(v8, (_DWORD *)(v11 + v8), v10, (const char *)v25)) == 0 )
  {
    v12 = dword_10443190;
    if ( dword_10443190 )
      v12 = (int (__stdcall *)(_DWORD, _DWORD))dword_10443190(v8, v25);
  }
  v13 = (int)v2[3].Flink;
  dword_104431A4 = v12;
  sub_100017F0();
  if ( !v13
    || (v14 = *(_DWORD *)(v13 + 60)) == 0
    || (v15 = *(_DWORD *)(v14 + v13 + 124)) == 0
    || (v16 = *(_DWORD *)(v14 + v13 + 120)) == 0
    || (v17 = (int (__stdcall *)(_DWORD, _DWORD))sub_100013F0(v13, (_DWORD *)(v16 + v13), v15, (const char *)v28)) == 0 )
  {
    v17 = dword_10443190;
    if ( dword_10443190 )
      v17 = (int (__stdcall *)(_DWORD, _DWORD))dword_10443190(v13, v28);
  }
  dword_104431AC = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))v17;
  if ( !dword_104431B0 )
    return v0;
  if ( !dword_104431A4 )
    return v0;
  if ( !v17 )
    return v0;
  v18 = sub_100012E0((const unsigned __int16 *)v33, 0);
  if ( !v18 )
    return v0;
  v19 = (int)v18[3].Flink;
  if ( !v19 )
    return v0;
  sub_100017F0();
  v20 = *(_DWORD *)(v19 + 60);
  if ( v20 )
  {
    v21 = *(_DWORD *)(v20 + v19 + 124);
    if ( v21 )
    {
      v22 = *(_DWORD *)(v20 + v19 + 120);
      if ( v22 )
      {
        v23 = (int (__stdcall *)(_DWORD, int (__stdcall *)(struct _EXCEPTION_RECORD **)))sub_100013F0(
                                                                                           v19,
                                                                                           (_DWORD *)(v22 + v19),
                                                                                           v21,
                                                                                           (const char *)v35);
        if ( v23 )
        {
          dword_104431A8 = (int)v23;
LABEL_36:
          if ( v23(0, sub_10002970) )
            return 1;
          return v0;
        }
      }
    }
  }
  if ( !dword_10443190 )
  {
    dword_104431A8 = 0;
    return 0;
  }
  v23 = (int (__stdcall *)(_DWORD, int (__stdcall *)(struct _EXCEPTION_RECORD **)))dword_10443190(v19, v35);
  dword_104431A8 = (int)v23;
  if ( v23 )
    goto LABEL_36;
  return v0;
}
// 10443190: using guessed type int (__stdcall *dword_10443190)(_DWORD, _DWORD);
// 104431A4: using guessed type int (__stdcall *dword_104431A4)(_DWORD, _DWORD);
// 104431A8: using guessed type int dword_104431A8;
// 104431AC: using guessed type int (__stdcall *dword_104431AC)(_DWORD, _DWORD, _DWORD);
// 104431B0: using guessed type int (__stdcall *dword_104431B0)(_DWORD);

//----- (10002D90) --------------------------------------------------------
int __cdecl sub_10002D90(int a1)
{
  int result; // eax

  result = a1;
  dword_104431B4 = a1;
  return result;
}
// 104431B4: using guessed type int dword_104431B4;

//----- (10002DA0) --------------------------------------------------------
int sub_10002DA0()
{
  int result; // eax
  int v1; // ebx
  struct _PEB *ProcessEnvironmentBlock; // esi
  int OSBuildNumber; // edx
  int Buffer; // eax
  int v5; // ecx
  int v6; // ecx

  result = _InterlockedCompareExchange(&dword_104432D8, 1, 0);
  if ( !result )
  {
    if ( NtCurrentTeb()->WOW32Reserved )
      dword_104432D4 = 1;
    v1 = 1;
    ProcessEnvironmentBlock = NtCurrentTeb()->ProcessEnvironmentBlock;
    dword_104431BC = ProcessEnvironmentBlock->OSMajorVersion;
    dword_104431C0 = ProcessEnvironmentBlock->OSMinorVersion;
    OSBuildNumber = ProcessEnvironmentBlock->OSBuildNumber;
    dword_104431C4 = OSBuildNumber;
    dword_104431C8 = ProcessEnvironmentBlock->OSPlatformId;
    Buffer = (int)ProcessEnvironmentBlock->CSDVersion.Buffer;
    if ( Buffer )
    {
      sub_100038F0(word_104431CC, Buffer, 0x7Fu);
      OSBuildNumber = dword_104431C4;
    }
    else
    {
      word_104431CC[0] = 0;
    }
    word_104432CC = HIBYTE(ProcessEnvironmentBlock->OSCSDVersion);
    word_104432CE = (unsigned __int8)ProcessEnvironmentBlock->OSCSDVersion;
    result = MEMORY[0x7FFE02D0];
    word_104432D0 = MEMORY[0x7FFE02D0];
    v5 = MEMORY[0x7FFE02D0];
    byte_104432D2 = 0;
    if ( MEMORY[0x7FFE0268] )
      v1 = MEMORY[0x7FFE0264];
    byte_104432D2 = v1;
    if ( v1 == 1 )
    {
      v5 = MEMORY[0x7FFE02D0] & 0xFFEF;
      word_104432D0 = MEMORY[0x7FFE02D0] & 0xFFEF;
    }
    if ( !OSBuildNumber )
    {
      result = sub_10002DA0(v5);
      if ( (unsigned int)dword_104431BC <= 6 && ((unsigned int)dword_104431BC < 6 || (unsigned int)dword_104431C0 < 4) )
      {
        result = sub_10002DA0(v6);
        if ( (unsigned int)dword_104431BC < 0xA )
          dword_104431C4 = 1;
      }
    }
  }
  return result;
}
// 10002EB1: variable 'v6' is possibly undefined
// 104431BC: using guessed type int dword_104431BC;
// 104431C0: using guessed type int dword_104431C0;
// 104431C4: using guessed type int dword_104431C4;
// 104431C8: using guessed type int dword_104431C8;
// 104431CC: using guessed type __int16 word_104431CC[128];
// 104432CC: using guessed type __int16 word_104432CC;
// 104432CE: using guessed type __int16 word_104432CE;
// 104432D0: using guessed type __int16 word_104432D0;
// 104432D2: using guessed type char byte_104432D2;
// 104432D4: using guessed type int dword_104432D4;
// 104432D8: using guessed type signed __int32 dword_104432D8;

//----- (10002ED0) --------------------------------------------------------
unsigned __int8 __cdecl sub_10002ED0(int a1, int a2, int a3)
{
  unsigned __int8 result; // al
  int v4; // edi
  int v5; // ebx
  unsigned int i; // eax
  unsigned int j; // esi
  char v8; // dl
  int v9; // edi
  int v10; // esi
  char v11; // cl
  int v12; // [esp+Ch] [ebp-108h]
  char v13[256]; // [esp+14h] [ebp-100h] BYREF

  result = (unsigned __int8)sub_100038C0(v13, 0, 0x100u);
  LOBYTE(v4) = 0;
  if ( a1 != -4 )
  {
    if ( a1 )
    {
      v5 = a3;
      if ( a3 )
      {
        for ( i = 0; i < 0x100; ++i )
          v13[i] = i;
        for ( j = 0; j < 0x100; ++j )
        {
          v8 = v13[j];
          v4 = (unsigned __int8)(v4 + *(_BYTE *)((j & 3) + a1) + v8);
          result = v13[v4];
          v13[j] = result;
          v13[v4] = v8;
        }
        LOBYTE(v9) = 0;
        LOBYTE(v12) = 0;
        v10 = a2 - 4;
        if ( a2 != 4 )
        {
          do
          {
            v9 = (unsigned __int8)(v9 + 1);
            ++v5;
            v11 = v13[v9];
            v12 = (unsigned __int8)(v11 + v12);
            v13[v9] = v13[v12];
            v13[v12] = v11;
            result = *(_BYTE *)(v5 + a1 + 4 - a3 - 1) ^ v13[(unsigned __int8)(v11 + v13[v9])];
            *(_BYTE *)(v5 - 1) = result;
            --v10;
          }
          while ( v10 );
        }
      }
    }
  }
  return result;
}

//----- (10002FD0) --------------------------------------------------------
BOOL __stdcall DllEntryPoint(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved)
{
  return 1;
}

//----- (10003000) --------------------------------------------------------
unsigned int Burepononavurluyoz()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104436F0[i] + byte_10443AF0[v3];
      byte_104436F0[i] = v4;
      byte_104436F0[i] = v4 + byte_104436F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104436F0[j] ^ byte_10443AF0[v7];
      byte_104436F0[j] = v8;
      byte_104436F0[j] = v8 ^ byte_104436F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104436F0[k] - byte_10443AF0[v11];
      byte_104436F0[k] = v12;
      byte_104436F0[k] = v12 - byte_104436F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104436F0[result] ^ byte_10443AF0[v15];
      byte_104436F0[result] = v16;
      byte_104436F0[result] = v16 ^ byte_104436F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (100030E0) --------------------------------------------------------
unsigned int Pipalogatucuqugifm()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104438F0[i] + byte_104437F0[v3];
      byte_104438F0[i] = v4;
      byte_104438F0[i] = v4 + byte_104438F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104438F0[j] ^ byte_104437F0[v7];
      byte_104438F0[j] = v8;
      byte_104438F0[j] = v8 ^ byte_104438F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104438F0[k] - byte_104437F0[v11];
      byte_104438F0[k] = v12;
      byte_104438F0[k] = v12 - byte_104438F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104438F0[result] ^ byte_104437F0[v15];
      byte_104438F0[result] = v16;
      byte_104438F0[result] = v16 ^ byte_104438F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (100031C0) --------------------------------------------------------
unsigned int Rujnemezecidocun()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104435F0[i] + byte_10443FF0[v3];
      byte_104435F0[i] = v4;
      byte_104435F0[i] = v4 + byte_104435F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104435F0[j] ^ byte_10443FF0[v7];
      byte_104435F0[j] = v8;
      byte_104435F0[j] = v8 ^ byte_104435F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104435F0[k] - byte_10443FF0[v11];
      byte_104435F0[k] = v12;
      byte_104435F0[k] = v12 - byte_104435F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104435F0[result] ^ byte_10443FF0[v15];
      byte_104435F0[result] = v16;
      byte_104435F0[result] = v16 ^ byte_104435F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (100032A0) --------------------------------------------------------
unsigned int Jurafat()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104442F0[i] + byte_104433F0[v3];
      byte_104442F0[i] = v4;
      byte_104442F0[i] = v4 + byte_104442F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104442F0[j] ^ byte_104433F0[v7];
      byte_104442F0[j] = v8;
      byte_104442F0[j] = v8 ^ byte_104442F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104442F0[k] - byte_104433F0[v11];
      byte_104442F0[k] = v12;
      byte_104442F0[k] = v12 - byte_104442F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104442F0[result] ^ byte_104433F0[v15];
      byte_104442F0[result] = v16;
      byte_104442F0[result] = v16 ^ byte_104442F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (10003380) --------------------------------------------------------
unsigned int Levecasasudigedutevibl()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104432F0[i] + byte_104443F0[v3];
      byte_104432F0[i] = v4;
      byte_104432F0[i] = v4 + byte_104432F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104432F0[j] ^ byte_104443F0[v7];
      byte_104432F0[j] = v8;
      byte_104432F0[j] = v8 ^ byte_104432F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104432F0[k] - byte_104443F0[v11];
      byte_104432F0[k] = v12;
      byte_104432F0[k] = v12 - byte_104432F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104432F0[result] ^ byte_104443F0[v15];
      byte_104432F0[result] = v16;
      byte_104432F0[result] = v16 ^ byte_104432F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (10003460) --------------------------------------------------------
unsigned int Gexejnweti()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_10443BF0[i] + byte_10443EF0[v3];
      byte_10443BF0[i] = v4;
      byte_10443BF0[i] = v4 + byte_10443BF0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_10443BF0[j] ^ byte_10443EF0[v7];
      byte_10443BF0[j] = v8;
      byte_10443BF0[j] = v8 ^ byte_10443BF0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_10443BF0[k] - byte_10443EF0[v11];
      byte_10443BF0[k] = v12;
      byte_10443BF0[k] = v12 - byte_10443BF0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_10443BF0[result] ^ byte_10443EF0[v15];
      byte_10443BF0[result] = v16;
      byte_10443BF0[result] = v16 ^ byte_10443BF0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (10003540) --------------------------------------------------------
unsigned int Lefinimijic()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104441F0[i] + byte_104434F0[v3];
      byte_104441F0[i] = v4;
      byte_104441F0[i] = v4 + byte_104441F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104441F0[j] ^ byte_104434F0[v7];
      byte_104441F0[j] = v8;
      byte_104441F0[j] = v8 ^ byte_104441F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104441F0[k] - byte_104434F0[v11];
      byte_104441F0[k] = v12;
      byte_104441F0[k] = v12 - byte_104441F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104441F0[result] ^ byte_104434F0[v15];
      byte_104441F0[result] = v16;
      byte_104441F0[result] = v16 ^ byte_104441F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (10003620) --------------------------------------------------------
unsigned int Pulivedahamw()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_104439F0[i] + byte_10443DF0[v3];
      byte_104439F0[i] = v4;
      byte_104439F0[i] = v4 + byte_104439F0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_104439F0[j] ^ byte_10443DF0[v7];
      byte_104439F0[j] = v8;
      byte_104439F0[j] = v8 ^ byte_104439F0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_104439F0[k] - byte_10443DF0[v11];
      byte_104439F0[k] = v12;
      byte_104439F0[k] = v12 - byte_104439F0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_104439F0[result] ^ byte_10443DF0[v15];
      byte_104439F0[result] = v16;
      byte_104439F0[result] = v16 ^ byte_104439F0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (10003700) --------------------------------------------------------
unsigned int Casugupuyuzu()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_10443CF0[i] + byte_104440F0[v3];
      byte_10443CF0[i] = v4;
      byte_10443CF0[i] = v4 + byte_10443CF0[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_10443CF0[j] ^ byte_104440F0[v7];
      byte_10443CF0[j] = v8;
      byte_10443CF0[j] = v8 ^ byte_10443CF0[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_10443CF0[k] - byte_104440F0[v11];
      byte_10443CF0[k] = v12;
      byte_10443CF0[k] = v12 - byte_10443CF0[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_10443CF0[result] ^ byte_104440F0[v15];
      byte_10443CF0[result] = v16;
      byte_10443CF0[result] = v16 ^ byte_10443CF0[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (100037E0) --------------------------------------------------------
int __cdecl sub_100037E0(unsigned __int8 *a1, unsigned __int8 *a2, int a3)
{
  int v6; // eax
  int v7; // edx

  do
  {
    v6 = *a1++;
    if ( (unsigned int)(v6 - 65) <= 0x19 )
      v6 += 32;
    v7 = *a2++;
    if ( (unsigned int)(v7 - 65) <= 0x19 )
      v7 += 32;
    --a3;
  }
  while ( a3 && v6 && v6 == v7 );
  return v6 - v7;
}

//----- (10003830) --------------------------------------------------------
int __cdecl sub_10003830(int a1, unsigned __int16 *a2)
{
  unsigned __int16 *v2; // edx
  int v3; // ecx
  unsigned __int16 v4; // ax
  int v5; // ecx

  v2 = a2;
  do
  {
    v3 = *(unsigned __int16 *)((char *)v2 + a1 - (_DWORD)a2);
    if ( (unsigned int)(v3 - 65) > 0x19 )
      v4 = *(unsigned __int16 *)((char *)v2 + a1 - (_DWORD)a2);
    else
      v4 = v3 + 32;
    v5 = *v2;
    if ( (unsigned int)(v5 - 65) <= 0x19 )
      LOWORD(v5) = v5 + 32;
    ++v2;
  }
  while ( v4 && v4 == (_WORD)v5 );
  return v4 - (unsigned __int16)v5;
}

//----- (10003890) --------------------------------------------------------
int __cdecl sub_10003890(int a1, char *a2, int a3)
{
  int result; // eax
  int v4; // esi
  char *v5; // edx
  char v6; // cl

  result = a1;
  v4 = a3;
  if ( a3 )
  {
    v5 = a2;
    do
    {
      v6 = *v5++;
      v5[a1 - (_DWORD)a2 - 1] = v6;
      --v4;
    }
    while ( v4 );
  }
  return result;
}

//----- (100038C0) --------------------------------------------------------
char *__cdecl sub_100038C0(char *a1, unsigned __int8 a2, unsigned int a3)
{
  if ( a3 )
  {
    memset32(a1, 16843009 * a2, a3 >> 2);
    memset(&a1[4 * (a3 >> 2)], a2, a3 & 3);
  }
  return a1;
}

//----- (100038F0) --------------------------------------------------------
_WORD *__cdecl sub_100038F0(_WORD *a1, int a2, unsigned int a3)
{
  unsigned int v3; // edx
  _WORD *v4; // edi
  __int16 v5; // cx
  _WORD *v7; // edi
  int i; // ecx

  v3 = a3;
  v4 = a1;
  if ( a3 )
  {
    while ( 1 )
    {
      v5 = *(_WORD *)((char *)v4 + a2 - (_DWORD)a1);
      --v3;
      *v4++ = v5;
      if ( !v5 )
        break;
      if ( !v3 )
        return a1;
    }
    if ( v3 )
    {
      memset(v4, 0, 4 * (v3 >> 1));
      v7 = &v4[2 * (v3 >> 1)];
      for ( i = v3 & 1; i; --i )
        *v7++ = 0;
    }
  }
  return a1;
}

//----- (10003940) --------------------------------------------------------
BOOL __cdecl sub_10003940(int *a1)
{
  struct _LIST_ENTRY *v1; // ebx
  struct _LIST_ENTRY *Flink; // ebp
  struct _LIST_ENTRY *Blink; // ebp
  bool v4; // zf
  char *v5; // ebp
  _DWORD *v6; // ebp
  struct _LIST_ENTRY *v7; // ebp
  _DWORD *v8; // ebp
  _DWORD *v9; // edx
  struct _LIST_ENTRY *v10; // ecx
  int v11; // ebp
  char *v12; // eax
  unsigned int v13; // ebx
  struct _LIST_ENTRY *v14; // eax
  int v15; // edx
  _BYTE *v16; // ecx
  _BYTE *v17; // ecx
  int i; // edx
  int v19; // eax
  unsigned int v20; // ebp
  unsigned int v21; // eax
  unsigned int v22; // edi
  unsigned int v23; // esi
  int v24; // edx
  unsigned int v25; // ecx
  _DWORD *v26; // edx
  int v27; // eax
  char v28; // al
  int v29; // edx
  BOOL result; // eax
  _DWORD v31[9]; // [esp+0h] [ebp-1F68h] BYREF
  char v32; // [esp+24h] [ebp-1F44h]
  BOOL v33; // [esp+28h] [ebp-1F40h]
  __int16 v34; // [esp+2Ch] [ebp-1F3Ch] BYREF
  char v35; // [esp+2Eh] [ebp-1F3Ah]
  _DWORD *v36; // [esp+30h] [ebp-1F38h]
  _DWORD v37[5]; // [esp+34h] [ebp-1F34h] BYREF
  _DWORD v38[1927]; // [esp+48h] [ebp-1F20h] BYREF
  struct _LIST_ENTRY *v39; // [esp+1E64h] [ebp-104h]
  struct _LIST_ENTRY *v40; // [esp+1E68h] [ebp-100h]
  char *v41; // [esp+1EE0h] [ebp-88h]
  _DWORD *v42; // [esp+1EFCh] [ebp-6Ch]
  _DWORD *v43; // [esp+1F00h] [ebp-68h]
  int v44; // [esp+1F04h] [ebp-64h]
  char *v45; // [esp+1F08h] [ebp-60h]
  BOOL v46; // [esp+1F5Ch] [ebp-Ch]
  char *v47; // [esp+1F60h] [ebp-8h]
  unsigned int v48; // [esp+1F64h] [ebp-4h]

  v33 = 0;
  v34 = 0;
  v35 = 0;
  sub_10002ED0((int)&unk_1001B000, 7, (int)&v34);
  memset(v37, 0, sizeof(v37));
  sub_10002ED0((int)&unk_1001B008, 24, (int)v37);
  sub_100038C0((char *)v38, 0, 0x1F20u);
  if ( *a1 )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B020, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  v1 = sub_100012E0((const unsigned __int16 *)v37, 0);
  v39 = v1;
  if ( !v1 )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B04C, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  Flink = v1[3].Flink;
  v40 = Flink;
  if ( !Flink )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B078, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  Blink = Flink[7].Blink;
  v4 = (struct _LIST_ENTRY *)((char *)v1[3].Flink + (unsigned int)Blink) == 0;
  v5 = (char *)v1[3].Flink + (unsigned int)Blink;
  v41 = v5;
  if ( v4 )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B0A4, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  v4 = v5 + 120 == 0;
  v6 = v5 + 120;
  v42 = v6;
  *(&byte_10442050 + 36) = v32;
  if ( v4 )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B0D0, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  v36 = (_DWORD *)*v6;
  v43 = v36;
  if ( !v36 )
    goto LABEL_28;
  if ( !v6[1] )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B0FC, 41, (int)v31);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  v7 = v1[3].Flink;
  v4 = (struct _LIST_ENTRY *)((char *)v7 + (_DWORD)v36) == 0;
  v8 = (struct _LIST_ENTRY **)((char *)&v7->Flink + (_DWORD)v36);
  v36 = v8;
  v38[1919] = v8;
  if ( v4 )
    goto LABEL_28;
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B128, 41, (int)v31);
  v9 = v36;
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  v10 = v1[3].Flink;
  v11 = v8[6];
  v45 = (char *)v10 + v9[7];
  v12 = (char *)v10 + v9[8];
  v44 = v11;
  v33 = (BOOL)v12;
  v46 = (BOOL)v12;
  v47 = (char *)v10 + v9[9];
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B154, 41, (int)v31);
  v13 = v48;
  v14 = v39;
  v15 = v33;
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  do
  {
    v16 = (char *)v14[3].Flink + *(_DWORD *)(v15 + 4 * v11 - 4);
    if ( !v16 )
      goto LABEL_17;
    v14 = v39;
    if ( *v16 != (_BYTE)v34 )
      goto LABEL_17;
    v15 = v33;
    if ( v16[1] != HIBYTE(v34) )
      goto LABEL_17;
    v17 = v16 + 2;
    for ( i = 1953446212; *v17; i = v19 + 65599 * i )
      v19 = *(unsigned __int16 *)v17++;
    v38[2 * v13 + 1] = i;
    v38[2 * v48 + 2] = *(_DWORD *)&v45[4 * *(unsigned __int16 *)&v47[2 * v44 - 2]];
    v13 = v48 + 1;
    v48 = v13;
    if ( v13 == 959 )
      break;
    v11 = v44;
    v33 = v46;
    v14 = v39;
    v15 = v46;
LABEL_17:
    v44 = --v11;
  }
  while ( v11 );
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B180, 41, (int)v31);
  v38[0] = v13;
  qmemcpy(&byte_10442050, v31, 0x24u);
  v20 = 0;
  *(&byte_10442050 + 36) = v32;
  if ( v13 != 1 )
  {
    do
    {
      memset(v31, 0, sizeof(v31));
      v32 = 0;
      sub_10002ED0((int)&unk_1001B1AC, 41, (int)v31);
      qmemcpy(&byte_10442050, v31, 0x24u);
      v21 = 0;
      *(&byte_10442050 + 36) = v32;
      if ( v13 - v20 != 1 )
      {
        do
        {
          v22 = v38[2 * v21 + 2];
          v23 = v38[2 * v21 + 4];
          if ( v22 > v23 )
          {
            v24 = v38[2 * v21 + 1];
            v38[2 * v21 + 1] = v38[2 * v21 + 3];
            v38[2 * v21 + 2] = v23;
            v38[2 * v21 + 3] = v24;
            v38[2 * v21 + 4] = v22;
            v13 = v38[0];
          }
          ++v21;
        }
        while ( v21 < v13 - v20 - 1 );
      }
      ++v20;
    }
    while ( v20 < v13 - 1 );
  }
  v25 = 0;
  *a1 = v13;
  if ( v13 )
  {
    v26 = a1 + 1;
    do
    {
      v27 = v38[2 * v25 + 1];
      ++v26;
      ++v25;
      *(v26 - 1) = v27;
    }
    while ( v25 < v13 );
  }
  memset(v31, 0, sizeof(v31));
  v32 = 0;
  sub_10002ED0((int)&unk_1001B1D8, 41, (int)v31);
  v28 = LOBYTE(v31[0]) ^ LOBYTE(v31[2]);
  qmemcpy(&byte_10442050, v31, 0x24u);
  *(&byte_10442050 + 36) = v32;
  v29 = *a1;
  byte_10442050 = v28;
  word_10442051 ^= *(_WORD *)((char *)&dword_10442058 + 1);
  byte_10442053 ^= HIBYTE(dword_10442058);
  v33 = v29 != 0;
LABEL_28:
  byte_10442054 ^= dword_1044205C;
  byte_10442057 ^= BYTE1(dword_1044205C) ^ word_10442055;
  result = v33;
  word_10442055 ^= *(_WORD *)((char *)&dword_1044205C + 1);
  return result;
}
// 10442050: using guessed type char byte_10442050;
// 10442051: using guessed type __int16 word_10442051;
// 10442053: using guessed type char byte_10442053;
// 10442054: using guessed type char byte_10442054;
// 10442055: using guessed type __int16 word_10442055;
// 10442057: using guessed type char byte_10442057;
// 10442058: using guessed type int dword_10442058;
// 1044205C: using guessed type int dword_1044205C;

//----- (10003FC0) --------------------------------------------------------
unsigned int sub_10003FC0()
{
  int v0; // esi
  unsigned __int8 v1; // bl
  unsigned int i; // edx
  int v3; // eax
  char v4; // cl
  unsigned __int8 v5; // bl
  unsigned int j; // edx
  int v7; // eax
  char v8; // cl
  unsigned __int8 v9; // bl
  unsigned int k; // edx
  int v11; // ecx
  char v12; // al
  unsigned __int8 v13; // bl
  unsigned int result; // eax
  int v15; // ecx
  char v16; // dl

  v0 = 0x2000;
  do
  {
    v1 = 1;
    for ( i = 0; i < 0x100; ++i )
    {
      v3 = v1++;
      v4 = byte_10442190[i] + byte_10442090[v3];
      byte_10442190[i] = v4;
      byte_10442190[i] = v4 + byte_10442190[v3];
    }
    v5 = 1;
    for ( j = 0; j < 0x100; ++j )
    {
      v7 = v5++;
      v8 = byte_10442190[j] ^ byte_10442090[v7];
      byte_10442190[j] = v8;
      byte_10442190[j] = v8 ^ byte_10442190[v7];
    }
    v9 = 1;
    for ( k = 0; k < 0x100; ++k )
    {
      v11 = v9++;
      v12 = byte_10442190[k] - byte_10442090[v11];
      byte_10442190[k] = v12;
      byte_10442190[k] = v12 - byte_10442190[v11];
    }
    v13 = 1;
    for ( result = 0; result < 0x100; ++result )
    {
      v15 = v13++;
      v16 = byte_10442190[result] ^ byte_10442090[v15];
      byte_10442190[result] = v16;
      byte_10442190[result] = v16 ^ byte_10442190[v15];
    }
    --v0;
  }
  while ( v0 );
  return result;
}

//----- (100041C0) --------------------------------------------------------
_DWORD *__cdecl sub_100041C0(_DWORD *a1)
{
  _DWORD *result; // eax
  _DWORD v2[64]; // [esp+0h] [ebp-100h] BYREF

  v2[0] = -1765792048;
  v2[1] = -1489903782;
  v2[2] = -1345071915;
  v2[3] = -3538870;
  v2[4] = 420222937;
  v2[5] = 806256305;
  v2[6] = 650231438;
  v2[7] = 1493978787;
  v2[8] = -311889325;
  v2[9] = -189859926;
  v2[10] = -1413271177;
  v2[11] = -1062504771;
  v2[12] = 1606344889;
  v2[13] = 1040903333;
  v2[14] = -1818542910;
  v2[15] = 1000268204;
  v2[16] = 410130813;
  v2[17] = -751106518;
  v2[18] = 1497777742;
  v2[19] = -2096121937;
  v2[20] = 2089071838;
  v2[21] = 496029020;
  v2[22] = 785623873;
  v2[23] = -1541293030;
  v2[24] = 327657497;
  v2[25] = 359095380;
  v2[26] = 920873397;
  v2[27] = 1102338636;
  v2[28] = -1436372771;
  v2[29] = 987310223;
  v2[30] = -1569160858;
  v2[31] = 728236387;
  v2[32] = 1215390257;
  v2[33] = 1265505029;
  v2[34] = -1050250534;
  v2[35] = 1476043578;
  v2[36] = 237271048;
  v2[37] = -5680793;
  v2[38] = -309288752;
  v2[39] = 1005350924;
  v2[40] = 1565066670;
  v2[41] = 890232721;
  v2[42] = 784356243;
  v2[43] = 353142246;
  v2[44] = 1984498678;
  v2[45] = 758625482;
  v2[46] = -463667262;
  v2[47] = 2112703619;
  v2[48] = 1489478966;
  v2[49] = 1768968359;
  v2[50] = 1948227260;
  v2[51] = 356703963;
  v2[52] = -1363602698;
  v2[53] = 1519575477;
  v2[54] = 1232228782;
  v2[55] = -1900592570;
  v2[56] = -867660173;
  v2[57] = -2083615795;
  v2[58] = -1554418809;
  v2[59] = 1490524417;
  v2[60] = 218176330;
  v2[61] = 1557662474;
  v2[62] = -441574521;
  v2[63] = 331116122;
  sub_100028F0(v2, 256);
  sub_100027D0((int)&unk_100B5048, 3723264, (int)v2, 0x100u, (int)&unk_100B5048);
  result = a1;
  *a1 = &unk_100B5048;
  return result;
}

//----- (10004470) --------------------------------------------------------
int sub_10004470()
{
  unsigned int *v0; // eax
  void (__stdcall *v1)(char *); // esi
  int result; // eax
  char *v3; // [esp+0h] [ebp-4h] BYREF

  v3 = 0;
  sub_100040A0();
  sub_10003FC0();
  if ( sub_10003940((int *)&byte_10442290) )
  {
    sub_10002D90((int)&byte_10442290);
    sub_100019F0();
    sub_10001A10();
    sub_10001BA0();
    sub_10002A80();
    sub_100041C0(&v3);
    if ( v3 )
    {
      v0 = sub_10002020(v3, 0x38D000u);
      if ( v0 )
      {
        v1 = (void (__stdcall *)(char *))sub_10002550(v0, (const char *)1);
        if ( v1 )
        {
          sub_10003FC0();
          v1(&byte_10442290);
          sub_10003FC0();
        }
      }
    }
  }
  sub_10003FC0();
  byte_10442290 ^= byte_10442298;
  byte_10442291 ^= byte_10442299;
  byte_10442292 ^= byte_1044229A;
  byte_10442293 ^= byte_1044229B;
  byte_10442294 ^= byte_1044229C;
  byte_10442296 ^= byte_1044229E;
  byte_10442190[0] ^= byte_10442198;
  byte_10442191 ^= byte_10442199;
  byte_10442192 ^= byte_1044219A;
  byte_10442193 ^= byte_1044219B;
  byte_10442297 ^= byte_1044229D ^ byte_10442295;
  byte_10442194 ^= byte_1044219C;
  result = (unsigned __int8)byte_1044219E;
  byte_10442196 ^= byte_1044219E;
  byte_10442295 ^= byte_1044229D;
  byte_10442197 ^= byte_1044219D ^ byte_10442195;
  byte_10442195 ^= byte_1044219D;
  return result;
}
// 100040A0: using guessed type int sub_100040A0(void);
// 10442191: using guessed type char byte_10442191;
// 10442192: using guessed type char byte_10442192;
// 10442193: using guessed type char byte_10442193;
// 10442194: using guessed type char byte_10442194;
// 10442195: using guessed type char byte_10442195;
// 10442196: using guessed type char byte_10442196;
// 10442197: using guessed type char byte_10442197;
// 10442198: using guessed type char byte_10442198;
// 10442199: using guessed type char byte_10442199;
// 1044219A: using guessed type char byte_1044219A;
// 1044219B: using guessed type char byte_1044219B;
// 1044219C: using guessed type char byte_1044219C;
// 1044219D: using guessed type char byte_1044219D;
// 1044219E: using guessed type char byte_1044219E;
// 10442290: using guessed type char byte_10442290;
// 10442291: using guessed type char byte_10442291;
// 10442292: using guessed type char byte_10442292;
// 10442293: using guessed type char byte_10442293;
// 10442294: using guessed type char byte_10442294;
// 10442295: using guessed type char byte_10442295;
// 10442296: using guessed type char byte_10442296;
// 10442297: using guessed type char byte_10442297;
// 10442298: using guessed type char byte_10442298;
// 10442299: using guessed type char byte_10442299;
// 1044229A: using guessed type char byte_1044229A;
// 1044229B: using guessed type char byte_1044229B;
// 1044229C: using guessed type char byte_1044229C;
// 1044229D: using guessed type char byte_1044229D;
// 1044229E: using guessed type char byte_1044229E;

//----- (1001A740) --------------------------------------------------------
void __cdecl sub_1001A740(int a1, int a2)
{
  do
    --a2;
  while ( a2 );
  sub_1001A762();
}

//----- (1001A762) --------------------------------------------------------
void sub_1001A762()
{
  __asm { sysenter }
}

//----- (1001A770) --------------------------------------------------------
int __stdcall sub_1001A770(int (__stdcall *a1)(int, int, int), int a2, int a3, int a4)
{
  return a1(a2, a3, a4);
}

//----- (120E0000) --------------------------------------------------------
int __stdcall DllEntry_0(int a1, int a2)
{
  sub_100040A0();
  sub_10003FC0();
  sub_10004470();
  sub_10003FC0();
  return 0;
}
// 100040A0: using guessed type int sub_100040A0(void);

// nfuncs=53 queued=50 decompiled=50 lumina nreq=0 worse=0 better=0
// ALL OK, 50 function(s) have been successfully decompiled
